export type HelpArticle = {
  id: string;
  category: string;
  title: string;
  summary: string;
  body: string[];
  route?: string;
  keywords: string[];
};

export const HELP_ARTICLES: HelpArticle[] = [
  { id:"connect-store",category:"Getting started",title:"Connect your store",summary:"Connect Zid or Salla and confirm PrizeSkout can read your store.",route:"/onboarding",keywords:["connect","zid","salla","onboarding"],body:["Open onboarding and choose your commerce platform.","Complete the platform authorization. Never paste store passwords or secret tokens into support chat.","After authorization, PrizeSkout verifies the connection and begins preparing your revenue view."] },
  { id:"restore-access",category:"Getting started",title:"Restore access to an existing account",summary:"Use your merchant email or PrizeSkout access code.",route:"/access",keywords:["login","access","restore","code","email"],body:["Open Access and choose Email or Access Code.","Email sends a secure sign-in link to the onboarded merchant address.","An access code restores the matching merchant workspace on the current device."] },
  { id:"first-profit-view",category:"Getting started",title:"Understand your first profit view",summary:"Learn what PrizeSkout needs before showing reliable profit.",route:"/dashboard/revenue-hub",keywords:["profit","revenue","first","empty"],body:["PrizeSkout combines sales, product cost, channel fees and payout evidence.","Complete missing cost and commission information before relying on margin totals.","Live channel prices remain in their original currency even when dashboard summaries use another display currency."] },
  { id:"channel-disconnected",category:"Channels and integrations",title:"Fix a disconnected channel",summary:"Reconnect a channel that stopped syncing.",route:"/dashboard/settings",keywords:["channel","disconnected","sync","reconnect"],body:["Open Settings and review Channels or Integrations.","Reconnect the affected platform and confirm the correct store account.","If reconnection repeatedly fails, contact human support with the platform name, time and visible error."] },
  { id:"sync-delay",category:"Channels and integrations",title:"Why data may be delayed",summary:"Understand normal processing and when to escalate.",keywords:["delay","sync","missing","processing"],body:["Channel events can take time to arrive and process.","Refresh the dashboard and confirm the channel remains connected.","Escalate if recent store activity remains missing after repeated refreshes or a dispatch shows a failure."] },
  { id:"safe-pricing",category:"Pricing and margins",title:"How protected price changes work",summary:"PrizeSkout asks before protected store changes.",route:"/dashboard/revenue-hub",keywords:["price","approval","change","margin"],body:["PrizeSkout evaluates configured margin floors and channel economics before recommending a price.","A protected change requires merchant approval.","After dispatch, PrizeSkout reads the result back when the connected channel supports verification."] },
  { id:"margin-floor",category:"Pricing and margins",title:"Set a margin floor",summary:"Define the minimum margin recommendations should preserve.",route:"/dashboard/settings",keywords:["margin","floor","minimum","rule"],body:["Open Settings and find margin rules.","Choose a floor that reflects product cost, channel commission and operating requirements.","Review recommendations after changing a floor because previously prepared actions may no longer be suitable."] },
  { id:"promotion-profit",category:"Promotions",title:"Check whether a promotion is profitable",summary:"Model discount, volume and channel costs before launch.",route:"/dashboard/revenue-hub",keywords:["promotion","discount","campaign","profit"],body:["Open the promotion simulator in Revenue Protection.","Enter the proposed discount and expected sales response.","Treat the result as a scenario, not a guarantee. Its reliability depends on configured costs and channel fees."] },
  { id:"payout-audit",category:"Payouts and recovery",title:"Run a payout audit",summary:"Compare expected payout with platform evidence.",route:"/dashboard/revenue-hub",keywords:["payout","audit","statement","expected"],body:["Upload or connect the relevant payout and sales evidence.","Confirm the statement period and configured contract terms.","Review discrepancies and evidence quality before starting a recovery case."] },
  { id:"recovery-case",category:"Payouts and recovery",title:"Create a recovery case",summary:"Organize a discrepancy and its supporting evidence.",route:"/dashboard/revenue-hub",keywords:["recovery","claim","evidence","dispute"],body:["Open the discrepancy from the payout workspace.","Confirm the amount, reason and evidence included in the case.","Submission and resolution still depend on the channel. PrizeSkout does not move money."] },
  { id:"noura-privacy",category:"Noura and support",title:"What Noura can and cannot do",summary:"Understand Noura's data and action safeguards.",keywords:["noura","chat","privacy","action"],body:["Noura explains PrizeSkout and guides troubleshooting.","Noura does not know private account facts unless the product securely supplies them and never asks for passwords or secret tokens.","Billing, security, account ownership, data deletion and sensitive store changes are escalated to people."] },
  { id:"human-support",category:"Noura and support",title:"Contact human support",summary:"Send a ticket or email the PrizeSkout team.",keywords:["human","email","ticket","support"],body:["Choose Human support in the Support window.","Describe the affected screen, channel, time and visible error.","You can also email support@prizeskout.qa directly."] },
];

export const HELP_CATEGORIES = Array.from(new Set(HELP_ARTICLES.map((article) => article.category)));
