import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { supabaseAdmin } from "@/integrations/supabase/client.server";
import { callAI } from "@/server/ai/providers";
import { NOURA_KNOWLEDGE, supportResponseTool } from "@/server/support-knowledge";

async function guard(supabase:any,userId:string){const {data,error}=await supabase.rpc("has_role",{_user_id:userId,_role:"admin"});if(error)throw new Error(error.message);if(!data)throw new Error("Admin role required");}
const count=async(table:string,apply?:(q:any)=>any)=>{let q=(supabaseAdmin as any).from(table).select("*",{count:"exact",head:true});if(apply)q=apply(q);const r=await q;return r.count??0;};

export const getPlatformOverview=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).handler(async({context})=>{await guard(context.supabase,context.userId);const day=new Date(Date.now()-86400000).toISOString(),sla=new Date(Date.now()-4*3600000).toISOString();const [users,channels,actions,recoveries,attention,tickets,urgentAttention,urgentTickets,staleTickets,audit]=await Promise.all([
  supabaseAdmin.auth.admin.listUsers({page:1,perPage:1}),count("ps_merchant_channels",q=>q.eq("status","connected")),count("ps_decide_results",q=>q.gte("created_at",day)),count("ps_recovery_cases",q=>q.in("status",["open","submitted","under_review"])),count("ps_attention_items",q=>q.neq("status","resolved")),count("contact_messages",q=>q.in("status",["open","in_progress","waiting_on_customer"])),count("ps_attention_items",q=>q.eq("severity","urgent").neq("status","resolved")),count("contact_messages",q=>q.eq("priority","urgent").in("status",["open","in_progress","waiting_on_customer"])),count("contact_messages",q=>q.eq("status","open").lt("created_at",sla)),(supabaseAdmin as any).from("ps_govern_audit_log").select("trace_id,event_type,account_id,merchant_id,source_platform,target_channel,summary_en,created_at").order("created_at",{ascending:false}).limit(12)
]);return{users:(users.data as any)?.total??users.data?.users?.length??0,channels,actions,recoveries,attention,tickets,urgentAttention,urgentTickets,staleTickets,audit:audit.data??[]};});

export const getPlatformMerchants=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).handler(async({context})=>{await guard(context.supabase,context.userId);const [users,channels,settings]=await Promise.all([supabaseAdmin.auth.admin.listUsers({page:1,perPage:1000}),(supabaseAdmin as any).from("ps_merchant_channels").select("account_id,platform,status,connected_at"),(supabaseAdmin as any).from("user_account_settings").select("user_id,company_name,country,currency,contact_email")]);const byUser=new Map((settings.data??[]).map((x:any)=>[x.user_id,x]));const byAccount=new Map<string,any[]>();for(const c of channels.data??[]){const a=byAccount.get(c.account_id)??[];a.push(c);byAccount.set(c.account_id,a);}return{merchants:(users.data?.users??[]).map(u=>{const s:any=byUser.get(u.id);return{id:u.id,email:u.email??"",created_at:u.created_at,last_sign_in_at:u.last_sign_in_at??null,company:s?.company_name??u.user_metadata?.company_name??null,country:s?.country??null,currency:s?.currency??null,channels:byAccount.get(u.id)??[]};})};});

export const getPlatformOperations=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).handler(async({context})=>{await guard(context.supabase,context.userId);const [tasks,recoveries,dispatches,attention]=await Promise.all([(supabaseAdmin as any).from("ps_store_manager_tasks").select("id,account_id,title,task_type,status,priority,risk_level,created_at").order("created_at",{ascending:false}).limit(100),(supabaseAdmin as any).from("ps_recovery_cases").select("id,account_id,platform,status,amount,currency,reason,created_at").order("created_at",{ascending:false}).limit(100),(supabaseAdmin as any).from("ps_dispatch_queue").select("id,account_id,target_channel,status,attempt_count,last_error,created_at").order("created_at",{ascending:false}).limit(100),(supabaseAdmin as any).from("ps_attention_items").select("id,account_id,title,severity,status,created_at").order("created_at",{ascending:false}).limit(100)]);return{tasks:tasks.data??[],recoveries:recoveries.data??[],dispatches:dispatches.data??[],attention:attention.data??[]};});

export const getSupportQueue=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).handler(async({context})=>{await guard(context.supabase,context.userId);const [tickets,roles,users,events]=await Promise.all([(supabaseAdmin as any).from("contact_messages").select("id,name,company,email,message,status,priority,assigned_to,admin_note,source,created_at,updated_at").order("created_at",{ascending:false}).limit(500),(supabaseAdmin as any).from("user_roles").select("user_id").eq("role","admin"),supabaseAdmin.auth.admin.listUsers({page:1,perPage:1000}),(supabaseAdmin as any).from("support_ticket_events").select("id,ticket_id,actor_id,event_type,body,metadata,created_at").order("created_at",{ascending:true}).limit(2000)]);if(tickets.error)throw new Error(tickets.error.message);const ids=new Set((roles.data??[]).map((x:any)=>x.user_id));const admins=(users.data?.users??[]).filter(x=>ids.has(x.id)).map(x=>({id:x.id,email:x.email??"Administrator"}));return{tickets:tickets.data??[],admins,events:events.error?[]:events.data??[]};});
const Ticket=z.object({id:z.string().uuid(),status:z.enum(["open","in_progress","waiting_on_customer","resolved","closed"]),priority:z.enum(["low","normal","high","urgent"]),note:z.string().max(5000).nullable(),assignedTo:z.string().uuid().nullable().optional()});
export const updateSupportTicket=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((x:unknown)=>Ticket.parse(x)).handler(async({data,context})=>{await guard(context.supabase,context.userId);const {data:before}=await(supabaseAdmin as any).from("contact_messages").select("status,priority,assigned_to").eq("id",data.id).maybeSingle();const patch:any={status:data.status,priority:data.priority,admin_note:data.note,updated_at:new Date().toISOString()};if(data.assignedTo!==undefined)patch.assigned_to=data.assignedTo;else if(data.status==="in_progress"&&!before?.assigned_to)patch.assigned_to=context.userId;const {error}=await (supabaseAdmin as any).from("contact_messages").update(patch).eq("id",data.id);if(error)throw new Error(error.message);await(supabaseAdmin as any).from("platform_admin_audit_log").insert({actor_id:context.userId,action:"support_ticket_updated",resource_type:"support_ticket",resource_id:data.id,details:{before,after:patch}});return{ok:true};});

const SupportEvent=z.object({ticketId:z.string().uuid(),type:z.enum(["note","reply"]),body:z.string().trim().min(1).max(10000)});
export const addSupportEvent=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((x:unknown)=>SupportEvent.parse(x)).handler(async({data,context})=>{await guard(context.supabase,context.userId);const {error}=await(supabaseAdmin as any).from("support_ticket_events").insert({ticket_id:data.ticketId,actor_id:context.userId,event_type:data.type,body:data.body});if(error)throw new Error(error.message);if(data.type==="reply")await(supabaseAdmin as any).from("contact_messages").update({status:"waiting_on_customer",assigned_to:context.userId,updated_at:new Date().toISOString()}).eq("id",data.ticketId);await(supabaseAdmin as any).from("platform_admin_audit_log").insert({actor_id:context.userId,action:`support_${data.type}_created`,resource_type:"support_ticket",resource_id:data.ticketId});return{ok:true};});

const Chat=z.object({message:z.string().trim().min(1).max(2000),history:z.array(z.object({role:z.enum(["user","assistant"]),content:z.string().max(3000)})).max(10).default([]),locale:z.string().max(10).default("en"),email:z.string().email().max(320).optional(),conversationId:z.string().uuid().optional(),page:z.string().max(300).optional()});
export const askSupportAgent=createServerFn({method:"POST"}).inputValidator((x:unknown)=>Chat.parse(x)).handler(async({data})=>{const transcript=data.history.map(x=>`${x.role}: ${x.content}`).join("\n");const result=await callAI({system:NOURA_KNOWLEDGE,user:`Current page: ${data.page??"unknown"}\n${transcript?`Conversation:\n${transcript}\n`:""}User: ${data.message}\nLocale: ${data.locale}`,maxTokens:600,tool:supportResponseTool});const payload=result.toolInput??{};const answer=String(payload.answer??result.text??"I could not prepare a reliable answer. Please contact human support.");const response={answer,confidence:["high","medium","low"].includes(String(payload.confidence))?String(payload.confidence):"low",escalate:Boolean(payload.escalate),suggestedRoute:String(payload.suggested_route??""),suggestedQuestions:Array.isArray(payload.suggested_questions)?payload.suggested_questions.map(String).slice(0,3):[]};const fullTranscript=[...data.history,{role:"user",content:data.message},{role:"assistant",content:answer}].map(x=>`${x.role==="user"?"Merchant":"Noura"}: ${x.content}`).join("\n\n").slice(0,5000);let conversationId=data.conversationId;try{if(conversationId){const{error}=await(supabaseAdmin as any).from("contact_messages").update({message:fullTranscript,priority:response.escalate?"high":"normal",updated_at:new Date().toISOString()}).eq("id",conversationId).eq("source","ai_chat");if(error)throw error}else{const{data:row,error}=await(supabaseAdmin as any).from("contact_messages").insert({name:data.email?data.email.split("@")[0]:"Support chat visitor",email:data.email??"anonymous@prizeskout.qa",message:fullTranscript,source:"ai_chat",status:"open",priority:response.escalate?"high":"normal"}).select("id").single();if(error)throw error;conversationId=row.id}}catch(error){console.error("Could not persist support chat",error)}return{...response,conversationId};});
