import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { supabaseAdmin } from "@/integrations/supabase/client.server";
import { callAI } from "@/server/ai/providers";

async function guard(supabase:any,userId:string){const {data,error}=await supabase.rpc("has_role",{_user_id:userId,_role:"admin"});if(error)throw new Error(error.message);if(!data)throw new Error("Admin role required");}
const count=async(table:string,apply?:(q:any)=>any)=>{let q=(supabaseAdmin as any).from(table).select("*",{count:"exact",head:true});if(apply)q=apply(q);const r=await q;return r.count??0;};

export const getPlatformOverview=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).handler(async({context})=>{await guard(context.supabase,context.userId);const day=new Date(Date.now()-86400000).toISOString();const [users,channels,actions,recoveries,attention,tickets,audit]=await Promise.all([
  supabaseAdmin.auth.admin.listUsers({page:1,perPage:1}),count("ps_merchant_channels",q=>q.eq("status","connected")),count("ps_decide_results",q=>q.gte("created_at",day)),count("ps_recovery_cases",q=>q.in("status",["open","submitted","under_review"])),count("ps_attention_items",q=>q.neq("status","resolved")),count("contact_messages",q=>q.in("status",["open","in_progress","waiting_on_customer"])),(supabaseAdmin as any).from("ps_govern_audit_log").select("trace_id,event_type,account_id,merchant_id,source_platform,target_channel,summary_en,created_at").order("created_at",{ascending:false}).limit(12)
]);return{users:(users.data as any)?.total??users.data?.users?.length??0,channels,actions,recoveries,attention,tickets,audit:audit.data??[]};});

export const getPlatformMerchants=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).handler(async({context})=>{await guard(context.supabase,context.userId);const [users,channels,settings]=await Promise.all([supabaseAdmin.auth.admin.listUsers({page:1,perPage:1000}),(supabaseAdmin as any).from("ps_merchant_channels").select("account_id,platform,status,connected_at"),(supabaseAdmin as any).from("user_account_settings").select("user_id,company_name,country,currency,contact_email")]);const byUser=new Map((settings.data??[]).map((x:any)=>[x.user_id,x]));const byAccount=new Map<string,any[]>();for(const c of channels.data??[]){const a=byAccount.get(c.account_id)??[];a.push(c);byAccount.set(c.account_id,a);}return{merchants:(users.data?.users??[]).map(u=>{const s:any=byUser.get(u.id);return{id:u.id,email:u.email??"",created_at:u.created_at,last_sign_in_at:u.last_sign_in_at??null,company:s?.company_name??u.user_metadata?.company_name??null,country:s?.country??null,currency:s?.currency??null,channels:byAccount.get(u.id)??[]};})};});

export const getPlatformOperations=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).handler(async({context})=>{await guard(context.supabase,context.userId);const [tasks,recoveries,dispatches,attention]=await Promise.all([(supabaseAdmin as any).from("ps_store_manager_tasks").select("id,account_id,title,task_type,status,priority,risk_level,created_at").order("created_at",{ascending:false}).limit(100),(supabaseAdmin as any).from("ps_recovery_cases").select("id,account_id,platform,status,amount,currency,reason,created_at").order("created_at",{ascending:false}).limit(100),(supabaseAdmin as any).from("ps_dispatch_queue").select("id,account_id,target_channel,status,attempt_count,last_error,created_at").order("created_at",{ascending:false}).limit(100),(supabaseAdmin as any).from("ps_attention_items").select("id,account_id,title,severity,status,created_at").order("created_at",{ascending:false}).limit(100)]);return{tasks:tasks.data??[],recoveries:recoveries.data??[],dispatches:dispatches.data??[],attention:attention.data??[]};});

export const getSupportQueue=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).handler(async({context})=>{await guard(context.supabase,context.userId);const {data,error}=await (supabaseAdmin as any).from("contact_messages").select("id,name,company,email,message,status,priority,assigned_to,admin_note,source,created_at,updated_at").order("created_at",{ascending:false}).limit(300);if(error)throw new Error(error.message);return{tickets:data??[]};});
const Ticket=z.object({id:z.string().uuid(),status:z.enum(["open","in_progress","waiting_on_customer","resolved","closed"]),priority:z.enum(["low","normal","high","urgent"]),note:z.string().max(5000).nullable()});
export const updateSupportTicket=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((x:unknown)=>Ticket.parse(x)).handler(async({data,context})=>{await guard(context.supabase,context.userId);const patch:any={status:data.status,priority:data.priority,admin_note:data.note,updated_at:new Date().toISOString()};if(data.status==="in_progress")patch.assigned_to=context.userId;const {error}=await (supabaseAdmin as any).from("contact_messages").update(patch).eq("id",data.id);if(error)throw new Error(error.message);return{ok:true};});

const Chat=z.object({message:z.string().trim().min(1).max(2000),history:z.array(z.object({role:z.enum(["user","assistant"]),content:z.string().max(3000)})).max(10).default([]),locale:z.string().max(10).default("en"),email:z.string().email().max(320).optional(),conversationId:z.string().uuid().optional()});
export const askSupportAgent=createServerFn({method:"POST"}).inputValidator((x:unknown)=>Chat.parse(x)).handler(async({data})=>{const transcript=data.history.map(x=>`${x.role}: ${x.content}`).join("\n");const result=await callAI({system:"You are PrizeSkout Support for a GCC merchant Revenue Protection platform. Help with onboarding, Zid and Salla connections, pricing and margin decisions, promotions, payout audits, recovery cases, and navigation. Never invent account data or claim to perform an action. Escalate billing, security, access, deletion, and unresolved technical issues to a human ticket. Answer in the user's language, concisely, under 180 words.",user:`${transcript?`Conversation:\n${transcript}\n`:""}User: ${data.message}\nLocale: ${data.locale}`,maxTokens:420});const fullTranscript=[...data.history,{role:"user",content:data.message},{role:"assistant",content:result.text}].map(x=>`${x.role==="user"?"Merchant":"PrizeSkout Support"}: ${x.content}`).join("\n\n").slice(0,5000);let conversationId=data.conversationId;try{if(conversationId){const{error}=await(supabaseAdmin as any).from("contact_messages").update({message:fullTranscript,updated_at:new Date().toISOString()}).eq("id",conversationId).eq("source","ai_chat");if(error)throw error}else{const{data:row,error}=await(supabaseAdmin as any).from("contact_messages").insert({name:data.email?data.email.split("@")[0]:"Support chat visitor",email:data.email??"anonymous@prizeskout.qa",message:fullTranscript,source:"ai_chat",status:"open",priority:"normal"}).select("id").single();if(error)throw error;conversationId=row.id}}catch(error){console.error("Could not persist support chat",error)}return{answer:result.text,conversationId};});
