import { createFileRoute } from "@tanstack/react-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useServerFn } from "@tanstack/react-start";
import { Clock3, Mail, RefreshCw, Search, Send, StickyNote, UserRoundCheck } from "lucide-react";
import { toast } from "sonner";
import { addSupportEvent, getSupportQueue, updateSupportTicket } from "@/server/platform-admin.functions";
import { Empty, ErrorState, Skeleton, Title, secondaryButton } from "./admin.index";

export const Route = createFileRoute("/admin/support")({ component: Page });
type Status="open"|"in_progress"|"waiting_on_customer"|"resolved"|"closed"; type Priority="low"|"normal"|"high"|"urgent";
type Ticket={id:string;name:string;company:string|null;email:string;message:string;status:Status;priority:Priority;assigned_to:string|null;admin_note:string|null;source:string;created_at:string;updated_at:string};
type Event={id:string;ticket_id:string;actor_id:string|null;event_type:string;body:string|null;created_at:string}; type Admin={id:string;email:string};

function Page(){
  const load=useServerFn(getSupportQueue),save=useServerFn(updateSupportTicket),addEvent=useServerFn(addSupportEvent);
  const[rows,setRows]=useState<Ticket[]>([]),[events,setEvents]=useState<Event[]>([]),[admins,setAdmins]=useState<Admin[]>([]),[id,setId]=useState<string>(),[q,setQ]=useState(""),[status,setStatus]=useState("active"),[priority,setPriority]=useState("all"),[source,setSource]=useState("all"),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[draft,setDraft]=useState(""),[draftType,setDraftType]=useState<"note"|"reply">("note");
  const refresh=useCallback(async()=>{setLoading(true);setError("");try{const x=await load();setRows(x.tickets as Ticket[]);setEvents((x.events??[])as Event[]);setAdmins((x.admins??[])as Admin[]);setId(v=>v&&x.tickets.some((t:any)=>t.id===v)?v:x.tickets[0]?.id)}catch(e){setError(e instanceof Error?e.message:"Could not load support.")}finally{setLoading(false)}},[load]);
  useEffect(()=>{void refresh()},[refresh]);
  const shown=useMemo(()=>rows.filter(x=>(status==="all"||status==="active"&&["open","in_progress","waiting_on_customer"].includes(x.status)||x.status===status)&&(priority==="all"||x.priority===priority)&&(source==="all"||x.source===source)&&`${x.name} ${x.email} ${x.message}`.toLowerCase().includes(q.toLowerCase())),[rows,q,status,priority,source]);
  const ticket=rows.find(x=>x.id===id),timeline=events.filter(x=>x.ticket_id===id),assignee=admins.find(x=>x.id===ticket?.assigned_to);
  const update=async(p:Partial<Ticket>&{assignedTo?:string|null})=>{if(!ticket)return;setBusy(true);try{await save({data:{id:ticket.id,status:p.status??ticket.status,priority:p.priority??ticket.priority,note:p.admin_note===undefined?ticket.admin_note:p.admin_note,assignedTo:p.assignedTo}});await refresh()}catch(e){toast.error(e instanceof Error?e.message:"Update failed.")}finally{setBusy(false)}};
  const submitEvent=async()=>{if(!ticket||!draft.trim())return;setBusy(true);try{await addEvent({data:{ticketId:ticket.id,type:draftType,body:draft.trim()}});if(draftType==="reply"){const subject=encodeURIComponent(`Re: Your PrizeSkout support request`),body=encodeURIComponent(draft.trim());location.href=`mailto:${ticket.email}?subject=${subject}&body=${body}`;}setDraft("");await refresh();toast.success(draftType==="note"?"Internal note saved.":"Reply prepared in your email app.")}catch(e){toast.error(e instanceof Error?e.message:"Could not save activity.")}finally{setBusy(false)}};
  const active=rows.filter(x=>["open","in_progress","waiting_on_customer"].includes(x.status)).length,urgent=rows.filter(x=>x.priority==="urgent"&&!["resolved","closed"].includes(x.status)).length;
  return <><Title title="Support inbox" sub="Manage Noura escalations and human-support requests from first contact through resolution." actions={<><span style={metricChip}>{active} active</span><span style={{...metricChip,color:urgent?"#B91C1C":"#166534",background:urgent?"#FEF2F2":"#F0FDF4"}}>{urgent} urgent</span><button onClick={()=>void refresh()} style={secondaryButton}><RefreshCw size={14}/>Refresh</button></>}/>{error&&<ErrorState message={error} onRetry={()=>void refresh()}/>}<div className="admin-split admin-card" style={{height:"calc(100vh - 190px)",overflow:"hidden"}}>
    <section className="admin-list-pane" style={{borderRight:"1px solid #E5E7EB",overflow:"auto"}}><div style={{padding:12,display:"grid",gap:7,position:"sticky",top:0,background:"#fff",zIndex:2}}><div style={{...input,display:"flex",gap:6}}><Search size={14}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search people or messages" style={{border:0,outline:0,width:"100%"}}/></div><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:6}}><Select value={status} onChange={setStatus} options={["active","open","in_progress","waiting_on_customer","resolved","closed","all"]}/><Select value={priority} onChange={setPriority} options={["all","urgent","high","normal","low"]}/><Select value={source} onChange={setSource} options={["all","ai_chat","contact_form"]}/></div></div>{loading&&!rows.length?[1,2,3,4].map(x=><div key={x} style={{padding:18,borderTop:"1px solid #eee"}}><Skeleton/></div>):shown.map(x=><button key={x.id} onClick={()=>setId(x.id)} style={{display:"block",width:"100%",padding:14,textAlign:"left",border:0,borderTop:"1px solid #EEF0F2",background:id===x.id?"#FFF7ED":"#fff",cursor:"pointer"}}><div style={{display:"flex",justifyContent:"space-between",gap:8}}><b style={{overflow:"hidden",textOverflow:"ellipsis"}}>{x.name}</b><small style={{color:x.priority==="urgent"?"#DC2626":"#6B7280",fontWeight:700}}>{x.source==="ai_chat"?"Noura":x.priority}</small></div><div style={{fontSize:11,color:"#6B7280",margin:"3px 0"}}>{x.email} · {age(x.created_at)}</div><div style={{fontSize:12,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{x.message}</div></button>)}{!loading&&!shown.length&&<Empty text="No tickets match these filters."/>}</section>
    <section className="admin-detail-pane" style={{padding:22,overflow:"auto"}}>{ticket?<><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><h2 style={{margin:0,fontSize:18}}>{ticket.name}</h2><a href={`mailto:${ticket.email}`} style={{fontSize:12,color:"#EA580C"}}><Mail size={11}/> {ticket.email}</a><div style={{fontSize:11,color:"#6B7280",marginTop:4}}>{ticket.source==="ai_chat"?"Noura support conversation":"Human support request"} · {assignee?.email||"Unassigned"}</div></div><Sla created={ticket.created_at} status={ticket.status}/></div>
      <div style={{padding:16,margin:"20px 0 12px",background:"#F9FAFB",borderRadius:10,whiteSpace:"pre-wrap",fontSize:13,lineHeight:1.6}}>{ticket.message}</div>
      <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:10}}><label style={label}>Status<Select value={ticket.status} onChange={v=>void update({status:v as Status})} options={["open","in_progress","waiting_on_customer","resolved","closed"]}/></label><label style={label}>Priority<Select value={ticket.priority} onChange={v=>void update({priority:v as Priority})} options={["low","normal","high","urgent"]}/></label><label style={label}>Assigned to<select disabled={busy} value={ticket.assigned_to??""} onChange={e=>void update({assignedTo:e.target.value||null})} style={input}><option value="">Unassigned</option>{admins.map(a=><option key={a.id} value={a.id}>{a.email}</option>)}</select></label></div>
      <h3 style={{fontSize:13,margin:"22px 0 8px"}}>Case activity</h3><div style={{borderLeft:"2px solid #E5E7EB",paddingLeft:13,display:"grid",gap:10}}>{timeline.map(e=><div key={e.id} style={{fontSize:12}}><b>{e.event_type==="reply"?"Email reply prepared":"Internal note"}</b><span style={{color:"#6B7280"}}> · {new Date(e.created_at).toLocaleString()}</span><div style={{marginTop:4,whiteSpace:"pre-wrap"}}>{e.body}</div></div>)}{!timeline.length&&<small style={{color:"#6B7280"}}>No activity recorded yet.</small>}</div>
      <div style={{marginTop:20,padding:14,border:"1px solid #E5E7EB",borderRadius:10}}><div style={{display:"flex",gap:7,marginBottom:9}}><button onClick={()=>setDraftType("note")} style={draftType==="note"?activeToggle:toggle}><StickyNote size={13}/>Internal note</button><button onClick={()=>setDraftType("reply")} style={draftType==="reply"?activeToggle:toggle}><Send size={13}/>Customer reply</button></div><textarea value={draft} onChange={e=>setDraft(e.target.value)} rows={4} placeholder={draftType==="note"?"Add context for other administrators…":"Write a reply, then open it in your email application…"} style={{...input,width:"100%",boxSizing:"border-box",resize:"vertical"}}/><button disabled={busy||!draft.trim()} onClick={()=>void submitEvent()} style={{...primaryButton,marginTop:8}}>{draftType==="note"?<StickyNote size={14}/>:<Send size={14}/>} {draftType==="note"?"Save note":"Prepare email reply"}</button></div>
    </>:<Empty text="Select a support conversation."/>}</section></div></>;
}
function Select({value,onChange,options}:{value:string;onChange:(v:string)=>void;options:string[]}){return <select value={value} onChange={e=>onChange(e.target.value)} style={input}>{options.map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select>}
function Sla({created,status}:{created:string;status:Status}){const hours=(Date.now()-new Date(created).getTime())/3600000,done=["resolved","closed"].includes(status),late=!done&&hours>=4;return <span style={{display:"inline-flex",alignItems:"center",gap:5,padding:"6px 9px",borderRadius:99,background:late?"#FEF2F2":"#F3F4F6",color:late?"#B91C1C":"#4B5563",fontSize:11,fontWeight:700}}><Clock3 size={13}/>{done?"Completed":late?`${Math.floor(hours)}h · SLA overdue`:`${Math.floor(hours)}h · within SLA`}</span>}
function age(date:string){const h=Math.floor((Date.now()-new Date(date).getTime())/3600000);return h<1?"less than 1h ago":h<24?`${h}h ago`:`${Math.floor(h/24)}d ago`}
const input:React.CSSProperties={border:"1px solid #DDE0E4",borderRadius:8,padding:"8px 10px",fontSize:12,background:"#fff",minWidth:0};const label:React.CSSProperties={display:"grid",gap:5,fontSize:11,fontWeight:700};const metricChip:React.CSSProperties={padding:"7px 10px",borderRadius:99,background:"#F3F4F6",fontSize:11,fontWeight:800};const toggle:React.CSSProperties={...secondaryButton,border:0,background:"transparent"};const activeToggle:React.CSSProperties={...toggle,background:"#FFF7ED",color:"#C2410C"};const primaryButton:React.CSSProperties={display:"inline-flex",alignItems:"center",gap:6,padding:"9px 12px",border:0,borderRadius:8,background:"#EA580C",color:"#fff",fontWeight:800,cursor:"pointer"};
