import { createFileRoute,Link,Outlet,useRouterState } from "@tanstack/react-router";
import { BarChart3,Users,Workflow,Headphones,ArrowLeft,LogOut,ShieldCheck } from "lucide-react";
import { useIsAdmin } from "@/hooks/useIsAdmin";
import { useAuth } from "@/lib/auth-context";
import { supabase } from "@/integrations/supabase/client";
export const Route=createFileRoute("/admin")({head:()=>({meta:[{title:"Platform Admin | PrizeSkout"}]}),component:AdminShell});
const nav=[{to:"/admin",label:"Overview",icon:BarChart3},{to:"/admin/merchants",label:"Merchants",icon:Users},{to:"/admin/operations",label:"Operations",icon:Workflow},{to:"/admin/support",label:"Support",icon:Headphones}];
function AdminShell(){const {data:admin,isLoading}=useIsAdmin(),{user}=useAuth(),path=useRouterState({select:s=>s.location.pathname});if(isLoading)return <Gate text="Checking administrator access…"/>;if(!admin)return <Gate text="This area is restricted to PrizeSkout platform administrators." denied/>;return <div style={{display:"flex",height:"100vh",background:"#F4F5F7",fontFamily:"Inter,system-ui,sans-serif",color:"#171717"}}><aside style={{width:244,background:"#111827",color:"#fff",display:"flex",flexDirection:"column"}}><div style={{padding:"24px 20px",borderBottom:"1px solid #263142"}}><b style={{fontSize:18}}>PrizeSkout</b><div style={{fontSize:10,color:"#9CA3AF",letterSpacing:1.5,marginTop:3}}>PLATFORM ADMIN</div></div><nav style={{padding:12,flex:1}}>{nav.map(({to,label,icon:Icon})=>{const active=to==="/admin"?path==="/admin"||path==="/admin/":path.startsWith(to);return <Link key={to} to={to} style={{display:"flex",alignItems:"center",gap:10,padding:"10px 12px",marginBottom:4,borderRadius:8,textDecoration:"none",fontSize:14,fontWeight:active?700:500,color:active?"#fff":"#AAB2C0",background:active?"#EA580C":"transparent"}}><Icon size={17}/>{label}</Link>})}</nav><div style={{padding:14,borderTop:"1px solid #263142"}}><Link to="/dashboard/revenue-hub" style={{display:"flex",gap:8,alignItems:"center",color:"#AAB2C0",textDecoration:"none",fontSize:12}}><ArrowLeft size={14}/>Merchant product</Link><div style={{display:"flex",alignItems:"center",gap:8,marginTop:14,fontSize:11,color:"#7F8A9B"}}><span style={{overflow:"hidden",textOverflow:"ellipsis",flex:1}}>{user?.email}</span><button aria-label="Sign out" onClick={()=>void supabase.auth.signOut().then(()=>location.assign("/"))} style={{background:0,border:0,color:"#AAB2C0",cursor:"pointer"}}><LogOut size={14}/></button></div></div></aside><main style={{flex:1,overflow:"auto"}}><header style={{height:64,display:"flex",alignItems:"center",padding:"0 28px",background:"#fff",borderBottom:"1px solid #E5E7EB"}}><ShieldCheck size={18} color="#EA580C"/><b style={{marginLeft:9}}>Revenue Protection Operations</b><span style={{marginLeft:"auto",fontSize:12,color:"#6B7280"}}>Live platform data</span></header><div style={{padding:28,maxWidth:1440,margin:"0 auto"}}><Outlet/></div></main></div>}
function Gate({text,denied=false}:{text:string;denied?:boolean}){return <div style={{height:"100vh",display:"grid",placeItems:"center",background:"#F7F7F5"}}><div style={{textAlign:"center",maxWidth:420}}><ShieldCheck size={34} color={denied?"#DC2626":"#EA580C"}/><h1 style={{fontSize:19}}>{denied?"Access denied":"PrizeSkout Admin"}</h1><p style={{fontSize:13,color:"#6B7280"}}>{text}</p>{denied&&<Link to="/dashboard/revenue-hub">Return to dashboard</Link>}</div></div>}
