import { useEffect, useRef, useState } from "react";
import logo from "@/assets/logo-light.svg";
import "./ProductStorySections.css";

type Lang="en"|"ar";
type Pair=[string,string];
const tx=(lang:Lang,p:Pair)=>p[lang==="ar"?1:0];

export function ProductStorySections({lang}:{lang:Lang}){
  return <div className="pss" dir={lang==="ar"?"rtl":"ltr"}>
    <CommerceNetwork lang={lang}/>
    <ProfitStory lang={lang}/>
    <DecisionStory lang={lang}/>
    <ProtectionStory lang={lang}/>
    <ManagerStory lang={lang}/>
    <RecoveryStory lang={lang}/>
    <PlatformMatrix lang={lang}/>
    <OperatingDay lang={lang}/>
    <TrustStrip lang={lang}/>
    <Pricing lang={lang}/>
    <Faq lang={lang}/>
    <FinalCta lang={lang}/>
  </div>
}

function Reveal({children,className=""}:{children:React.ReactNode,className?:string}){const ref=useRef<HTMLDivElement>(null);const [seen,setSeen]=useState(false);useEffect(()=>{const el=ref.current;if(!el)return;const observer=new IntersectionObserver(([entry])=>setSeen(entry.isIntersecting),{threshold:.18,rootMargin:"60px"});observer.observe(el);return()=>observer.disconnect()},[]);return <div ref={ref} className={`${className} pss-reveal ${seen?"is-seen":""}`}>{children}</div>}
function Intro({lang,kicker,title,body,center=false}:{lang:Lang,kicker:Pair,title:Pair,body:Pair,center?:boolean}){return <header className={`pss-intro ${center?"center":""}`}><span>{tx(lang,kicker)}</span><h2>{tx(lang,title)}</h2><p>{tx(lang,body)}</p></header>}

function CommerceNetwork({lang}:{lang:Lang}){return <section className="pss-network"><Intro lang={lang} center kicker={["YOUR COMMERCE, CONNECTED","تجارتك، متصلة"]} title={["One operating layer across every channel.","طبقة تشغيل واحدة عبر كل قناة."]} body={["Orders and payouts flow in. Protected decisions and approved updates flow back out.","تتدفق الطلبات والدفعات إلى الداخل، وتعود القرارات المحمية والتحديثات المعتمدة إلى الخارج."]}/><Reveal className="network-canvas"><div className="network-core"><img src={logo} alt="PrizeSkout"/><b>{tx(lang,["Control centre","مركز التحكم"])}</b><small>{tx(lang,["Monitoring continuously","مراقبة مستمرة"])}</small></div><Node cls="store" label={tx(lang,["Storefront","واجهة المتجر"])} detail={tx(lang,["Products · orders","المنتجات · الطلبات"])}/><Node cls="agg" label={tx(lang,["Aggregator","منصة التجميع"])} detail={tx(lang,["Orders · fees · prices","الطلبات · الرسوم · الأسعار"])}/><Node cls="pay" label={tx(lang,["Payouts","الدفعات"])} detail={tx(lang,["Statements · settlements","الكشوف · التسويات"])}/><Node cls="pos" label="POS" detail={tx(lang,["Coming soon","قريباً"])}/><i className="flow f1"/><i className="flow f2"/><i className="flow f3"/><i className="flow f4"/></Reveal></section>}
function Node({cls,label,detail}:{cls:string,label:string,detail:string}){return <div className={`network-node ${cls}`}><span>{label.slice(0,1)}</span><div><b>{label}</b><small>{detail}</small></div></div>}

function ProfitStory({lang}:{lang:Lang}){return <section className="pss-section"><Intro lang={lang} kicker={["UNDERSTAND","افهم"]} title={["The order said QAR 58. See what you actually kept.","قيمة الطلب 58 ر.ق. اعرف ما احتفظت به فعلياً."]} body={["PrizeSkout reconciles the complete economics of one order, then CFO Copilot explains the result in plain language.","يطابق PrizeSkout اقتصاديات الطلب كاملة، ثم يشرح المساعد المالي النتيجة بلغة بسيطة."]}/><Reveal className="story-frame profit-frame"><div className="order-source"><span>{tx(lang,["NEW ORDER","طلب جديد"])}</span><strong>QAR 58.00</strong><small>{tx(lang,["Aggregator · #10482","منصة التجميع · #10482"])}</small></div><div className="profit-ledger">{[["Order value","قيمة الطلب","QAR 58.00",""],["Commission & fees","العمولة والرسوم","− QAR 12.36","minus"],["Product cost","تكلفة المنتج","− QAR 21.00","minus"],["True profit","الربح الحقيقي","QAR 24.64","total"]].map(x=><div className={x[3]} key={x[0]}><span>{tx(lang,[x[0],x[1]])}</span><b>{x[2]}</b></div>)}</div><div className="copilot-note"><small>CFO COPILOT</small><b>{tx(lang,["Here’s what changed","إليك ما تغير"])}</b><p>{tx(lang,["Fees consumed 21.3% of the order. You kept QAR 24.64 after every known cost.","استهلكت الرسوم 21.3% من الطلب، واحتفظت بـ24.64 ر.ق بعد كل التكاليف المعروفة."])}</p></div><DemoCursor label={tx(lang,["Explain this order","اشرح هذا الطلب"])}/></Reveal></section>}

function DecisionStory({lang}:{lang:Lang}){return <section className="pss-section tint"><Intro lang={lang} kicker={["DECIDE","قرّر"]} title={["Test the market and the promotion before committing.","اختبر السوق والعرض قبل الالتزام."]} body={["Competitor context and promotion economics meet in one safe recommendation—not a race to the lowest price.","تجتمع بيانات المنافسين واقتصاديات العرض في توصية آمنة، لا في سباق نحو السعر الأقل."]}/><Reveal className="decision-grid"><div className="radar-card"><small>COMPETITOR RADAR</small><h3>{tx(lang,["Market check complete","اكتمل فحص السوق"])}</h3><div className="price-compare"><span><small>{tx(lang,["Your price","سعرك"])}</small><b>QAR 34</b></span><i>→</i><span><small>{tx(lang,["Aggregator market","سوق منصة التجميع"])}</small><b>QAR 31</b></span></div><footer>✓ {tx(lang,["Safe range: QAR 32.50–35.20","النطاق الآمن: 32.50–35.20 ر.ق"])}</footer></div><div className="sim-card"><small>PROMOTION SIMULATOR</small><h3>{tx(lang,["More orders. Less profit?","طلبات أكثر، وربح أقل؟"])}</h3><div className="discount-track"><i/><span>20%</span></div><div className="scenario danger"><span>{tx(lang,["Expected orders","الطلبات المتوقعة"])}</span><b>+25%</b><em>{tx(lang,["Profit impact −7.4%","تأثير الربح −7.4%"])}</em></div><div className="scenario safe"><span>{tx(lang,["Safer discount","الخصم الأكثر أماناً"])}</span><b>12%</b><em>{tx(lang,["Projected return +9.2%","العائد المتوقع +9.2%"])}</em></div><DemoCursor label={tx(lang,["Choose safer scenario","اختر السيناريو الآمن"])}/></div></Reveal></section>}

function ProtectionStory({lang}:{lang:Lang}){return <section className="pss-section dark"><Intro lang={lang} kicker={["PROTECT","احمِ"]} title={["Your margin policy stays in the room for every decision.","تبقى سياسة هامشك حاضرة في كل قرار."]} body={["When fees move, PrizeSkout prepares the smallest safe change and keeps you in control of publication.","عندما تتغير الرسوم، يُعد PrizeSkout أصغر تغيير آمن ويبقي النشر تحت سيطرتك."]}/><Reveal className="protection-console"><div className="policy-line"><span>{tx(lang,["PROTECTED FLOOR","الحد المحمي"])}</span><strong>18%</strong><i/></div><div className="fee-event"><small>{tx(lang,["AGGREGATOR COMMISSION","عمولة منصة التجميع"])}</small><b>25% <em>→</em> 27%</b><span>{tx(lang,["Margin would fall below policy","سينخفض الهامش عن السياسة"])}</span></div><div className="safe-change"><small>{tx(lang,["CURRENT","الحالي"])}</small><strong>QAR 49.20</strong><i>→</i><small>{tx(lang,["PROTECTED","المحمي"])}</small><strong>QAR 50.60</strong><button>{tx(lang,["Approve protected change","وافق على التغيير المحمي"])}</button></div><div className="margin-gauge"><span>14%</span><i/><b>18%</b><i/><span>24%</span></div><DemoCursor label={tx(lang,["Review & approve","راجع ووافق"])}/></Reveal></section>}

function ManagerStory({lang}:{lang:Lang}){return <section className="pss-section"><Intro lang={lang} kicker={["OPERATE","شغّل"]} title={["Delegate the work. Keep the decision.","فوّض العمل، واحتفظ بالقرار."]} body={["Store Manager turns an everyday request into checked, channel-ready work—then waits for your approval.","يحوّل مدير المتجر طلبك اليومي إلى عمل مدقق وجاهز للقنوات، ثم ينتظر موافقتك."]}/><Reveal className="manager-console"><div className="manager-prompt"><small>{tx(lang,["YOU ASKED","طلبت"])}</small><p>{tx(lang,["“Add the new Truffle Burger, improve the image, set QAR 42, add 80 units and prepare it everywhere.”","«أضف برجر الترفل الجديد، وحسّن الصورة، وحدد السعر عند 42 ر.ق، وأضف 80 وحدة وجهزه في كل مكان.»"])}</p></div><div className="manager-work">{[["Product details","تفاصيل المنتج"],["Image & description","الصورة والوصف"],["Margin policy","سياسة الهامش"],["Channel requirements","متطلبات القنوات"]].map((x,i)=><div key={x[0]} style={{animationDelay:`${i*.35}s`}}><span>✓</span><b>{tx(lang,x as Pair)}</b><small>{tx(lang,["Checked and ready","تم الفحص وهو جاهز"])}</small></div>)}</div><div className="publish-plan"><b>{tx(lang,["Approval plan","خطة الموافقة"])}</b><span>Storefront <em>{tx(lang,["Ready","جاهز"])}</em></span><span>{tx(lang,["Aggregator","منصة التجميع"])} <em>{tx(lang,["Ready","جاهز"])}</em></span><span>POS <em className="soon">{tx(lang,["Coming soon","قريباً"])}</em></span><button>{tx(lang,["Approve connected updates","وافق على التحديثات المتصلة"])}</button></div><DemoCursor label={tx(lang,["Approve plan","وافق على الخطة"])}/></Reveal></section>}

function RecoveryStory({lang}:{lang:Lang}){return <section className="pss-section tint"><Intro lang={lang} kicker={["RECOVER","استرد"]} title={["A warning becomes an evidence-backed recovery case.","يتحول التنبيه إلى حالة استرداد مدعومة بالأدلة."]} body={["PrizeSkout checks the agreement against the payout, traces affected orders and organizes the proof.","يفحص PrizeSkout الاتفاقية مقابل الدفعة، ويتتبع الطلبات المتأثرة وينظم الإثباتات."]}/><Reveal className="recovery-frame"><div className="payout-sheet"><span>{tx(lang,["PAYOUT RECEIVED","تم استلام الدفعة"])}</span><strong>QAR 39,625</strong><div><small>{tx(lang,["Contract commission","عمولة العقد"])}</small><b>19.0%</b></div><div className="flag"><small>{tx(lang,["Commission charged","العمولة المحتسبة"])}</small><b>21.4%</b></div></div><div className="evidence-flow"><h3>{tx(lang,["Building the evidence","جارٍ تجهيز الأدلة"])}</h3>{[["Agreement rate","نسبة الاتفاقية"],["184 affected orders","184 طلباً متأثراً"],["Settlement records","سجلات التسوية"],["Fee calculations","حسابات الرسوم"]].map((x,i)=><span key={x[0]} style={{animationDelay:`${i*.4}s`}}>✓ {tx(lang,x as Pair)}</span>)}<footer><small>{tx(lang,["POTENTIAL OVERCHARGE","رسوم زائدة محتملة"])}</small><b>QAR 486</b><button>{tx(lang,["Review recovery case","راجع حالة الاسترداد"])}</button></footer></div></Reveal></section>}

const caps:Array<[Pair,Pair,string]>=[[["CFO Copilot","المساعد المالي"],["Ask your numbers in everyday language.","اسأل عن أرقامك بلغة يومية."],"cfo"],[["Store Manager","مدير المتجر"],["Prepare products and operational work.","جهّز المنتجات والعمل التشغيلي."],"manager"],[["Competitor Radar","رادار المنافسين"],["Monitor market prices safely.","راقب أسعار السوق بأمان."],"radar"],[["Promotion Simulator","محاكي العروض"],["Test profit before launch.","اختبر الربح قبل الإطلاق."],"promo"],[["Payout Audit","تدقيق الدفعات"],["Match fees against agreements.","طابق الرسوم مع الاتفاقيات."],"audit"],[["Policy Centre","مركز السياسات"],["Define what automation may do.","حدد ما يمكن للأتمتة فعله."],"policy"]];
function PlatformMatrix({lang}:{lang:Lang}){return <section className="pss-section"><Intro lang={lang} center kicker={["THE COMPLETE SYSTEM","النظام المتكامل"]} title={["Not separate tools. One operating system for profit.","ليست أدوات منفصلة، بل نظام تشغيل واحد للربح."]} body={["Every capability shares the same store context, policies, evidence and approval history.","تشارك كل قدرة سياق المتجر وسياساته وأدلته وسجل الموافقات نفسه."]}/><Reveal className="platform-matrix">{caps.map(([title,body,cls],i)=><article className={cls} key={title[0]}><small>0{i+1}</small><h3>{tx(lang,title)}</h3><p>{tx(lang,body)}</p><div className="matrix-visual"><i/><i/><i/></div></article>)}</Reveal></section>}

function OperatingDay({lang}:{lang:Lang}){const events:Array<[string,Pair,Pair]>=[["08:00",["Orders reconciled","تمت مطابقة الطلبات"],["True Profit updated","تم تحديث الربح الحقيقي"]],["10:15",["Margin risk found","تم اكتشاف خطر على الهامش"],["Protected recommendation prepared","تم إعداد توصية محمية"]],["13:40",["Promotion tested","تم اختبار العرض"],["Unsafe scenario avoided","تم تجنب سيناريو غير آمن"]],["17:20",["Store work prepared","تم تجهيز أعمال المتجر"],["Waiting for approval","بانتظار الموافقة"]],["21:05",["Payout checked","تم فحص الدفعة"],["Evidence case prepared","تم تجهيز حالة الأدلة"]]];return <section className="pss-section dark day"><Intro lang={lang} center kicker={["EXAMPLE OPERATING DAY","مثال ليوم تشغيلي"]} title={["PrizeSkout keeps working after you stop watching.","يواصل PrizeSkout العمل بعد أن تتوقف عن المتابعة."]} body={["A simulated day showing how the capabilities reinforce one another. Example data—not a customer performance claim.","يوم تجريبي يوضح كيف تدعم القدرات بعضها بعضاً. بيانات توضيحية وليست ادعاءً بأداء عميل."]}/><Reveal className="day-timeline">{events.map((x,i)=><div key={x[0]} style={{animationDelay:`${i*.3}s`}}><time>{x[0]}</time><i/><b>{tx(lang,x[1])}</b><span>{tx(lang,x[2])}</span></div>)}</Reveal></section>}

function TrustStrip({lang}:{lang:Lang}){const items:Array<Pair>=[["Approval before sensitive changes","موافقة قبل التغييرات الحساسة"],["Every action recorded","يتم تسجيل كل إجراء"],["Margin policy checked","يتم فحص سياسة الهامش"],["Arabic and English","العربية والإنجليزية"],["Designed for GCC commerce","مصمم لتجارة الخليج"]];return <section className="pss-trust"><p>{tx(lang,["BUILT FOR CONTROL, NOT BLACK-BOX AUTOMATION","مصمم للتحكم، لا للأتمتة الغامضة"])}</p><div>{items.map(x=><span key={x[0]}>✓ {tx(lang,x)}</span>)}</div></section>}

function Pricing({lang}:{lang:Lang}){return <section className="pss-section pss-pricing" id="pricing"><Intro lang={lang} center kicker={["CHOOSE YOUR OPERATING LEVEL","اختر مستوى التشغيل"]} title={["Start with visibility. Scale into protection.","ابدأ بالوضوح، وتوسع نحو الحماية."]} body={["The prices stay simple. The difference is how far PrizeSkout operates across your business.","الأسعار واضحة، والفرق هو مدى تشغيل PrizeSkout عبر أعمالك."]}/><div className="pss-price-grid"><Price lang={lang} name="Core" price="QAR 349" subtitle={["Understand and manage","افهم وأدر"]} features={[["Full CFO Copilot","المساعد المالي الكامل"],["AI Store Manager","مدير المتجر بالذكاء الاصطناعي"],["True Profit and payout visibility","الربح الحقيقي ووضوح الدفعات"],["Margin policies and protected actions","سياسات الهامش والإجراءات المحمية"],["Competitor Radar and promotion simulation","رادار المنافسين ومحاكاة العروض"]]}/><Price lang={lang} popular name="Growth" price="QAR 1,099" subtitle={["Protect and recover","احمِ واسترد"]} features={[["Everything in Core","كل ما في Core"],["Protected repricing automation","أتمتة إعادة التسعير المحمية"],["Commission and payout audits","تدقيق العمولات والدفعات"],["Recovery evidence workflows","سير عمل أدلة الاسترداد"],["More connected channels and automation","قنوات وأتمتة أكثر"]]}/><Price lang={lang} name="Enterprise" price={tx(lang,["Custom","مخصص"])} subtitle={["Operate at scale","شغّل على نطاق واسع"]} features={[["Everything in Growth","كل ما في Growth"],["Multiple locations and teams","مواقع وفرق متعددة"],["Custom policies and governance","سياسات وحوكمة مخصصة"],["Enterprise integrations and APIs","تكاملات وواجهات مؤسسية"],["Dedicated service levels","مستويات خدمة مخصصة"]]}/></div></section>}
function Price({lang,name,price,subtitle,features,popular=false}:{lang:Lang,name:string,price:string,subtitle:Pair,features:Pair[],popular?:boolean}){return <article className={`pss-price ${popular?"popular":""}`}>{popular&&<em>{tx(lang,["MOST POPULAR","الأكثر شيوعاً"])}</em>}<small>{tx(lang,subtitle)}</small><h3>{name}</h3><strong>{price}</strong>{price.startsWith("QAR")&&<span>/ {tx(lang,["month","شهر"])}</span>}<ul>{features.map(x=><li key={x[0]}>✓ {tx(lang,x)}</li>)}</ul><a href="/onboarding">{popular?tx(lang,["Choose Growth","اختر Growth"]):tx(lang,["Get started","ابدأ الآن"])}</a></article>}

function Faq({lang}:{lang:Lang}){const qs:Array<[Pair,Pair]>=[[["What does PrizeSkout connect to?","بماذا يتصل PrizeSkout؟"],["Connected storefronts and aggregators can provide catalogue, order, fee and payout information depending on their supported integration.","يمكن لواجهات المتاجر ومنصات التجميع المتصلة توفير بيانات المنتجات والطلبات والرسوم والدفعات حسب التكامل المدعوم."]],[["Does PrizeSkout change prices without approval?","هل يغير PrizeSkout الأسعار دون موافقة؟"],["You control the policy and approval mode. Sensitive changes can remain supervised until you explicitly approve them.","أنت تتحكم في السياسة ووضع الموافقة، ويمكن أن تبقى التغييرات الحساسة تحت الإشراف حتى توافق عليها صراحةً."]],[["Is recovered money guaranteed?","هل استرداد الأموال مضمون؟"],["No. PrizeSkout identifies potential discrepancies and organizes evidence. Final recovery depends on the agreement and the receiving platform’s process.","لا. يحدد PrizeSkout الفروقات المحتملة وينظم الأدلة، ويعتمد الاسترداد النهائي على الاتفاقية وإجراءات المنصة المستلمة."]],[["What is coming soon?","ما الذي سيأتي قريباً؟"],["Additional POS and channel integrations will be labelled clearly until they are genuinely available.","سيتم تمييز تكاملات نقاط البيع والقنوات الإضافية بوضوح حتى تصبح متاحة فعلياً."]]];return <section className="pss-section pss-faq"><Intro lang={lang} kicker={["QUESTIONS, ANSWERED","إجابات على أسئلتك"]} title={["Know exactly what PrizeSkout does.","اعرف بالضبط ما يفعله PrizeSkout."]} body={["Clear answers, without inflated promises.","إجابات واضحة دون وعود مبالغ فيها."]}/><div>{qs.map((q,i)=><details key={q[0][0]} open={i===0}><summary>{tx(lang,q[0])}<span>+</span></summary><p>{tx(lang,q[1])}</p></details>)}</div></section>}

function FinalCta({lang}:{lang:Lang}){return <section className="pss-final"><div className="final-status"><span>✓ {tx(lang,["Connected","متصل"])}</span><span>✓ {tx(lang,["Margin protected","الهامش محمي"])}</span><span>✓ {tx(lang,["Work prepared","العمل جاهز"])}</span><span>✓ {tx(lang,["Payout monitored","الدفعة تحت المراقبة"])}</span></div><img src={logo} alt="PrizeSkout"/><h2>{tx(lang,["Put every connected order under active profit protection.","ضع كل طلب متصل تحت حماية نشطة للربح."])}</h2><p>{tx(lang,["Connect your commerce stack and let PrizeSkout organize the next decision.","اربط منظومة تجارتك ودع PrizeSkout ينظم القرار التالي."])}</p><div><a href="/onboarding">{tx(lang,["Connect your store","اربط متجرك"])}</a><a href="/contact">{tx(lang,["Book a guided demo","احجز عرضاً توضيحياً"])}</a></div></section>}
function DemoCursor({label}:{label:string}){return <div className="pss-cursor" aria-hidden="true"><svg viewBox="0 0 30 38"><path d="M3 2.5 26 24l-10.3 1.5L10.5 35 3 2.5Z"/></svg><span>{label}</span><i/></div>}
