import { jsPDF } from "jspdf";
import {
  BORDER,
  BLUE,
  CONTENT_W,
  FAINT,
  GREEN,
  INK,
  MARGIN_X,
  MUTED,
  RED,
  type RGB,
  drawBrandedFooters,
  drawBrandedHeader,
  drawLabel,
  ensureSpace,
  resolveBrandTheme,
  slugifyBrand,
  tint,
} from "@/lib/pdfBranding";

export type PricingRecommendation = {
  id: string;
  product: string;
  category: string;
  channel: "Online" | "In-Store";
  current: number;
  recommended: number;
  reason: string;
  unitImpact: string;
  marginImpact: string;
  netMonthly: string;
  confidence: number;
};

const CURRENCY = "QAR";

function fmtPrice(n: number) {
  return `${CURRENCY} ${n.toLocaleString("en-US", {
    minimumFractionDigits: n % 1 ? 2 : 0,
    maximumFractionDigits: 2,
  })}`;
}

function impactColor(value: string): RGB {
  if (value.startsWith("+")) return GREEN;
  if (value.startsWith("-")) return RED;
  return MUTED;
}

function confidenceColor(score: number, accent: RGB): RGB {
  if (score > 90) return GREEN;
  if (score >= 80) return accent;
  return [245, 158, 11];
}

export async function exportPricingPdf(recs: PricingRecommendation[]) {
  const theme = resolveBrandTheme();
  const { branding, accent, accentTint } = theme;
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const today = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  let y = await drawBrandedHeader(
    doc,
    theme,
    "AI Pricing Recommendations",
    `Pricing report  |  ${today}`,
  );

  // Intro
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(...INK);
  doc.text("Recommendations to act on this week", MARGIN_X, y);
  y += 6;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...MUTED);
  const intro =
    "These price changes were generated by your model using current competitor positions, your sales velocity, elasticity signals, and stock availability. Each recommendation includes the projected unit and margin impact so you can prioritize.";
  const introLines = doc.splitTextToSize(intro, CONTENT_W);
  doc.text(introLines, MARGIN_X, y);
  y += introLines.length * 4.6 + 4;

  // Summary strip
  drawPricingSummary(doc, y, recs, accent, accentTint);
  y += 24;

  for (let i = 0; i < recs.length; i++) {
    y = drawRecommendationCard(doc, recs[i], i + 1, y, accent, accentTint);
    y += 6;
  }

  drawBrandedFooters(doc, theme);
  doc.save(`${slugifyBrand(branding.brandName)}-pricing-recommendations.pdf`);
}

function drawPricingSummary(
  doc: jsPDF,
  y: number,
  recs: PricingRecommendation[],
  accent: RGB,
  accentTint: RGB,
) {
  // Sum the QAR figures from netMonthly strings like "+QAR 18K" or "+QAR 6K"
  let totalK = 0;
  for (const r of recs) {
    const m = /([+-]?)\s*QAR\s*([\d,.]+)\s*K?/i.exec(r.netMonthly);
    if (!m) continue;
    const sign = m[1] === "-" ? -1 : 1;
    const value = parseFloat(m[2].replace(/,/g, "")) || 0;
    totalK += sign * value;
  }
  const formattedTotal =
    (totalK >= 0 ? "+" : "-") +
    `QAR ${Math.abs(totalK).toLocaleString("en-US", { maximumFractionDigits: 0 })}K`;

  const avgConf = Math.round(
    recs.reduce((s, r) => s + r.confidence, 0) / Math.max(1, recs.length),
  );

  const blocks: { label: string; value: string; color: RGB; bg: RGB }[] = [
    {
      label: "Net monthly impact",
      value: formattedTotal,
      color: GREEN,
      bg: [240, 253, 244],
    },
    {
      label: "Recommendations",
      value: String(recs.length),
      color: accent,
      bg: accentTint,
    },
    {
      label: "Avg model confidence",
      value: `${avgConf}%`,
      color: BLUE,
      bg: [239, 246, 255],
    },
  ];
  const gap = 4;
  const w = (CONTENT_W - gap * (blocks.length - 1)) / blocks.length;
  blocks.forEach((b, i) => {
    const x = MARGIN_X + i * (w + gap);
    doc.setFillColor(b.bg[0], b.bg[1], b.bg[2]);
    doc.roundedRect(x, y, w, 20, 2, 2, "F");
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...FAINT);
    doc.text(b.label.toUpperCase(), x + 5, y + 6);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(b.color[0], b.color[1], b.color[2]);
    doc.text(b.value, x + 5, y + 15);
  });
}

function estimateRecHeight(
  doc: jsPDF,
  r: PricingRecommendation,
  innerW: number,
): number {
  let h = 8; // top padding
  h += 5; // title
  h += 6; // tag row
  h += 5;
  // Reason
  const reasonLines = doc.splitTextToSize(r.reason, innerW);
  h += reasonLines.length * 4.6 + 6;
  // Price + impact strip
  h += 24;
  h += 8; // bottom padding
  return h;
}

function drawRecommendationCard(
  doc: jsPDF,
  r: PricingRecommendation,
  index: number,
  startY: number,
  accent: RGB,
  accentTint: RGB,
): number {
  const innerW = CONTENT_W - 12;
  const cardH = estimateRecHeight(doc, r, innerW);
  let y = ensureSpace(doc, startY, cardH);

  const cardTop = y;
  const cardX = MARGIN_X;
  const cardW = CONTENT_W;
  const innerX = cardX + 6;
  y += 8;

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12.5);
  doc.setTextColor(...INK);
  doc.text(`${index}. ${r.product}`, innerX, y);

  // Confidence badge (right)
  const conf = r.confidence;
  const cColor = confidenceColor(conf, accent);
  const badgeW = 28;
  const badgeX = cardX + cardW - 6 - badgeW;
  doc.setFillColor(cColor[0], cColor[1], cColor[2]);
  doc.roundedRect(badgeX, y - 5, badgeW, 7, 1.5, 1.5, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(255, 255, 255);
  doc.text(`${conf}% confidence`, badgeX + badgeW / 2, y, { align: "center" });

  y += 5;

  // Meta line
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...MUTED);
  doc.text(`${r.category}  |  ${r.channel}`, innerX, y);
  y += 6;

  // Reason
  y = drawLabel(doc, "RATIONALE", innerX, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  doc.setTextColor(...INK);
  const reasonLines = doc.splitTextToSize(r.reason, innerW);
  doc.text(reasonLines, innerX, y);
  y += reasonLines.length * 4.6 + 4;

  // Price + impact strip
  const stripTop = y;
  const stripH = 22;
  doc.setFillColor(...tint(accent, 0.96));
  doc.roundedRect(innerX, stripTop, innerW, stripH, 2, 2, "F");

  // Current → Recommended
  let cx = innerX + 5;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.5);
  doc.setTextColor(...FAINT);
  doc.text("CURRENT", cx, stripTop + 6);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(...MUTED);
  doc.text(fmtPrice(r.current), cx, stripTop + 14);

  cx += 36;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...MUTED);
  doc.text(">", cx, stripTop + 14);

  cx += 6;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.5);
  doc.setTextColor(...FAINT);
  doc.text("RECOMMENDED", cx, stripTop + 6);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(...GREEN);
  doc.text(fmtPrice(r.recommended), cx, stripTop + 14);

  // Right side: unit, margin, net monthly
  const metrics: { label: string; value: string; color: RGB }[] = [
    { label: "UNIT", value: `${r.unitImpact} units`, color: impactColor(r.unitImpact) },
    { label: "MARGIN", value: r.marginImpact, color: impactColor(r.marginImpact) },
    { label: "NET MONTHLY", value: r.netMonthly, color: GREEN },
  ];
  const rightStart = innerX + innerW - 5 - metrics.length * 36 + 36;
  metrics.forEach((m, i) => {
    const x = rightStart + i * 36 - 36;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7.5);
    doc.setTextColor(...FAINT);
    doc.text(m.label, x, stripTop + 6);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(m.color[0], m.color[1], m.color[2]);
    doc.text(m.value, x, stripTop + 14);
  });

  y = stripTop + stripH + 4;

  // Card border
  doc.setDrawColor(...BORDER);
  doc.setLineWidth(0.3);
  doc.roundedRect(cardX, cardTop, cardW, y - cardTop - 2, 2.5, 2.5, "S");

  return y;
}
