import { useEffect, useState } from "react";
import { CheckCircle2, Save, ShieldAlert } from "lucide-react";
import type { ZidJahezBridgeSettings as Settings } from "@/server/core/zid-jahez-bridge";

const field={border:"1px solid var(--border)",borderRadius:7,padding:"7px 8px",background:"var(--surface)",color:"var(--text)",fontFamily:"inherit"};

export function ZidJahezBridgeSettings({availableSkus,onSettings}:{availableSkus:string[];onSettings?:(settings:Settings|null)=>void}){
  const [settings,setSettings]=useState<Settings|null>(null);
  const [mazeed,setMazeed]=useState(false);const [jahez,setJahez]=useState(false);
  const [commission,setCommission]=useState("");const [vatMode,setVatMode]=useState<Settings["vat_mode"]>("store_includes_vat");
  const [skus,setSkus]=useState("");const [confirmedBy,setConfirmedBy]=useState("");
  const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);
  const [events,setEvents]=useState<Array<{id:string;sku:string;expected_price:number;status:string;created_at:string}>>([]);
  const [observed,setObserved]=useState<Record<string,string>>({});const [verifiedBy,setVerifiedBy]=useState("");
  const call=async(payload:Record<string,unknown>)=>{const response=await fetch("/api/channels/connect",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({merchant_id:localStorage.getItem("ps_merchant_id")??"",access_code:localStorage.getItem("ps_access_code")??"",platform:"zid_jahez_bridge",...payload})});const data=await response.json();if(!response.ok||!data.ok)throw new Error(data.error??"Could not load Zid–Jahez settings.");return data;};
  const apply=(value:Settings|null)=>{setSettings(value);onSettings?.(value);if(!value)return;setMazeed(value.mazeed_active);setJahez(value.jahez_active);setCommission(value.mazeed_commission_pct==null?"":String(value.mazeed_commission_pct));setVatMode(value.vat_mode);setSkus(value.eligible_skus.join(", "));setConfirmedBy(value.confirmed_by??"");};
  useEffect(()=>{call({action:"get"}).then(data=>{apply(data.settings??null);setEvents(data.events??[]);}).catch(reason=>setError(reason instanceof Error?reason.message:"Could not load Zid–Jahez settings."));},[]);
  const save=async()=>{setBusy(true);setError(null);try{const eligible=skus.split(/[\s,]+/).map(value=>value.trim()).filter(Boolean);const data=await call({action:"save",mazeed_active:mazeed,jahez_active:jahez,mazeed_commission_pct:commission===""?null:Number(commission),vat_mode:vatMode,eligible_skus:eligible,confirmed_by:confirmedBy});apply(data.settings);}catch(reason){setError(reason instanceof Error?reason.message:"Could not save settings.");}finally{setBusy(false);}};
  const useCatalogue=()=>setSkus(availableSkus.slice(0,100).join(", "));
  const confirm=async(id:string)=>{const price=Number(observed[id]);if(!(price>0)||!verifiedBy.trim()){setError("Enter the Jahez price you observed and who checked it.");return;}setBusy(true);setError(null);try{await call({action:"confirm_propagation",id,observed_price:price,verified_by:verifiedBy});const data=await call({action:"get"});setEvents(data.events??[]);}catch(reason){setError(reason instanceof Error?reason.message:"Could not verify propagation.");}finally{setBusy(false);}};
  return <section style={{border:"1px solid var(--border)",borderRadius:10,padding:12,background:"var(--surface2)"}}>
    <div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"start",flexWrap:"wrap"}}><div><strong style={{fontSize:13}}>Zid → Mazeed → Jahez bridge</strong><div style={{fontSize:10.5,color:"var(--muted)",marginTop:3}}>Tell PrizeSkout which Zid products are enrolled. A confirmed Zid change will then be tracked as waiting for Jahez—not falsely reported as live there.</div></div>{settings?.jahez_active?<span style={{fontSize:10.5,color:"#087F5B",fontWeight:900,display:"flex",gap:5}}><CheckCircle2 size={13}/>Bridge tracking active</span>:<span style={{fontSize:10.5,color:"#A16207",fontWeight:900,display:"flex",gap:5}}><ShieldAlert size={13}/>Not configured</span>}</div>
    <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(175px,1fr))",gap:9,marginTop:11}}>
      <label style={{fontSize:11,fontWeight:800,display:"flex",gap:7,alignItems:"center"}}><input type="checkbox" checked={mazeed} onChange={event=>{setMazeed(event.target.checked);if(!event.target.checked)setJahez(false);}}/>Mazeed is active in Zid</label>
      <label style={{fontSize:11,fontWeight:800,display:"flex",gap:7,alignItems:"center"}}><input type="checkbox" checked={jahez} disabled={!mazeed} onChange={event=>setJahez(event.target.checked)}/>Jahez channel is active</label>
      <label style={{fontSize:10.5,fontWeight:800}}>Mazeed commission %<input type="number" min="0" max="100" value={commission} onChange={event=>setCommission(event.target.value)} style={{...field,width:"100%",boxSizing:"border-box",display:"block",marginTop:4}} placeholder="From agreement"/></label>
      <label style={{fontSize:10.5,fontWeight:800}}>VAT treatment<select value={vatMode} onChange={event=>setVatMode(event.target.value as Settings["vat_mode"])} style={{...field,width:"100%",display:"block",marginTop:4}}><option value="store_includes_vat">Store price includes VAT</option><option value="mazeed_adds_vat">Mazeed adds VAT</option></select></label>
      <label style={{fontSize:10.5,fontWeight:800}}>Confirmed by<input value={confirmedBy} onChange={event=>setConfirmedBy(event.target.value)} style={{...field,width:"100%",boxSizing:"border-box",display:"block",marginTop:4}} placeholder="Merchant or reviewer"/></label>
    </div>
    <label style={{display:"block",fontSize:10.5,fontWeight:800,marginTop:9}}>Jahez-enrolled SKUs<textarea value={skus} onChange={event=>setSkus(event.target.value)} rows={2} style={{...field,width:"100%",boxSizing:"border-box",display:"block",marginTop:4}} placeholder="SKU-1, SKU-2"/></label>
    <div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap",marginTop:8}}><button type="button" onClick={useCatalogue} style={{border:"1px solid var(--border)",borderRadius:7,padding:"7px 9px",background:"var(--surface)",color:"var(--text)",fontFamily:"inherit",fontSize:10.5,fontWeight:800}}>Use first 100 Zid SKUs</button><button type="button" disabled={busy} onClick={save} style={{border:0,borderRadius:7,padding:"8px 10px",background:"#14213D",color:"#fff",fontFamily:"inherit",fontWeight:800,display:"flex",gap:5}}><Save size={13}/>{busy?"Saving…":"Save bridge settings"}</button>{error&&<span style={{fontSize:10.5,color:"#B42318"}}>{error}</span>}</div>
    {!!events.length&&<div style={{borderTop:"1px solid var(--border)",marginTop:10,paddingTop:9}}><div style={{display:"flex",justifyContent:"space-between",gap:8,alignItems:"center",flexWrap:"wrap"}}><div style={{fontSize:10.5,fontWeight:900}}>Recent propagation checks</div><input value={verifiedBy} onChange={event=>setVerifiedBy(event.target.value)} placeholder="Fallback verifier" style={{...field,fontSize:10,width:150}}/></div><div style={{display:"flex",flexDirection:"column",gap:6,marginTop:6}}>{events.slice(0,8).map(item=><div key={item.id} style={{display:"flex",gap:6,alignItems:"center",flexWrap:"wrap",fontSize:10,color:item.status==="confirmed"?"#087F5B":"#A16207",fontWeight:800}}><span>{item.sku} · expected SAR {Number(item.expected_price).toFixed(2)} · {item.status==="pending"?"waiting for Jahez":item.status}</span>{item.status==="pending"&&<><input type="number" value={observed[item.id]??""} onChange={event=>setObserved({...observed,[item.id]:event.target.value})} placeholder="Observed price" style={{...field,fontSize:10,width:105,padding:"4px 6px"}}/><button disabled={busy} onClick={()=>confirm(item.id)} style={{border:"1px solid var(--border)",borderRadius:6,padding:"5px 7px",background:"var(--surface)",color:"var(--text)",fontFamily:"inherit",fontSize:10,fontWeight:800}}>Verify fallback</button></>}</div>)}</div></div>}
  </section>;
}
