import { saveWordReport } from "@/lib/wordReport";
import type { CommissionAuditPdfData, CommissionAuditPdfOptions } from "./exportAuditReportPdf";
import type { PayoutCheckPdfData, RepricingPdfData } from "./exportPayoutReportPdf";

const money=(value:number,currency:string)=>`${currency} ${value.toLocaleString("en-US",{maximumFractionDigits:2})}`;
const dateSuffix=()=>new Date().toISOString().slice(0,10);

export async function exportPayoutCheckWord(data:PayoutCheckPdfData,currency:string){
  const expectedAtAgreed=data.commission_rate_pct!=null&&data.commission_amount!=null?data.expected_payout+(data.commission_amount-data.sub_total_sum*data.commission_rate_pct/100):data.expected_payout;
  await saveWordReport({title:"Expected Payout Check",subtitle:`${data.platform??"Platform"} | ${data.period_start??"Period not supplied"}${data.period_end?` to ${data.period_end}`:""}`,fileName:`payout-check-${dateSuffix()}.docx`,summary:[{label:"Orders checked",value:String(data.order_count)},{label:"Eligible sales",value:money(data.sub_total_sum,currency)},{label:"Agreed commission",value:data.commission_rate_pct==null?"Not supplied":`${data.commission_rate_pct}%`},{label:"Expected payout at agreed rate",value:money(expectedAtAgreed,currency)}],sections:[{title:"Payout bridge",table:{headers:["Component","Amount"],rows:[["Eligible sales",money(data.sub_total_sum,currency)],["Contractual commission",data.commission_rate_pct==null?"Not established":money(data.sub_total_sum*data.commission_rate_pct/100,currency)],["Additional charges",money(data.additional_charges??0,currency)],["Additional income and vouchers",money(data.additional_income??0,currency)],["Platform-reported or calculated payout",money(data.expected_payout,currency)]]}},{title:"Exceptions and evidence",bullets:[data.unexplained_charge?`Unexplained charge: ${data.unexplained_charge.label} | ${money(data.unexplained_charge.amount,currency)}`:"No unexplained charge was identified in the supplied data.",data.source==="upload"?"Result is based on an uploaded platform document.":"Result is calculated from connected order history; add settlement and bank evidence to confirm actual receipt."]}],limitations:["This is a per-period payout calculation, not an assurance opinion.","A bank receipt is required to confirm the amount actually received.","Merchant-supplied contract terms are not independently verified unless explicitly marked reviewed."]});
}

export async function exportPayoutHistoryWord(checks:PayoutCheckPdfData[],repricings:RepricingPdfData[],currency:string){
  await saveWordReport({title:"Activity & Evidence Report",subtitle:"Payout checks and channel price activity",fileName:`activity-evidence-${dateSuffix()}.docx`,summary:[{label:"Payout checks",value:String(checks.length)},{label:"Price changes",value:String(repricings.length)},{label:"Failed price actions",value:String(repricings.filter(row=>!["success","confirmed"].includes(row.status)).length)}],sections:[{title:"Payout checks",table:{headers:["Date","Platform","Orders","Agreed rate","Expected payout"],rows:checks.map(row=>[row.created_at?new Date(row.created_at).toLocaleString():"Not available",row.platform??"Not available",row.order_count,row.commission_rate_pct==null?"Not available":`${row.commission_rate_pct}%`,money(row.expected_payout,currency)])}},{title:"Price changes",table:{headers:["Date","Channel","SKU","Old price","New price","Status"],rows:repricings.map(row=>[new Date(row.created_at).toLocaleString(),row.target_channel??"Not available",row.sku??"Not available",row.old_price==null?"Not available":money(row.old_price,row.currency),money(row.new_price,row.currency),row.status.replaceAll("_"," ")])},note:"Each price event remains in its original transaction currency."}],limitations:["A successful upstream response does not by itself prove the price was confirmed live unless the event status explicitly says confirmed.","Historical currencies are not converted."]});
}

export async function exportCommissionAuditWord(data:CommissionAuditPdfData,currency:string,documentCount:number,options:CommissionAuditPdfOptions={}){
  const totals=data.ledgerTotals;
  const assurance=data.assurance;
  await saveWordReport({title:"Payout Investigation Report",subtitle:data.coverage?`${data.coverage.start} to ${data.coverage.end}`:"Open period",fileName:`payout-investigation-${dateSuffix()}.docx`,summary:[{label:"Evidence documents",value:String(documentCount)},{label:"Orders",value:String(totals?.orders??0)},{label:"Eligible sales",value:money(totals?.sales??0,currency)},{label:"Findings",value:String(data.findings.length)},{label:"Critical findings",value:String(data.findings.filter(f=>f.severity==="critical").length)}],sections:[{title:"Independent conclusion",paragraphs:[assurance?.opinionLabel??"No retained assurance conclusion is available for this investigation.",assurance?`Evidence score: ${assurance.evidenceScore}% | Claims-ready amount: ${money(assurance.claimsReadyAmount,currency)} | Estimated exposure: ${money(assurance.estimatedExposure,currency)}`:""].filter(Boolean),bullets:assurance?.limitations,note:`Review status: ${options.reviewStatus??"Draft - merchant review required"}`},{title:"Findings",table:{headers:["Severity","Finding","Detail"],rows:data.findings.map(f=>[f.severity.toUpperCase(),f.title,f.detail])}},{title:"Transaction ledger",table:{headers:["Date","Orders","Eligible sales","Contractual commission","Expected net"],rows:data.ledger.map(row=>[row.date,row.orders,money(row.sales,currency),money(row.commission_at_agreed_rate,currency),money(row.expected_net,currency)])}},{title:"Evidence register",table:{headers:["File","Document type","Evidence level"],rows:(options.documents??[]).map(doc=>[doc.file_name,doc.document_type,doc.result.evidence_level??"not classified"])}}],limitations:["This report distinguishes merchant assertions, single-source calculations, and corroborated evidence.","Estimates are not presented as claims-ready recoveries.","No bank-file content review is implied unless bank evidence is included and explicitly classified.","Contract terms are merchant supplied unless a reviewed contract is identified in the report."]});
}
