import {useEffect,useMemo,useState} from "react";
import {CheckCircle2,Download,FileSpreadsheet,LockKeyhole,Save} from "lucide-react";
import type {ClassifiedDocument,LedgerRow} from "@/lib/commission-audit";
import {buildMonthEndClose} from "@/lib/month-end-close";
import type {SavedMonthEndClose} from "@/server/core/month-end-close";

const input={border:"1px solid var(--border)",borderRadius:7,padding:"8px 9px",background:"var(--surface)",color:"var(--text)",fontFamily:"inherit"};
const money=(v:number,c:string)=>`${c} ${Math.abs(v).toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const csvCell=(v:unknown)=>`"${String(v??"").replaceAll('"','""')}"`;
function downloadCsv(name:string,headers:string[],rows:unknown[][]){const csv=[headers,...rows].map(row=>row.map(csvCell).join(",")).join("\r\n");const url=URL.createObjectURL(new Blob([`\uFEFF${csv}`],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}

export function MonthEndCloseWorkspace({totals,documents,currency,coverage}:{totals:LedgerRow|null;documents:ClassifiedDocument[];currency:string;coverage:{start:string;end:string}|null}){
  const close=useMemo(()=>buildMonthEndClose(totals,documents),[totals,documents]);
  const [system,setSystem]=useState("Generic CSV");
  const [preparedBy,setPreparedBy]=useState("PrizeSkout close engine");
  const [reviewer,setReviewer]=useState("");
  const [saved,setSaved]=useState<SavedMonthEndClose[]>([]);
  const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);
  const call=async(payload:Record<string,unknown>)=>{const response=await fetch("/api/channels/connect",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({merchant_id:localStorage.getItem("ps_merchant_id")??"",access_code:localStorage.getItem("ps_access_code")??"",platform:"month_end_close",...payload})});const data=await response.json();if(!response.ok||!data.ok)throw new Error(data.error??"Close request failed.");return data;};
  const load=()=>call({action:"list"}).then(data=>setSaved(data.closes??[])).catch(err=>setError(err instanceof Error?err.message:"Could not load close history."));
  useEffect(()=>{load();},[]);
  const save=async()=>{setBusy(true);setError(null);try{await call({action:"save",period_start:coverage?.start??"",period_end:coverage?.end??"",currency,schedules:close.schedules,journals:close.journals,limitations:close.limitations,prepared_by:preparedBy});await load();}catch(err){setError(err instanceof Error?err.message:"Could not save close.");}finally{setBusy(false);}};
  const advance=async(item:SavedMonthEndClose,status:"reviewed"|"approved"|"locked")=>{if(!reviewer.trim()){setError("Enter the finance reviewer’s name.");return;}setBusy(true);try{await call({action:"advance",id:item.id,close_status:status,reviewer});await load();}catch(err){setError(err instanceof Error?err.message:"Could not advance close.");}finally{setBusy(false);}};
  const mapping:Record<string,Record<string,string>>={
    "Generic CSV":{},"Xero":{"Marketplace receivable":"1200","Marketplace sales revenue":"2000","Platform commission expense":"4100"},
    "QuickBooks":{"Marketplace receivable":"Accounts Receivable","Marketplace sales revenue":"Sales of Product Income","Platform commission expense":"Commissions and fees"},
    "Zoho Books":{"Marketplace receivable":"Accounts Receivable","Marketplace sales revenue":"Sales","Platform commission expense":"Platform Fees"},
    "Oracle NetSuite":{"Marketplace receivable":"1100","Marketplace sales revenue":"4000","Platform commission expense":"6100"},
    "SAP":{"Marketplace receivable":"140000","Marketplace sales revenue":"400000","Platform commission expense":"630000"},
  };
  const exportSchedules=()=>downloadCsv(`prizeskout-close-schedules-${coverage?.end??"period"}.csv`,["Code","Schedule","Amount","Currency","Evidence","Status"],close.schedules.map(s=>[s.code,s.label,s.amount,currency,s.evidence,s.status]));
  const exportJournal=()=>downloadCsv(`prizeskout-proposed-journal-${coverage?.end??"period"}.csv`,["Journal","External account code","Account","Description","Debit","Credit","Currency","Source","Posting status"],close.journals.map(j=>[j.journal,mapping[system]?.[j.account]??"",j.account,j.description,j.debit,j.credit,currency,j.source,"PROPOSED — NOT POSTED"]));
  return <section style={{border:"1px solid var(--border)",borderRadius:12,overflow:"hidden"}}>
    <div style={{padding:"16px 18px",background:"var(--surface2)",display:"flex",justifyContent:"space-between",gap:10,alignItems:"center",flexWrap:"wrap"}}><div><div style={{fontSize:17,fontWeight:900}}>Accountant-Ready Month-End Close</div><div style={{fontSize:11.5,color:"var(--muted)",marginTop:3}}>Close schedules and balanced journal proposals with evidence status. Nothing is posted automatically.</div></div><span style={{fontSize:10.5,fontWeight:900,color:close.balanced?"#087F5B":"#B42318"}}>{close.balanced?"JOURNALS BALANCED":"JOURNALS OUT OF BALANCE"}</span></div>
    <div style={{padding:18,display:"flex",flexDirection:"column",gap:15}}>
      <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(170px,1fr))",gap:9}}>{[["Period",coverage?`${coverage.start} → ${coverage.end}`:"Not established"],["Expected receivable",money(close.expected_receivable,currency)],["Settlement received",close.cash_received==null?"Not evidenced":money(close.cash_received,currency)],["Cash in transit",money(close.cash_in_transit??0,currency)],["Unresolved variance",close.unresolved_variance==null?"Not testable":money(close.unresolved_variance,currency)]].map(([k,v])=><div key={k} style={{border:"1px solid var(--border)",borderRadius:9,padding:"10px 11px"}}><div style={{fontSize:9.5,color:"var(--muted)",fontWeight:800,textTransform:"uppercase"}}>{k}</div><div style={{fontSize:15,fontWeight:900,marginTop:4}}>{v}</div></div>)}</div>
      <div className="table-scroll"><table style={{width:"100%",borderCollapse:"collapse",minWidth:800,fontSize:11.5}}><thead><tr>{["Account schedule","Amount","Evidence basis","Close status"].map(v=><th key={v} style={{padding:9,textAlign:"start",color:"var(--muted)",borderBottom:"1px solid var(--border)"}}>{v}</th>)}</tr></thead><tbody>{close.schedules.map(s=><tr key={s.code}><td style={{padding:9,borderBottom:"1px solid var(--border)",fontWeight:900}}>{s.label}</td><td style={{padding:9,borderBottom:"1px solid var(--border)",textAlign:"end"}}>{money(s.amount,currency)}</td><td style={{padding:9,borderBottom:"1px solid var(--border)",color:"var(--muted)"}}>{s.evidence}</td><td style={{padding:9,borderBottom:"1px solid var(--border)",fontWeight:900,color:s.status==="supported"?"#087F5B":s.status==="missing"?"#B42318":"#A16207"}}>{s.status.toUpperCase()}</td></tr>)}</tbody></table></div>
      <div><strong style={{fontSize:13}}>Proposed journal entries</strong><div className="table-scroll" style={{marginTop:8}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:900,fontSize:11.5}}><thead><tr>{["Journal","Account","Description","Debit","Credit","Source"].map(v=><th key={v} style={{padding:9,textAlign:"start",color:"var(--muted)",borderBottom:"1px solid var(--border)"}}>{v}</th>)}</tr></thead><tbody>{close.journals.map((j,i)=><tr key={`${j.journal}-${i}`}><td style={{padding:9,borderBottom:"1px solid var(--border)",fontWeight:800}}>{j.journal}</td><td style={{padding:9,borderBottom:"1px solid var(--border)"}}>{j.account}</td><td style={{padding:9,borderBottom:"1px solid var(--border)"}}>{j.description}</td><td style={{padding:9,borderBottom:"1px solid var(--border)",textAlign:"end"}}>{j.debit?money(j.debit,currency):"—"}</td><td style={{padding:9,borderBottom:"1px solid var(--border)",textAlign:"end"}}>{j.credit?money(j.credit,currency):"—"}</td><td style={{padding:9,borderBottom:"1px solid var(--border)",color:"var(--muted)"}}>{j.source}</td></tr>)}</tbody></table></div></div>
      <div style={{padding:"10px 12px",border:"1px solid color-mix(in srgb,#A16207 30%,var(--border))",borderRadius:9,fontSize:11.5,color:"#A16207"}}>{close.limitations.length} schedule(s) require additional evidence before a complete close: {close.limitations.join(" · ")||"none"}.</div>
      <div style={{display:"flex",gap:8,alignItems:"end",flexWrap:"wrap"}}><label style={{fontSize:10.5,fontWeight:800}}>Accounting mapping<select style={{...input,display:"block"}} value={system} onChange={e=>setSystem(e.target.value)}>{Object.keys(mapping).map(v=><option key={v}>{v}</option>)}</select></label><button onClick={exportSchedules} style={{...input,fontWeight:800,cursor:"pointer",display:"flex",gap:6}}><Download size={14}/>Export schedules CSV</button><button onClick={exportJournal} style={{...input,fontWeight:800,cursor:"pointer",display:"flex",gap:6}}><FileSpreadsheet size={14}/>Export proposed journal</button><label style={{fontSize:10.5,fontWeight:800}}>Prepared by<input style={{...input,display:"block"}} value={preparedBy} onChange={e=>setPreparedBy(e.target.value)}/></label><button disabled={busy||!close.balanced} onClick={save} style={{border:0,borderRadius:8,padding:"9px 12px",background:"#14213D",color:"#fff",fontFamily:"inherit",fontWeight:800,display:"flex",gap:6}}><Save size={14}/>Save close draft</button></div>
      {!!saved.length&&<div style={{borderTop:"1px solid var(--border)",paddingTop:13}}><div style={{display:"flex",justifyContent:"space-between",gap:8,alignItems:"end",flexWrap:"wrap"}}><strong>Close register</strong><label style={{fontSize:10.5,fontWeight:800}}>Finance reviewer<input style={{...input,marginLeft:6}} value={reviewer} onChange={e=>setReviewer(e.target.value)}/></label></div><div style={{display:"flex",flexDirection:"column",gap:7,marginTop:8}}>{saved.map(item=><div key={item.id} style={{border:"1px solid var(--border)",borderRadius:8,padding:"9px 10px",display:"flex",justifyContent:"space-between",gap:8,alignItems:"center",flexWrap:"wrap"}}><div><strong>{item.period_start??"Open"} → {item.period_end??"Open"}</strong><div style={{fontSize:10,color:"var(--muted)"}}>{item.status.toUpperCase()} · prepared by {item.prepared_by}</div></div><div style={{display:"flex",gap:6}}>{item.status==="draft"&&<button onClick={()=>advance(item,"reviewed")} style={input}>Mark reviewed</button>}{item.status==="reviewed"&&<button onClick={()=>advance(item,"approved")} style={input}>Approve</button>}{item.status==="approved"&&<button onClick={()=>advance(item,"locked")} style={{...input,display:"flex",gap:5}}><LockKeyhole size={13}/>Lock version</button>}{item.status==="locked"&&<span style={{fontSize:11,color:"#087F5B",fontWeight:900,display:"flex",gap:5}}><CheckCircle2 size={14}/>Locked</span>}</div></div>)}</div></div>}
      <div style={{fontSize:10.5,color:"var(--muted)"}}>Exports are proposed accounting workpapers only. PrizeSkout does not post to Xero, QuickBooks, Zoho Books, NetSuite, SAP, or any general ledger without a separately authorized integration and explicit approval.</div>
      {error&&<div style={{fontSize:12,color:"#B42318"}}>{error}</div>}
    </div>
  </section>;
}
