import { useEffect,useState } from "react";
import { MerchantField, inferredMerchantHelp } from "@/components/ui/MerchantField";

type Target={id:string;product:string;competitor:string;url:string;category:string|null;channel:string;match_status:string;match_confidence:number;latest_scrape:{price:number|null;currency:string|null;availability:string|null;status:string;scraped_at:string}|null};
const OG="#EF681A",GN="#10B981",RED="#DC2626";

export function CompetitorRadarAccessTab(){
  const [targets,setTargets]=useState<Target[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[message,setMessage]=useState(""),[form,setForm]=useState({product:"",competitor:"",url:"",channel:"online",category:""});
  const call=async(body:Record<string,string>)=>{const response=await fetch("/api/channels/connect",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({merchant_id:localStorage.getItem("ps_merchant_id")??"",access_code:localStorage.getItem("ps_access_code")??"",platform:"competitor_radar",...body})});const result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error??"Request failed");return result;};
  const load=async()=>{setLoading(true);try{const result=await call({action:"list"});setTargets(result.targets??[]);setMessage("");}catch(error){setMessage(error instanceof Error?error.message:"Competitor Radar could not be loaded.");}finally{setLoading(false);}};
  useEffect(()=>{void load();},[]);
  const add=async()=>{setBusy("add");setMessage("");try{await call({action:"add",...form});setForm({product:"",competitor:"",url:"",channel:"online",category:""});await load();setMessage("Competitor product saved. Use Check price now when you want an immediate Firecrawl check; scheduled monitoring will also pick it up.");}catch(error){setMessage(error instanceof Error?error.message:"The competitor product was not saved.");}finally{setBusy("");}};
  const refresh=async(target:Target)=>{setBusy(target.id);setMessage("Checking the public product page now…");try{const result=await call({action:"refresh",id:target.id});await load();setMessage(`Live price confirmed: ${result.scrape.currency??""} ${Number(result.scrape.price).toFixed(2)}.`);}catch(error){setMessage(error instanceof Error?error.message:"The price check failed.");}finally{setBusy("");}};
  const remove=async(target:Target)=>{if(!confirm(`Stop monitoring ${target.product} at ${target.competitor}?`))return;setBusy(target.id);try{await call({action:"remove",id:target.id});await load();setMessage("Competitor product removed from monitoring.");}catch(error){setMessage(error instanceof Error?error.message:"The tracked product was not removed.");}finally{setBusy("");}};
  const canAdd=form.product.trim()&&form.competitor.trim()&&form.url.trim();
  return <div style={{display:"flex",flexDirection:"column",gap:18}}>
    <div><h3 style={{fontSize:18,fontWeight:800,margin:"0 0 6px"}}>Competitor Radar</h3><p style={copy}>Add the exact public product page you want PrizeSkout to monitor. Each URL is matched to one of your products and one sales channel, so its price can inform protected recommendations.</p></div>
    <div style={card}><h4 style={{margin:"0 0 5px",fontSize:15}}>Add a competitor product</h4><p style={{...copy,margin:"0 0 14px"}}>Saving a URL does not spend a Firecrawl credit. An immediate credit is used only when you press <strong>Check price now</strong>; scheduled checks use the shared URL cache where possible.</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:10}}><Field label="Your product"><input value={form.product} onChange={e=>setForm({...form,product:e.target.value})} placeholder="Example: iPad Pro 11-inch M4" style={input}/></Field><Field label="Competitor"><input value={form.competitor} onChange={e=>setForm({...form,competitor:e.target.value})} placeholder="Example: Faisal Al Dayel" style={input}/></Field><Field label="Channel"><input value={form.channel} onChange={e=>setForm({...form,channel:e.target.value})} placeholder="online, jahez, noon…" style={input}/></Field><Field label="Category (optional)"><input value={form.category} onChange={e=>setForm({...form,category:e.target.value})} placeholder="Example: Fragrance" style={input}/></Field></div><Field label="Exact competitor product URL"><input value={form.url} onChange={e=>setForm({...form,url:e.target.value})} placeholder="https://competitor.com/product/..." style={input}/></Field><button type="button" disabled={!canAdd||busy==="add"} onClick={()=>void add()} style={{...button,background:OG,color:"#fff",borderColor:OG,opacity:canAdd&&busy!=="add"?1:.55}}>{busy==="add"?"Saving…":"Add to monitoring"}</button></div>
    <div style={card}><div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"center",flexWrap:"wrap"}}><div><h4 style={{margin:0,fontSize:15}}>Tracked competitor products</h4><p style={{...copy,margin:"4px 0 0"}}>{targets.length} URL{targets.length===1?"":"s"} connected to Competitor Radar.</p></div><button onClick={()=>void load()} style={button}>Refresh list</button></div>{loading?<div style={empty}>Loading tracked products…</div>:!targets.length?<div style={empty}>No competitor products are being monitored yet. Add the first exact product URL above.</div>:<div style={{display:"flex",flexDirection:"column",gap:9,marginTop:14}}>{targets.map(target=><article key={target.id} style={{border:"1px solid var(--border)",borderRadius:11,padding:"13px 14px",display:"grid",gridTemplateColumns:"minmax(0,1fr) auto",gap:12,alignItems:"center"}}><div style={{minWidth:0}}><div style={{display:"flex",gap:7,alignItems:"center",flexWrap:"wrap"}}><strong>{target.product}</strong><Badge text={target.channel}/><Badge text={target.match_status.replaceAll("_"," ")}/>{target.latest_scrape&&<Badge text="live" color={GN}/>}</div><div style={{fontSize:12,color:"var(--muted)",marginTop:4}}>{target.competitor} · {target.latest_scrape?`${target.latest_scrape.currency??""} ${Number(target.latest_scrape.price).toFixed(2)} · checked ${new Date(target.latest_scrape.scraped_at).toLocaleString()}`:"Waiting for first price check"}</div><a href={target.url} target="_blank" rel="noreferrer" style={{display:"block",fontSize:11,color:OG,marginTop:5,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{target.url}</a></div><div style={{display:"flex",gap:6,flexWrap:"wrap",justifyContent:"flex-end"}}><button disabled={busy===target.id} onClick={()=>void refresh(target)} style={button}>{busy===target.id?"Checking…":"Check price now"}</button><button disabled={busy===target.id} onClick={()=>void remove(target)} style={{...button,color:RED}}>Remove</button></div></article>)}</div>}</div>
    <div aria-live="polite" style={{fontSize:12.5,color:message.toLowerCase().includes("failed")||message.toLowerCase().includes("not")?RED:"var(--muted)",minHeight:18}}>{message}</div>
  </div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <MerchantField label={label} help={inferredMerchantHelp(label)} style={{marginBottom:10}}>{children}</MerchantField>}
function Badge({text,color="var(--muted)"}:{text:string;color?:string}){return <span style={{fontSize:9.5,textTransform:"uppercase",fontWeight:850,color,border:"1px solid var(--border)",borderRadius:999,padding:"3px 7px"}}>{text}</span>}
const card:React.CSSProperties={background:"var(--surface2)",border:"1px solid var(--border)",borderRadius:12,padding:"18px 20px"};
const copy:React.CSSProperties={fontSize:13,color:"var(--muted)",lineHeight:1.65};
const input:React.CSSProperties={border:"1px solid var(--border)",borderRadius:8,padding:"10px 11px",background:"var(--surface)",color:"var(--text)",fontFamily:"inherit",fontSize:13};
const button:React.CSSProperties={border:"1px solid var(--border)",borderRadius:8,padding:"8px 11px",background:"var(--surface)",color:"var(--text)",fontFamily:"inherit",fontSize:11.5,fontWeight:750,cursor:"pointer"};
const empty:React.CSSProperties={marginTop:14,padding:20,border:"1px dashed var(--border)",borderRadius:10,color:"var(--muted)",fontSize:12.5,textAlign:"center"};
