import { useEffect, useMemo, useState } from "react";
import { MerchantField, inferredMerchantHelp } from "@/components/ui/MerchantField";

type Item = { id:string; file_name:string; file_size:number; product_name:string|null; product_sku:string|null; match_status:string; match_confidence:number; alt_text:string|null; uploaded_image_id:string|null };
type Job = { id:string; title:string; status:string; created_at:string; ps_product_image_items:Item[] };
const OG="#EF681A", GN="#10B981", RED="#DC2626";

export function ProductImageManagerTab(){
  const [jobs,setJobs]=useState<Job[]>([]),[files,setFiles]=useState<File[]>([]),[query,setQuery]=useState(""),[alt,setAlt]=useState(""),[busy,setBusy]=useState(""),[message,setMessage]=useState("");
  const merchant=()=>localStorage.getItem("ps_merchant_id")??"",code=()=>localStorage.getItem("ps_access_code")??"";
  const load=async()=>{try{const response=await fetch(`/api/copilot/images?merchant_id=${encodeURIComponent(merchant())}&access_code=${encodeURIComponent(code())}`),body=await response.json();if(!response.ok||!body.ok)throw new Error(body.error??"Could not load image jobs.");setJobs(body.jobs??[]);}catch(error){setMessage(error instanceof Error?error.message:"Could not load image jobs.");}};
  useEffect(()=>{void load();},[]);
  const previews=useMemo(()=>files.map(file=>({file,url:URL.createObjectURL(file)})),[files]);
  useEffect(()=>()=>previews.forEach(item=>URL.revokeObjectURL(item.url)),[previews]);

  const upload=async()=>{if(!files.length)return;setBusy("upload");setMessage("");try{const form=new FormData();form.set("merchant_id",merchant());form.set("access_code",code());form.set("product_query",query);form.set("alt_text",alt);files.forEach(file=>form.append("images",file));const response=await fetch("/api/copilot/images",{method:"POST",body:form}),body=await response.json();if(!response.ok||!body.ok)throw new Error(body.error??"Upload failed.");setFiles([]);setQuery("");setAlt("");await load();setMessage(body.job.status==="matched"?"Images uploaded privately and matched. Review the job before applying it.":"Images uploaded, but at least one filename needs a confirmed product match.");}catch(error){setMessage(error instanceof Error?error.message:"Upload failed.");}finally{setBusy("");}};
  const matchItem=async(item:Item)=>{const productQuery=prompt(`Enter the exact product name or SKU for ${item.file_name}:`);if(!productQuery?.trim())return;setBusy(item.id);setMessage("");try{const response=await fetch("/api/copilot/images",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({merchant_id:merchant(),access_code:code(),action:"match_item",item_id:item.id,product_query:productQuery.trim()})}),body=await response.json();if(!response.ok||!body.ok)throw new Error(body.error??"Product could not be matched.");await load();setMessage(`Matched ${item.file_name}.`);}catch(error){setMessage(error instanceof Error?error.message:"Product could not be matched.");}finally{setBusy("");}};
  const action=async(job:Job,kind:"preview"|"rollback")=>{setBusy(job.id);setMessage("");try{const response=await fetch("/api/copilot/images",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({merchant_id:merchant(),access_code:code(),action:kind,job_id:job.id})}),body=await response.json();if(!response.ok||!body.ok)throw new Error(body.error??"Request failed.");if(kind==="preview"){const count=job.ps_product_image_items.length;if(!confirm(`Approve ${count} image upload${count===1?"":"s"} to the connected store? Existing gallery images will be preserved.`)){setMessage("Approval cancelled. Nothing changed in the store.");return;}const appliedResponse=await fetch("/api/copilot/images",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({merchant_id:merchant(),access_code:code(),action:"apply",approval_token:body.preview.approval_token})}),applied=await appliedResponse.json();if(!appliedResponse.ok||!applied.ok)throw new Error(applied.error??applied.message??"Image upload could not be fully verified.");setMessage(applied.message);}else setMessage(body.message);await load();}catch(error){setMessage(error instanceof Error?error.message:"Image action failed.");}finally{setBusy("");}};

  return <div style={{display:"flex",flexDirection:"column",gap:18}}>
    <div><h3 style={{fontSize:18,fontWeight:800,margin:"0 0 6px"}}>Product Image Manager</h3><p style={copy}>Delegate product-image work without hosting files yourself. PrizeSkout stores uploads privately, matches products, preserves the original gallery, asks for approval, uploads to the connected store, and verifies the result.</p></div>
    <div style={card}><h4 style={{margin:"0 0 5px"}}>Prepare an image batch</h4><p style={{...copy,margin:"0 0 14px"}}>Use an exact product name or SKU to assign every selected image to one product. Leave it empty to match filenames against product names and SKUs.</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:10}}><Field label="Exact product or SKU (optional)"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Example: COFFEE-04" style={input}/></Field><Field label="Alt text (optional)"><input value={alt} onChange={e=>setAlt(e.target.value)} placeholder="Defaults to the product name" style={input}/></Field></div><label style={{display:"block",border:"1px dashed var(--border)",borderRadius:11,padding:18,textAlign:"center",cursor:"pointer",background:"var(--surface)"}}><strong>Select product images</strong><div style={{fontSize:11.5,color:"var(--muted)",marginTop:4}}>JPG, PNG or WebP · up to 20 files · 10 MB each</div><input type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={e=>setFiles(Array.from(e.target.files??[]).slice(0,20))} style={{display:"none"}}/></label>{previews.length>0&&<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(110px,1fr))",gap:9,marginTop:12}}>{previews.map(({file,url})=><div key={`${file.name}-${file.lastModified}`} style={{border:"1px solid var(--border)",borderRadius:9,padding:7,background:"var(--surface)"}}><img src={url} alt="Upload preview" style={{width:"100%",aspectRatio:"1",objectFit:"contain",borderRadius:6}}/><div title={file.name} style={{fontSize:10.5,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap",marginTop:5}}>{file.name}</div></div>)}</div>}<button disabled={!files.length||busy==="upload"} onClick={()=>void upload()} style={{...button,background:OG,color:"#fff",borderColor:OG,marginTop:12,opacity:files.length?1:.55}}>{busy==="upload"?"Uploading securely…":`Prepare ${files.length||""} image${files.length===1?"":"s"}`}</button></div>
    <div style={card}><h4 style={{margin:0}}>Image jobs</h4><p style={{...copy,margin:"4px 0 12px"}}>A completed job means the connected store returned every uploaded image during verification—not merely that it accepted the request. Existing gallery images are preserved; approved images are appended in the selected order.</p>{!jobs.length?<div style={empty}>No product-image jobs yet.</div>:<div style={{display:"flex",flexDirection:"column",gap:9}}>{jobs.map(job=><article key={job.id} style={{border:"1px solid var(--border)",borderRadius:10,padding:"12px 13px",display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"}}><div><div style={{display:"flex",gap:7,alignItems:"center",flexWrap:"wrap"}}><strong>{job.title}</strong><Badge text={job.status} color={job.status==="completed"?GN:job.status.includes("attention")||job.status==="partial"?RED:"var(--muted)"}/></div><div style={{fontSize:11.5,color:"var(--muted)",marginTop:4}}>{job.ps_product_image_items.length} image{job.ps_product_image_items.length===1?"":"s"} · {job.ps_product_image_items.filter(item=>item.match_status==="confirmed").length} confirmed match{job.ps_product_image_items.length===1?"":"es"} · {new Date(job.created_at).toLocaleString()}</div>{job.ps_product_image_items.map(item=><div key={item.id} style={{fontSize:10.5,color:"var(--muted)",marginTop:4,display:"flex",gap:7,alignItems:"center",flexWrap:"wrap"}}><span>{item.file_name} → {item.product_name??"Unmatched"}{item.product_sku?` (${item.product_sku})`:""}</span>{item.match_status!=="confirmed"&&<button disabled={busy===item.id} onClick={()=>void matchItem(item)} style={{...button,padding:"4px 7px",fontSize:10}}>Match product</button>}</div>)}</div><div style={{display:"flex",gap:6}}>{["matched","needs_attention","draft"].includes(job.status)&&<button disabled={busy===job.id||job.status==="needs_attention"} onClick={()=>void action(job,"preview")} style={button}>Review &amp; approve</button>}{["completed","partial"].includes(job.status)&&<button disabled={busy===job.id} onClick={()=>void action(job,"rollback")} style={{...button,color:RED}}>Undo uploaded images</button>}</div></article>)}</div>}</div>
    <div aria-live="polite" style={{minHeight:18,fontSize:12.5,color:message.toLowerCase().includes("failed")||message.toLowerCase().includes("could not")?RED:"var(--muted)"}}>{message}</div>
  </div>;
}

function Field({label,children}:{label:string;children:React.ReactNode}){return <MerchantField label={label} help={inferredMerchantHelp(label)}>{children}</MerchantField>}
function Badge({text,color}:{text:string;color:string}){return <span style={{fontSize:9.5,fontWeight:850,textTransform:"uppercase",color,border:"1px solid var(--border)",borderRadius:999,padding:"3px 7px"}}>{text.replaceAll("_"," ")}</span>}
const card:React.CSSProperties={background:"var(--surface2)",border:"1px solid var(--border)",borderRadius:12,padding:"18px 20px"},copy:React.CSSProperties={fontSize:13,color:"var(--muted)",lineHeight:1.65},input:React.CSSProperties={border:"1px solid var(--border)",borderRadius:8,padding:"10px 11px",background:"var(--surface)",color:"var(--text)",fontFamily:"inherit"},button:React.CSSProperties={border:"1px solid var(--border)",borderRadius:8,padding:"8px 11px",background:"var(--surface)",color:"var(--text)",fontFamily:"inherit",fontSize:11.5,fontWeight:750,cursor:"pointer"},empty:React.CSSProperties={padding:20,border:"1px dashed var(--border)",borderRadius:10,color:"var(--muted)",fontSize:12.5,textAlign:"center"};
