import {createFileRoute} from "@tanstack/react-router";
import {supabaseAdmin} from "@/integrations/supabase/client.server";
import {applyImageJob,assignImageItem,createImageJob,listImageJobs,previewImageJob,rollbackImageJob} from "@/server/core/product-image-manager";

const respond=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json"}});
async function context(merchantId:string,accessCode:string){const {data:code}=await supabaseAdmin.from("ps_access_codes" as never).select("merchant_id").eq("code",accessCode.trim().toUpperCase()).maybeSingle() as {data:{merchant_id:string}|null};if(!code||code.merchant_id!==merchantId)throw new Error("Unauthorized");const {data:channel}=await supabaseAdmin.from("ps_merchant_channels").select("bearer_token,manager_token,metadata,status").eq("account_id",merchantId).eq("platform","zid").maybeSingle();if(!channel||channel.status!=="connected"||!channel.bearer_token)throw new Error("Zid is not connected.");const metadata=(channel.metadata??{}) as Record<string,unknown>,authorization=channel.bearer_token.startsWith("Bearer ")?channel.bearer_token:`Bearer ${channel.bearer_token}`;return{headers:{Authorization:authorization,"X-Manager-Token":channel.manager_token??"","Access-Token":channel.manager_token??"",...(metadata.store_id?{"Store-Id":String(metadata.store_id)}:{}),Role:"Manager",Accept:"application/json","Accept-Language":"en"}};}

export const Route=createFileRoute("/api/copilot/images")({server:{handlers:{
  GET:async({request})=>{const url=new URL(request.url),merchantId=url.searchParams.get("merchant_id")??"",code=url.searchParams.get("access_code")??"";try{await context(merchantId,code);return respond({ok:true,jobs:await listImageJobs(merchantId)});}catch(error){return respond({error:error instanceof Error?error.message:"Could not load image jobs."},error instanceof Error&&error.message==="Unauthorized"?403:422);}},
  POST:async({request})=>{try{const type=request.headers.get("content-type")??"";if(type.includes("multipart/form-data")){const form=await request.formData(),merchantId=String(form.get("merchant_id")??""),code=String(form.get("access_code")??""),{headers}=await context(merchantId,code),files=form.getAll("images").filter(value=>value instanceof File) as File[];return respond({ok:true,job:await createImageJob(merchantId,headers,{files,productQuery:String(form.get("product_query")??""),altText:String(form.get("alt_text")??"")})});}
    const body=await request.json() as Record<string,string>,merchantId=body.merchant_id??"",{headers}=await context(merchantId,body.access_code??"");if(body.action==="match_item")return respond({ok:true,...await assignImageItem(merchantId,headers,body.item_id,body.product_query)});if(body.action==="preview")return respond({ok:true,preview:await previewImageJob(merchantId,headers,body.job_id)});if(body.action==="apply"){const result=await applyImageJob(merchantId,headers,body.approval_token);return respond(result,result.ok?200:502);}if(body.action==="rollback"){const result=await rollbackImageJob(merchantId,headers,body.job_id);return respond(result,result.ok?200:502);}return respond({error:"Unsupported image action."},400);
  }catch(error){const message=error instanceof Error?error.message:"Product image request failed.";return respond({error:message},message==="Unauthorized"?403:422);}}
}}});
