import {supabaseAdmin} from "@/integrations/supabase/client.server";
import {evidenceFingerprint} from "./merchant-evidence";
import {appendEvidenceProcessingAttempt,registerMerchantEvidence} from "./merchant-evidence-intake";
import {NORMALIZED_COMMERCE_VERSION,type NormalizedCommerceEvent} from "./normalized-commerce-events";
import {createEvidenceReviewDraft} from "./evidence-review";
import {matchEvidenceAgreement} from "./evidence-agreement-matcher";
import {runNormalizedReconciliationShadow} from "./normalized-reconciliation-shadow";

export type SourceOrderRecord={external_event_id:string;order_id:string;occurred_at:string;channel:string;branch_external_id?:string|null;currency:string;gross_amount:number;discount_amount?:number;tax_amount?:number;refund_amount?:number;cancellation_amount?:number;status?:string;final?:boolean};
const money=(value:number)=>Math.round(value*100)/100,clean=(value:unknown,max=180)=>typeof value==="string"?value.trim().slice(0,max):"";
export function prepareSourceOrderBatch(records:unknown){
  if(!Array.isArray(records)||!records.length||records.length>1000)throw new Error("Provide between 1 and 1,000 order records.");
  const seen=new Set<string>();return records.map((raw,index)=>{if(!raw||typeof raw!=="object")throw new Error(`Order record ${index+1} is invalid.`);const row=raw as Record<string,unknown>,external=clean(row.external_event_id),order=clean(row.order_id),channel=clean(row.channel,80).toLowerCase(),currency=clean(row.currency,12).toUpperCase(),occurred=clean(row.occurred_at,40),gross=Number(row.gross_amount);if(!external||!order||!channel||!currency||!Number.isFinite(gross)||gross<0||Number.isNaN(Date.parse(occurred)))throw new Error(`Order record ${index+1} is missing a valid identity, date, channel, currency, or gross amount.`);if(seen.has(external))throw new Error(`Order event ${external} is duplicated in this batch.`);seen.add(external);const optional=(key:string)=>{const value=row[key]==null?0:Number(row[key]);if(!Number.isFinite(value)||value<0)throw new Error(`Order record ${index+1} has an invalid ${key}.`);return money(value);};return {external_event_id:external,order_id:order,occurred_at:new Date(occurred).toISOString(),channel,branch_external_id:clean(row.branch_external_id,160)||null,currency,gross_amount:money(gross),discount_amount:optional("discount_amount"),tax_amount:optional("tax_amount"),refund_amount:optional("refund_amount"),cancellation_amount:optional("cancellation_amount"),status:clean(row.status,80)||"unknown",final:row.final===true};});
}

export function validateAuthorizedSourceRecords(records:SourceOrderRecord[],permissions:unknown){
  const allowed=new Set(Array.isArray(permissions)?permissions.filter((value):value is string=>typeof value==="string"):[]),missing:string[]=[];
  if(!allowed.has("completed_orders"))missing.push("completed_orders");
  if(records.some(row=>(row.refund_amount??0)>0)&&!allowed.has("refunds"))missing.push("refunds");
  if(records.some(row=>(row.cancellation_amount??0)>0)&&!allowed.has("cancellations"))missing.push("cancellations");
  if(records.some(row=>(row.discount_amount??0)>0)&&!allowed.has("discount_funding"))missing.push("discount_funding");
  if(records.some(row=>(row.tax_amount??0)>0)&&!allowed.has("taxes"))missing.push("taxes");
  if(missing.length)throw new Error(`This delivery includes evidence outside the merchant authorization. Required permission${missing.length===1?"":"s"}: ${[...new Set(missing)].join(", ")}.`);
}

export function assessSourceDeliveryCompleteness(received:number,declared:number|null|undefined,explicitlyComplete:boolean){if(declared!=null&&(!Number.isInteger(declared)||declared<0))throw new Error("Declared record count must be a non-negative whole number.");const countMatches=declared==null||declared===received,complete=explicitlyComplete&&countMatches;return {state:complete?"completed" as const:"partial" as const,complete,reason:complete?null:!explicitlyComplete?"The source did not explicitly confirm that this delivery was complete.":`The source declared ${declared} records but PrizeSkout received ${received}.`};}

export async function syncEvidenceSourceOrders(input:{connectionId:string;batchId:string;cursorAfter?:string|null;records:unknown;deliveryComplete?:boolean;declaredRecordCount?:number|null}){
  if(!clean(input.batchId,180))throw new Error("A stable provider batch ID is required.");
  const db=supabaseAdmin as any,{data:connection,error}=await db.from("ps_evidence_source_connections").select("*").eq("id",input.connectionId).eq("status","active").eq("read_only",true).maybeSingle();if(error||!connection)throw new Error(error?.message??"An active read-only evidence source was not found.");
  const {data:authorization,error:authorizationError}=await db.from("ps_evidence_source_authorizations").select("id,approved_by,permissions,branch_references").eq("account_id",connection.account_id).eq("connection_id",connection.id).maybeSingle();if(authorizationError||!authorization)throw new Error(authorizationError?.message??"Merchant authorization is required before automatic source evidence can be accepted.");
  const records=prepareSourceOrderBatch(input.records),delivery=assessSourceDeliveryCompleteness(records.length,input.declaredRecordCount,input.deliveryComplete===true),{data:run,error:runError}=await db.from("ps_evidence_source_sync_runs").insert({account_id:connection.account_id,connection_id:connection.id,state:"running",cursor_before:connection.sync_cursor}).select("id").single();if(runError||!run)throw new Error(runError?.message??"Evidence sync run could not start.");
  try{
    validateAuthorizedSourceRecords(records,authorization.permissions);const allowedBranches=(authorization.branch_references??[]).map((value:string)=>value.trim().toLowerCase());if(allowedBranches.length&&records.some(row=>!row.branch_external_id||!allowedBranches.includes(row.branch_external_id.toLowerCase())))throw new Error("At least one order falls outside the merchant-authorized branch scope.");
    const contentHash=evidenceFingerprint({connection_id:connection.id,batch_id:input.batchId,records}),intake=await registerMerchantEvidence({accountId:connection.account_id,merchantId:connection.merchant_id,sourceKind:"optional_api",sourceProvider:connection.provider,sourceExternalId:`${connection.id}:${clean(input.batchId,180)}`,documentKind:"order_export",contentSha256:contentHash,mediaType:"application/json",sourceMetadata:{connection_id:connection.id,batch_id:clean(input.batchId,180),record_count:records.length,data_minimized:true,customer_and_payment_fields_retained:false}});
    const events:NormalizedCommerceEvent[]=records.map(row=>{const cancelled=row.cancellation_amount>0,statusFinal=row.final,cashNet=Math.max(0,row.gross_amount-row.discount_amount+row.tax_amount-row.refund_amount-row.cancellation_amount),strong=statusFinal&&delivery.complete,base:Omit<NormalizedCommerceEvent,"event_fingerprint">={account_id:connection.account_id,merchant_id:connection.merchant_id,evidence_item_id:intake.evidenceItemId,source_kind:"optional_api",source_provider:connection.provider,external_event_id:row.external_event_id,event_kind:"order_snapshot",channel:row.channel,branch_external_id:row.branch_external_id,order_external_id:row.order_id,settlement_reference:null,occurred_at:row.occurred_at,currency:row.currency,gross_amount:row.gross_amount,discount_amount:row.discount_amount,tax_amount:row.tax_amount,fee_amount:null,net_amount:money(cashNet),normalized_payload:{status:row.status,eligible:strong&&!cancelled,claims_ready:strong,final:statusFinal,delivery_complete:delivery.complete,refund_amount:row.refund_amount,cancellation_amount:row.cancellation_amount,source_connection_id:connection.id},normalization_version:NORMALIZED_COMMERCE_VERSION,evidence_strength:strong?"strong":"partial",limitations:[...(!statusFinal?["The source order is not yet final."]:[]),...(delivery.reason?[delivery.reason]:[])]};return {...base,event_fingerprint:evidenceFingerprint(base)};});
    let created=0,shadowRunId:null|string=null,agreementState:null|string=null;if(!intake.duplicate){const {data,error:eventError}=await db.from("ps_normalized_commerce_events").upsert(events,{onConflict:"account_id,source_provider,event_kind,external_event_id,event_fingerprint",ignoreDuplicates:true}).select("id");if(eventError)throw new Error(eventError.message);created=data?.length??0;const attempt=await appendEvidenceProcessingAttempt({evidenceItemId:intake.evidenceItemId,accountId:connection.account_id,processorVersion:`${NORMALIZED_COMMERCE_VERSION}:source-sync`,attemptNumber:1,state:"normalized",detectedDocumentKind:"order_export",extractionSummary:{record_count:records.length,event_count:created,data_minimized:true,source_authorization_id:authorization.id}});
      const channels=[...new Set(records.map(row=>row.channel))],currencies=[...new Set(records.map(row=>row.currency))],branches=[...new Set(records.map(row=>row.branch_external_id).filter((value):value is string=>Boolean(value)))],dates=records.map(row=>row.occurred_at.slice(0,10)).sort(),platform=channels.length===1?channels[0]:connection.provider;
      const review=await createEvidenceReviewDraft({accountId:connection.account_id,merchantId:connection.merchant_id,evidenceItemId:intake.evidenceItemId,processingAttemptId:attempt.attemptId,processorVersion:`${NORMALIZED_COMMERCE_VERSION}:authorized-source`,documentKind:"order_export",platform,extractionPayload:{format:"authorized_source",source_authorization_id:authorization.id,record_count:records.length,period_start:dates[0],period_end:dates.at(-1),currency:currencies.length===1?currencies[0]:null,branch_external_id:branches.length===1?branches[0]:null,data_minimized:true},warnings:[],confidence:1});
      const reviewedPayload={format:"authorized_source",source_authorization_id:authorization.id,record_count:records.length,period_start:dates[0],period_end:dates.at(-1),currency:currencies.length===1?currencies[0]:null,branch_external_id:branches.length===1?branches[0]:null};const {data:decision,error:decisionError}=await db.from("ps_evidence_review_decisions").insert({account_id:connection.account_id,merchant_id:connection.merchant_id,evidence_item_id:intake.evidenceItemId,review_draft_id:review.reviewDraftId,decision:"approved",reviewed_payload:reviewedPayload,correction_summary:"Automatically accepted under the merchant's immutable read-only source authorization.",reviewer_email:authorization.approved_by}).select("id").single();if(decisionError||!decision)throw new Error(decisionError?.message??"Authorized source decision could not be recorded.");await db.from("ps_evidence_review_drafts").update({status:"approved"}).eq("id",review.reviewDraftId).eq("status","pending");
      const agreement=await matchEvidenceAgreement({accountId:connection.account_id,merchantId:connection.merchant_id,evidenceItemId:intake.evidenceItemId,reviewDecisionId:decision.id,context:{platform,periodStart:dates[0],periodEnd:dates.at(-1)??dates[0],currency:currencies.length===1?currencies[0]:null,branch:branches.length===1?branches[0]:null,brand:null,legalEntity:null}});agreementState=agreement.state;const shadow=await runNormalizedReconciliationShadow({accountId:connection.account_id,evidenceItemId:intake.evidenceItemId,contractTermId:agreement.state==="automatic"?String(agreement.contract_term_id):null,requireExplicitContract:true});shadowRunId=shadow.runId;}
    const finished=new Date().toISOString(),occurred=records.map(row=>row.occurred_at).sort(),finalRecords=records.filter(row=>row.final).length;await db.from("ps_evidence_source_sync_runs").update({state:delivery.state,cursor_after:input.cursorAfter??connection.sync_cursor,records_seen:records.length,declared_record_count:input.declaredRecordCount??null,delivery_complete:delivery.complete,evidence_items_created:intake.duplicate?0:1,duplicates_ignored:intake.duplicate?records.length:Math.max(0,records.length-created),evidence_period_start:occurred[0],evidence_period_end:occurred.at(-1),final_records:finalRecords,non_final_records:records.length-finalRecords,channels:[...new Set(records.map(row=>row.channel))],currencies:[...new Set(records.map(row=>row.currency))],branch_references:[...new Set(records.map(row=>row.branch_external_id).filter((value):value is string=>Boolean(value)))],error_message:delivery.reason,finished_at:finished}).eq("id",run.id);await db.from("ps_evidence_source_connections").update({sync_cursor:input.cursorAfter??connection.sync_cursor,last_sync_at:finished,last_success_at:delivery.complete?finished:connection.last_success_at,last_delivery_state:delivery.state,last_error:delivery.reason,updated_at:finished}).eq("id",connection.id);return {runId:run.id,evidenceItemId:intake.evidenceItemId,duplicate:intake.duplicate,records:records.length,eventsCreated:created,agreementState,shadowRunId,deliveryState:delivery.state,deliveryComplete:delivery.complete};
  }catch(reason){const message=(reason instanceof Error?reason.message:String(reason)).slice(0,2000),finished=new Date().toISOString();await db.from("ps_evidence_source_sync_runs").update({state:"failed",error_message:message,finished_at:finished}).eq("id",run.id);await db.from("ps_evidence_source_connections").update({last_sync_at:finished,last_delivery_state:"failed",last_error:message,updated_at:finished}).eq("id",connection.id);throw reason;}
}
