import {supabaseAdmin} from "@/integrations/supabase/client.server";

export const EVIDENCE_READ_PERMISSIONS=["completed_orders","refunds","cancellations","discount_funding","taxes","service_charges","delivery_charges","settlement_references"] as const;
type Permission=typeof EVIDENCE_READ_PERMISSIONS[number];
const kinds=["optional_api","automatic_report","watched_folder","local_connector","order_management_partner"] as const;
const clean=(value:unknown,max=180)=>typeof value==="string"?value.trim().slice(0,max):"";
export function prepareEvidenceSource(input:{provider:unknown;connectionKind:unknown;permissions:unknown;branches?:unknown;externalReference?:unknown;expectedIntervalMinutes?:unknown}){
  const provider=clean(input.provider,80).toLowerCase(),connectionKind=clean(input.connectionKind,40);
  if(!provider)throw new Error("Evidence source provider is required.");if(!kinds.includes(connectionKind as any))throw new Error("Choose a supported evidence connection type.");
  const requested=Array.isArray(input.permissions)?[...new Set(input.permissions.map(value=>clean(value,60)).filter(Boolean))]:[];
  const forbidden=requested.filter(value=>!EVIDENCE_READ_PERMISSIONS.includes(value as Permission));if(forbidden.length)throw new Error(`Only read-only evidence permissions are allowed. Remove: ${forbidden.join(", ")}.`);
  const branches=Array.isArray(input.branches)?[...new Set(input.branches.map(value=>clean(value,160)).filter(Boolean))].slice(0,250):[];
  const interval=Number(input.expectedIntervalMinutes??1440);if(!Number.isInteger(interval)||interval<15||interval>10080)throw new Error("Expected sync frequency must be between 15 minutes and 7 days.");
  return {provider,connection_kind:connectionKind,read_only:true,permissions:requested,branch_references:branches,external_connection_reference:clean(input.externalReference,240)||"default",expected_sync_interval_minutes:interval};
}
export function assessEvidenceSourceHealth(source:{status:string;last_sync_at?:string|null;last_success_at?:string|null;last_error?:string|null;last_delivery_state?:string|null;expected_sync_interval_minutes?:number|null},now=Date.now()){
  if(source.status==="setup_required")return {state:"setup_required" as const,label:"Setup required",attention:true};if(source.status==="paused")return {state:"paused" as const,label:"Paused",attention:false};if(source.status==="disconnected")return {state:"disconnected" as const,label:"Disconnected",attention:false};if(source.last_error&&(!source.last_success_at||Date.parse(source.last_sync_at??"")>Date.parse(source.last_success_at)))return {state:"failed" as const,label:"Latest sync failed",attention:true};if(!source.last_success_at)return {state:"awaiting_first_sync" as const,label:"Waiting for first sync",attention:true};const interval=(source.expected_sync_interval_minutes??1440)*60_000,age=now-Date.parse(source.last_success_at);if(age>interval*1.5)return {state:"late" as const,label:"Evidence is late",attention:true};return {state:"healthy" as const,label:"Current",attention:false};
}
type CoverageRun={state:string;records_seen:number;evidence_period_start:string|null;evidence_period_end:string|null;final_records:number;non_final_records:number;channels:string[];currencies:string[];branch_references:string[];finished_at:string|null};
export function summarizeEvidenceSourceCoverage(runs:CoverageRun[]){
  const observed=runs.filter(run=>["completed","partial"].includes(run.state)&&run.evidence_period_start&&run.evidence_period_end),times=observed.flatMap(run=>[Date.parse(run.evidence_period_start!),Date.parse(run.evidence_period_end!)]).filter(Number.isFinite);
  return {basis:"observed_deliveries" as const,completeness:"not_guaranteed" as const,period_start:times.length?new Date(Math.min(...times)).toISOString():null,period_end:times.length?new Date(Math.max(...times)).toISOString():null,records_seen:observed.reduce((sum,run)=>sum+Number(run.records_seen||0),0),final_records:observed.reduce((sum,run)=>sum+Number(run.final_records||0),0),non_final_records:observed.reduce((sum,run)=>sum+Number(run.non_final_records||0),0),channels:[...new Set(observed.flatMap(run=>run.channels??[]))].sort(),currencies:[...new Set(observed.flatMap(run=>run.currencies??[]))].sort(),branches:[...new Set(observed.flatMap(run=>run.branch_references??[]))].sort(),successful_deliveries:observed.filter(run=>run.state==="completed").length,incomplete_deliveries:observed.filter(run=>run.state==="partial").length};
}
export async function listEvidenceSources(accountId:string){const db=supabaseAdmin as any,{data,error}=await db.from("ps_evidence_source_connections").select("id,provider,connection_kind,status,read_only,permissions,branch_references,external_connection_reference,expected_sync_interval_minutes,last_sync_at,last_success_at,last_error,last_delivery_state,created_at,updated_at,ps_evidence_source_authorizations(approved_by,approved_at)").eq("account_id",accountId).order("created_at",{ascending:false});if(error)throw new Error(error.message);const ids=(data??[]).map((source:any)=>source.id),{data:runs,error:runsError}=ids.length?await db.from("ps_evidence_source_sync_runs").select("connection_id,state,records_seen,evidence_period_start,evidence_period_end,final_records,non_final_records,channels,currencies,branch_references,finished_at").eq("account_id",accountId).in("connection_id",ids).in("state",["completed","partial"]).order("finished_at",{ascending:false}).limit(1000):{data:[],error:null};if(runsError&&runsError.code!=="42703")throw new Error(runsError.message);return (data??[]).map((source:any)=>({...source,health:assessEvidenceSourceHealth(source),coverage:summarizeEvidenceSourceCoverage((runs??[]).filter((run:any)=>run.connection_id===source.id)),authorized:Array.isArray(source.ps_evidence_source_authorizations)?source.ps_evidence_source_authorizations.length>0:Boolean(source.ps_evidence_source_authorizations)}));}
export async function registerEvidenceSource(accountId:string,merchantId:string,input:Parameters<typeof prepareEvidenceSource>[0]){const prepared=prepareEvidenceSource(input),{data,error}=await (supabaseAdmin as any).from("ps_evidence_source_connections").upsert({account_id:accountId,merchant_id:merchantId,...prepared,status:"setup_required",updated_at:new Date().toISOString()},{onConflict:"account_id,provider,connection_kind,external_connection_reference"}).select("id,provider,connection_kind,status,read_only,permissions,branch_references").single();if(error||!data)throw new Error(error?.message??"Evidence source could not be registered.");return data;}
export async function setEvidenceSourceStatus(accountId:string,id:string,status:string,approvedBy?:string){if(!["active","paused","disconnected"].includes(status))throw new Error("Choose active, paused, or disconnected.");const db=supabaseAdmin as any,{data:current,error:currentError}=await db.from("ps_evidence_source_connections").select("id,provider,status,permissions,branch_references").eq("account_id",accountId).eq("id",id).maybeSingle();if(currentError||!current)throw new Error(currentError?.message??"Evidence source was not found.");if(current.status==="disconnected")throw new Error("A disconnected source cannot be reactivated; create a new connection authorization.");if(status==="active"){const reviewer=clean(approvedBy,320);if(!reviewer)throw new Error("The merchant approver is required before activating automatic evidence.");const {error:approvalError}=await db.from("ps_evidence_source_authorizations").upsert({account_id:accountId,connection_id:id,approved_by:reviewer,approval_statement:"I authorize PrizeSkout to collect the listed read-only financial evidence for the selected branches. This does not authorize write access or external actions.",permissions:current.permissions,branch_references:current.branch_references},{onConflict:"connection_id",ignoreDuplicates:true});if(approvalError)throw new Error(approvalError.message);}const {data,error}=await db.from("ps_evidence_source_connections").update({status,updated_at:new Date().toISOString()}).eq("account_id",accountId).eq("id",id).neq("status","disconnected").select("id,provider,status").maybeSingle();if(error||!data)throw new Error(error?.message??"Evidence source could not be updated.");return data;}
