import {createHash,createHmac,timingSafeEqual} from "crypto";
import {supabaseAdmin as typedSupabaseAdmin} from "@/integrations/supabase/client.server";
import {displayProductName,productMatches} from "./zid-product-match";
import {createStoreManagerTask,transitionStoreManagerTask} from "./store-manager";

type Obj=Record<string,unknown>;type Headers=Record<string,string>;
const supabaseAdmin=typedSupabaseAdmin as any;
const BUCKET="product-image-jobs",secret=()=>process.env.COPILOT_APPROVAL_SECRET||process.env.SUPABASE_SERVICE_ROLE_KEY||"";
const rows=(payload:Obj,key:string)=>Array.isArray(payload[key])?payload[key] as Obj[]:Array.isArray(payload.results)?payload.results as Obj[]:[];
async function zid(url:string,headers:Headers,init?:RequestInit){const response=await fetch(url,{...init,headers:{...headers,...(init?.headers??{})}}),payload=await response.json().catch(()=>({})) as Obj;return{response,payload};}
async function products(headers:Headers){const all:Obj[]=[];for(let page=1;page<=50;page++){const call=await zid(`https://api.zid.sa/v1/products/?page=${page}&page_size=100`,headers);if(!call.response.ok)throw new Error(`Zid products returned ${call.response.status}.`);const batch=rows(call.payload,"products");all.push(...batch);if(batch.length<100)break;}return all;}
async function gallery(headers:Headers,id:string){const call=await zid(`https://api.zid.sa/v1/products/${encodeURIComponent(id)}/images/`,headers);if(!call.response.ok)throw new Error(`Zid product images returned ${call.response.status}.`);return rows(call.payload,"images");}
function token(payload:Obj){const raw=Buffer.from(JSON.stringify(payload)).toString("base64url"),key=secret();if(!key)throw new Error("Approval signing is not configured.");return`${raw}.${createHmac("sha256",key).update(raw).digest("base64url")}`;}
function decode(value:string,accountId:string){const [raw,sig]=value.split("."),key=secret();if(!raw||!sig||!key)throw new Error("Invalid image approval.");const expected=Buffer.from(createHmac("sha256",key).update(raw).digest("base64url")),actual=Buffer.from(sig);if(actual.length!==expected.length||!timingSafeEqual(actual,expected))throw new Error("The image approval was changed.");const payload=JSON.parse(Buffer.from(raw,"base64url").toString()) as Obj;if(payload.account_id!==accountId||Number(payload.expires_at)<Date.now())throw new Error("The image approval expired. Preview it again.");return payload;}
function detectedMime(bytes:Buffer){if(bytes.length>=3&&bytes[0]===0xff&&bytes[1]===0xd8&&bytes[2]===0xff)return"image/jpeg";if(bytes.length>=8&&bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))return"image/png";if(bytes.length>=12&&bytes.toString("ascii",0,4)==="RIFF"&&bytes.toString("ascii",8,12)==="WEBP")return"image/webp";return"";}
async function moveTask(accountId:string,taskId:unknown,toStatus:string,note:string){if(!taskId)return;try{await transitionStoreManagerTask(accountId,{id:String(taskId),toStatus,actor:"PrizeSkout Image Manager",note});}catch{/* Image execution remains authoritative; task synchronization is best effort. */}}
export async function createImageJob(accountId:string,headers:Headers,input:{files:File[];productQuery?:string;altText?:string}){
  if(!input.files.length||input.files.length>20)throw new Error("Upload between 1 and 20 images per job.");
  const total=input.files.reduce((sum,file)=>sum+file.size,0);if(total>50*1024*1024)throw new Error("A batch cannot exceed 50 MB.");
  const catalogue=await products(headers),query=input.productQuery?.trim();let explicit:Obj|null=null;
  if(query){const matches=catalogue.filter(product=>productMatches(product,query,true));if(matches.length!==1)throw new Error(matches.length?`More than one product matched ${query}. Use its exact SKU.`:`No product matched ${query}.`);explicit=matches[0];}
  const {data:job,error:jobError}=await (supabaseAdmin.from("ps_product_image_jobs") as any).insert({account_id:accountId,title:query?`Images for ${query}`:`Image batch ${new Date().toLocaleDateString("en-SA")}`,status:"draft",policy:{preserve_originals:true,approval_required:true,max_files:20}}).select("*").single();if(jobError)throw new Error(`${jobError.message}. Run migration 20260806040000_product_image_manager.sql.`);
  const created:Obj[]=[],uploadedPaths:string[]=[];
  try{for(let index=0;index<input.files.length;index++){const file=input.files[index];if(!["image/jpeg","image/png","image/webp"].includes(file.type)||file.size>10*1024*1024)throw new Error(`${file.name} must be JPG, PNG, or WebP and no larger than 10 MB.`);const bytes=Buffer.from(await file.arrayBuffer()),actualMime=detectedMime(bytes);if(actualMime!==file.type)throw new Error(`${file.name} does not contain a valid ${file.type.replace("image/","").toUpperCase()} image.`);const hash=createHash("sha256").update(bytes).digest("hex"),extension=file.type.split("/")[1].replace("jpeg","jpg"),path=`${accountId}/${job.id}/${String(index+1).padStart(3,"0")}-${hash.slice(0,12)}.${extension}`;const upload=await supabaseAdmin.storage.from(BUCKET).upload(path,bytes,{contentType:file.type,upsert:false});if(upload.error)throw upload.error;uploadedPaths.push(path);
    const stem=file.name.replace(/\.[^.]+$/,"").replace(/[_-]+/g," ").trim(),matches=explicit?[explicit]:catalogue.filter(product=>productMatches(product,stem,true));const matched=matches.length===1?matches[0]:null,matchStatus=explicit||matched?"confirmed":matches.length>1?"ambiguous":"unmatched",exactSku=Boolean(matched&&String(matched.sku??"")&&stem.toLowerCase().includes(String(matched.sku).toLowerCase())),confidence=explicit?1:matched?(exactSku?1:.92):0;
    const {data:item,error}=await (supabaseAdmin.from("ps_product_image_items") as any).insert({job_id:job.id,account_id:accountId,storage_path:path,file_name:file.name,mime_type:file.type,file_size:file.size,sha256:hash,alt_text:(input.altText||matched&&displayProductName(matched)||stem).slice(0,240),position:index,is_cover:index===0,product_id:matched?String(matched.id):null,product_sku:matched?String(matched.sku??""):null,product_name:matched?displayProductName(matched):null,match_status:matchStatus,match_confidence:confidence}).select("*").single();if(error)throw error;created.push(item);}
  }catch(error){if(uploadedPaths.length)await supabaseAdmin.storage.from(BUCKET).remove(uploadedPaths);await (supabaseAdmin.from("ps_product_image_jobs") as any).delete().eq("id",job.id);throw error;}
  const ready=created.every(item=>item.match_status==="confirmed");const managerTask=await createStoreManagerTask(accountId,{title:`Prepare ${created.length} product image${created.length===1?"":"s"}`,detail:ready?"Images are matched and ready for merchant preview.":"One or more images need a confirmed product match.",taskType:"product_images",priority:"medium",approvalRequired:false,riskLevel:"reversible"}).catch(()=>null);await (supabaseAdmin.from("ps_product_image_jobs") as any).update({status:ready?"matched":"needs_attention",manager_task_id:(managerTask as Obj|null)?.id??null}).eq("id",job.id);await (supabaseAdmin.from("ps_product_image_events") as any).insert({account_id:accountId,job_id:job.id,event_type:"uploaded_and_matched",actor:"merchant",detail:{files:created.length,ready}});return{...job,status:ready?"matched":"needs_attention",manager_task_id:(managerTask as Obj|null)?.id??null,items:created};
}
export async function listImageJobs(accountId:string){const {data,error}=await (supabaseAdmin.from("ps_product_image_jobs") as any).select("*,ps_product_image_items(*)").eq("account_id",accountId).order("created_at",{ascending:false}).limit(30);if(error)throw new Error(`${error.message}. Run migration 20260806040000_product_image_manager.sql.`);return data??[];}
export async function assignImageItem(accountId:string,headers:Headers,itemId:string,query:string){const search=query.trim();if(!search)throw new Error("Enter an exact product name or SKU.");const catalogue=await products(headers),matches=catalogue.filter(product=>productMatches(product,search,true));if(matches.length!==1)throw new Error(matches.length?"More than one product matched. Use the exact SKU.":"No product matched that name or SKU.");const product=matches[0],{data:item,error}=await (supabaseAdmin.from("ps_product_image_items") as any).update({product_id:String(product.id),product_sku:String(product.sku??""),product_name:displayProductName(product),match_status:"confirmed",match_confidence:1}).eq("account_id",accountId).eq("id",itemId).select("*").single();if(error||!item)throw new Error(error?.message??"Image item not found.");const {data:items}=await (supabaseAdmin.from("ps_product_image_items") as any).select("match_status").eq("job_id",item.job_id),ready=Boolean(items?.length&&items.every((row:Obj)=>row.match_status==="confirmed"));await (supabaseAdmin.from("ps_product_image_jobs") as any).update({status:ready?"matched":"needs_attention"}).eq("account_id",accountId).eq("id",item.job_id);await (supabaseAdmin.from("ps_product_image_events") as any).insert({account_id:accountId,job_id:item.job_id,event_type:"product_match_confirmed",actor:"Merchant",detail:{item_id:itemId,product_id:product.id,query:search}});return{item,ready};}
export async function previewImageJob(accountId:string,headers:Headers,jobId:string){const {data:job,error}=await (supabaseAdmin.from("ps_product_image_jobs") as any).select("*,ps_product_image_items(*)").eq("account_id",accountId).eq("id",jobId).maybeSingle();if(error||!job)throw new Error("Image job not found.");const items=job.ps_product_image_items as Obj[];if(!items.length||items.some(item=>item.match_status!=="confirmed"||!item.product_id))throw new Error("Every image must have one confirmed product match before approval.");const grouped=new Map<string,Obj[]>();for(const item of items){const id=String(item.product_id);if(!grouped.has(id))grouped.set(id,[]);grouped.get(id)!.push(item);}const snapshots:Obj[]=[];for(const [productId,productItems]of grouped)snapshots.push({product_id:productId,before_gallery:await gallery(headers,productId),item_ids:productItems.map(item=>item.id)});for(const snap of snapshots)await (supabaseAdmin.from("ps_product_image_items") as any).update({before_gallery:snap.before_gallery}).in("id",snap.item_ids as string[]);await (supabaseAdmin.from("ps_product_image_jobs") as any).update({status:"waiting_approval"}).eq("id",jobId);await moveTask(accountId,job.manager_task_id,"waiting_approval","Image matches and the current product galleries were captured for merchant approval.");const approval=token({v:1,account_id:accountId,job_id:jobId,snapshots:snapshots.map(s=>({product_id:s.product_id,image_ids:(s.before_gallery as Obj[]).map(image=>String(image.id??""))})),expires_at:Date.now()+15*60_000});return{job:{...job,status:"waiting_approval",ps_product_image_items:items},approval_token:approval,expires_at:new Date(Date.now()+15*60_000).toISOString(),snapshots};}
export async function applyImageJob(accountId:string,headers:Headers,approvalToken:string){const approval=decode(approvalToken,accountId),jobId=String(approval.job_id),{data:job}=await (supabaseAdmin.from("ps_product_image_jobs") as any).select("*,ps_product_image_items(*)").eq("account_id",accountId).eq("id",jobId).maybeSingle();if(!job||job.status!=="waiting_approval")throw new Error("This image job is no longer waiting for approval.");const items=job.ps_product_image_items as Obj[],snapshots=approval.snapshots as Obj[];for(const snap of snapshots){const live=(await gallery(headers,String(snap.product_id))).map(image=>String(image.id??""));if(JSON.stringify(live)!==JSON.stringify(snap.image_ids))throw new Error("A product gallery changed after preview. Preview the job again.");}
  await moveTask(accountId,job.manager_task_id,"approved","Merchant approved the exact image batch.");await moveTask(accountId,job.manager_task_id,"executing","Uploading approved images to the connected store.");await (supabaseAdmin.from("ps_product_image_jobs") as any).update({status:"executing",approved_by:"Merchant",approved_at:new Date().toISOString()}).eq("id",jobId);const results:Obj[]=[];for(const item of items){const productId=String(item.product_id),before=await gallery(headers,productId),beforeIds=new Set(before.map(image=>String(image.id??""))),download=await supabaseAdmin.storage.from(BUCKET).download(String(item.storage_path));if(download.error)throw download.error;const form=new FormData();form.set("image",download.data,String(item.file_name));form.set("alt_text",String(item.alt_text??item.product_name??"Product image"));const call=await zid(`https://api.zid.sa/v1/products/${encodeURIComponent(productId)}/images/`,headers,{method:"POST",body:form});let live:Obj[]=[],newImages:Obj[]=[];if(call.response.ok){for(let attempt=0;attempt<4;attempt++){if(attempt)await new Promise(resolve=>setTimeout(resolve,500));live=await gallery(headers,productId);newImages=live.filter(image=>!beforeIds.has(String(image.id??"")));if(newImages.length)break;}}const responseData=call.payload.data as Obj|undefined,responseImage=call.payload.image as Obj|undefined,responseId=String(call.payload.id??responseData?.id??responseImage?.id??""),imageId=responseId&&live.some(image=>String(image.id??"")===responseId)?responseId:newImages.length===1?String(newImages[0].id??""):"",confirmed=Boolean(call.response.ok&&imageId&&live.some(image=>String(image.id??"")===imageId));const result={item_id:item.id,product_id:item.product_id,image_id:imageId,status:confirmed?"confirmed":"unconfirmed",http_status:call.response.status,new_images_found:newImages.length};results.push(result);await (supabaseAdmin.from("ps_product_image_items") as any).update({uploaded_image_id:imageId||null,result}).eq("id",item.id);}
  await moveTask(accountId,job.manager_task_id,"verifying","Reading the live galleries back from the connected store.");const confirmed=results.every(result=>result.status==="confirmed"),rejected=results.every(result=>Number(result.http_status)>=400),status=confirmed?"completed":"partial";await (supabaseAdmin.from("ps_product_image_jobs") as any).update({status}).eq("id",jobId);await moveTask(accountId,job.manager_task_id,confirmed?"completed":"needs_attention",confirmed?"Every uploaded image was found in the live product gallery.":"At least one upload could not be confirmed in the live gallery.");await (supabaseAdmin.from("ps_product_image_events") as any).insert({account_id:accountId,job_id:jobId,event_type:"execution_verified",actor:"PrizeSkout",detail:{status,results}});return{ok:confirmed,confirmed,status,results,message:confirmed?`${results.length} image${results.length===1?"":"s"} uploaded and confirmed in the connected store.`:rejected?"The connected store rejected the image upload. No image was added.":"The store accepted some images, but every upload could not be confirmed."};}
export async function rollbackImageJob(accountId:string,headers:Headers,jobId:string){const {data:job}=await (supabaseAdmin.from("ps_product_image_jobs") as any).select("*,ps_product_image_items(*)").eq("account_id",accountId).eq("id",jobId).maybeSingle();if(!job||!["completed","partial"].includes(job.status))throw new Error("Only a completed image job can be rolled back.");const results:Obj[]=[];for(const item of job.ps_product_image_items as Obj[]){if(!item.uploaded_image_id)continue;const urls=[`https://api.zid.sa/v1/products/${encodeURIComponent(String(item.product_id))}/images/${encodeURIComponent(String(item.uploaded_image_id))}/`,`https://api.zid.sa/v1/products/${encodeURIComponent(String(item.product_id))}/images/${encodeURIComponent(String(item.uploaded_image_id))}`];let response:Response|null=null;for(const url of urls){response=await fetch(url,{method:"DELETE",headers});if(response.ok||response.status===404)break;}const live=await gallery(headers,String(item.product_id)),removed=!live.some(image=>String(image.id??"")===String(item.uploaded_image_id));results.push({item_id:item.id,image_id:item.uploaded_image_id,removed,http_status:response?.status});}const confirmed=results.every(result=>result.removed);await (supabaseAdmin.from("ps_product_image_jobs") as any).update({status:confirmed?"rolled_back":"needs_attention"}).eq("id",jobId);await (supabaseAdmin.from("ps_product_image_events") as any).insert({account_id:accountId,job_id:jobId,event_type:"rollback",actor:"Merchant",detail:{confirmed,results}});return{ok:confirmed,confirmed,results,message:confirmed?"Uploaded images were removed and the original gallery was preserved.":"Rollback needs attention; not every uploaded image could be confirmed as removed."};}
