import {supabaseAdmin} from "@/integrations/supabase/client.server";
export type PromotionActionType="stop"|"reduce_discount"|"remove_item"|"adjust_discount";
const table=()=>(supabaseAdmin as any).from("ps_promotion_actions");
export async function listPromotionActions(accountId:string){const {data,error}=await table().select("*").eq("account_id",accountId).order("created_at",{ascending:false}).limit(200);if(error)throw error;return data??[]}
export async function createPromotionAction(input:{accountId:string;scenarioId:string;platform:string;actionType:PromotionActionType;targetReference:string;payload:Record<string,unknown>;requestedBy:string}){const {data:scenario,error:scenarioError}=await (supabaseAdmin as any).from("ps_promotion_scenarios").select("id,status,platform").eq("account_id",input.accountId).eq("id",input.scenarioId).maybeSingle();if(scenarioError||!scenario)throw new Error("Promotion scenario was not found.");if(!["approved","ready_to_launch","running"].includes(scenario.status))throw new Error("Approve the promotion scenario before proposing a platform change.");if(input.platform!==scenario.platform&&!String((input.payload.channels as string[]|undefined)??[]).includes(input.platform))throw new Error("The action platform is not part of this approved scenario.");const {data,error}=await table().insert({account_id:input.accountId,scenario_id:input.scenarioId,platform:input.platform,action_type:input.actionType,target_reference:input.targetReference,requested_payload:input.payload,status:"pending_approval",requested_by:input.requestedBy}).select("*").single();if(error)throw error;return data}
export async function approvePromotionAction(accountId:string,id:string,reviewer:string,decision:"approved"|"rejected"){const {data:current,error:readError}=await table().select("*").eq("account_id",accountId).eq("id",id).maybeSingle();if(readError||!current)throw new Error("Promotion action was not found.");if(current.status!=="pending_approval")throw new Error("Only a pending promotion action can be decided.");if(current.requested_by.trim().toLowerCase()===reviewer.trim().toLowerCase())throw new Error("The requester cannot approve the same external promotion action.");const {data,error}=await table().update({status:decision,approved_by:reviewer,approved_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("account_id",accountId).eq("id",id).select("*").single();if(error)throw error;return data}
export async function queuePromotionAction(accountId:string,id:string){const {data:current,error:readError}=await table().select("*").eq("account_id",accountId).eq("id",id).maybeSingle();if(readError||!current)throw new Error("Promotion action was not found.");if(current.status!=="approved"||!current.approved_at)throw new Error("Explicit approval is required before execution.");const {data:channel}=await supabaseAdmin.from("ps_merchant_channels").select("status").eq("account_id",accountId).eq("platform",current.platform).maybeSingle();const deliveryMode=channel?.status==="connected"?"partner_pull":"manual";const {data,error}=await table().update({status:"awaiting_partner",delivery_mode:deliveryMode,updated_at:new Date().toISOString()}).eq("account_id",accountId).eq("id",id).select("*").single();if(error)throw error;return data}
export async function listPendingPartnerPromotionActions(accountId:string,platform:string){const {data,error}=await table().select("id,scenario_id,platform,action_type,target_reference,requested_payload,approved_at,created_at").eq("account_id",accountId).eq("platform",platform).eq("status","awaiting_partner").eq("delivery_mode","partner_pull").order("created_at").limit(100);if(error)throw error;return data??[]}
export async function confirmPromotionAction(accountId:string,id:string,partnerReference:string,result:Record<string,unknown>){const {data:current,error:readError}=await table().select("status").eq("account_id",accountId).eq("id",id).maybeSingle();if(readError||!current)throw new Error("Promotion action was not found.");if(current.status!=="awaiting_partner")throw new Error("Only an action awaiting execution can be confirmed.");const {data,error}=await table().update({status:"confirmed",partner_reference:partnerReference,result_payload:result,confirmed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("account_id",accountId).eq("id",id).select("*").single();if(error)throw error;return data}
