export type ManagerPlaybook={id:string;title:string;signals:string[];capabilities:string[];outcome:string};
export const STORE_MANAGER_PLAYBOOKS:ManagerPlaybook[]=[
  {id:"new_product_onboarding",title:"New-product onboarding",signals:["new supplier","new products","onboard products","supplier spreadsheet"],capabilities:["catalog.sync","catalog.inspect","product.create","product.edit","pricing.preview","product.publish"],outcome:"Complete, profitable products prepared and published only after approval."},
  {id:"catalogue_cleanup",title:"Catalogue cleanup",signals:["clean catalogue","missing information","duplicate sku","bad images"],capabilities:["catalog.sync","catalog.inspect","product.edit"],outcome:"Catalogue issues resolved and confirmed by platform readback."},
  {id:"margin_recovery",title:"Margin recovery",signals:["protect margin","losing money","below margin","reprice"],capabilities:["catalog.sync","pricing.preview","pricing.publish"],outcome:"Verified-cost products restored within the active margin policy."},
  {id:"stock_response",title:"Stock response",signals:["low stock","out of stock","slow stock","dead stock"],capabilities:["inventory.inspect","inventory.update","promotion.analyse"],outcome:"Stock exceptions prepared or corrected without overselling."},
  {id:"campaign_control",title:"Campaign preparation and control",signals:["campaign","promotion","coupon","discount"],capabilities:["promotion.analyse","pricing.preview","promotion.launch","payout.audit"],outcome:"Campaign economics reviewed, launch recorded and promised funding checked."},
  {id:"payout_recovery",title:"Payout audit and recovery",signals:["payout","commission","missing money","recovery","dispute"],capabilities:["payout.audit","dispute.submit"],outcome:"Discrepancy evidenced, approved and tracked through recovery."},
  {id:"salla_order_reconciliation",title:"Salla order reconciliation",signals:["reconcile salla orders","order mismatch","invoice mismatch","payment mismatch","refund mismatch"],capabilities:["orders.inspect","orders.reconcile","shipping.inspect","report.prepare"],outcome:"Orders, collections, refunds, invoices and shipment evidence reconciled with financial exceptions queued for review."},
  {id:"daily_store_health",title:"Daily store health check",signals:["manage my store","what needs attention","daily brief","store health"],capabilities:["catalog.inspect","inventory.inspect","orders.inspect","pricing.preview","payout.audit","competitor.monitor","report.prepare"],outcome:"Prioritized store brief with connected actions and explicit exceptions."},
];
