import { useState } from "react";
import { Bot, Check, Clipboard, Download, FileJson, LoaderCircle, Send } from "lucide-react";
import { SettingsTabs } from "@/components/dashboard/settings/SettingsTabs";
import { DashboardV2Shell } from "./DashboardV2Shell";
import { buildDashboardV2ChromeData } from "./dashboard-v2-chrome";
import { useDashboardV2Activity } from "./useDashboardV2Activity";
import { useDashboardV2Context } from "./useDashboardV2Context";
import { useDashboardV2Summary } from "./useDashboardV2Summary";
import type { DashboardV2WorkspaceId } from "./DashboardV2Workspace";

const money = (value: number | null | undefined, currency: string | null | undefined) => value == null ? "Not calculated" : `${currency ?? ""} ${new Intl.NumberFormat(undefined, { maximumFractionDigits: 2 }).format(value)}`.trim();
const text = (value: unknown, fallback = "—") => typeof value === "string" && value.trim() ? value : fallback;
const date = (value: unknown) => typeof value === "string" ? new Date(value).toLocaleString() : "—";

function download(filename: string, body: string, type: string) {
  const url = URL.createObjectURL(new Blob([body], { type }));
  const anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.click();
  setTimeout(() => URL.revokeObjectURL(url), 2000);
}

function Copilot() {
  const context = useDashboardV2Context();
  const [prompt, setPrompt] = useState("");
  const [messages, setMessages] = useState<Array<{ role: "user" | "assistant"; text: string }>>([]);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  async function ask(value = prompt) {
    const question = value.trim(); if (!question || busy) return;
    const merchantId = localStorage.getItem("ps_merchant_id") ?? "", accessCode = localStorage.getItem("ps_access_code") ?? "";
    setMessages((rows) => [...rows, { role: "user", text: question }]); setPrompt(""); setBusy(true); setError(null);
    try {
      const response = await fetch("/api/copilot/compile", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ prompt: question, requested_role: "cfo", merchant_id: merchantId, access_code: accessCode, context: { current_page: "dashboard/ai-copilot", currency: context?.currency, connected_channels: context?.channels, conversation: messages.slice(-8) } }) });
      const body = await response.json(); if (!response.ok) throw new Error(body.error || "Copilot could not answer.");
      setMessages((rows) => [...rows, { role: "assistant", text: body.message || "No evidence-backed answer was returned." }]);
    } catch (reason) { setError(reason instanceof Error ? reason.message : "Copilot could not answer."); } finally { setBusy(false); }
  }
  return <><section className="ps-v2-card ps-v2-module-card"><header><div><h2>Evidence-backed conversation</h2><p>Answers use retained PrizeSkout evidence; no external action is executed from this chat.</p></div><span className="ps-v2-readonly"><Bot size={13}/> CFO Copilot</span></header><div className="ps-v2-copilot-thread" aria-live="polite">{messages.length ? messages.map((message, index) => <article key={index} data-role={message.role}><strong>{message.role === "user" ? "You" : "PrizeSkout"}</strong><p>{message.text}</p></article>) : <div className="ps-v2-empty-workspace"><Bot size={28}/><strong>Ask a financial question</strong><p>Try “What evidence is missing?” or “Which channel needs attention?”</p></div>}{busy && <p><LoaderCircle className="ps-v2-spin" size={16}/> Reviewing retained evidence…</p>}</div>{error && <p className="ps-v2-form-error" role="alert">{error}</p>}<form className="ps-v2-copilot-form" onSubmit={(event) => { event.preventDefault(); void ask(); }}><label htmlFor="v2-copilot-prompt">Question</label><textarea id="v2-copilot-prompt" value={prompt} onChange={(event) => setPrompt(event.target.value)} maxLength={2000} placeholder="Ask about profit, payouts, fees, trends, or missing evidence"/><button className="ps-v2-action" disabled={!prompt.trim() || busy}><Send size={14}/> Ask Copilot</button></form></section></>;
}

function Reports({ summary }: { summary: ReturnType<typeof useDashboardV2Summary>["summary"] }) {
  const disabled = !summary;
  const exportJson = () => summary && download(`prizeskout-report-${new Date().toISOString().slice(0,10)}.json`, JSON.stringify(summary, null, 2), "application/json");
  const exportCsv = () => summary && download(`prizeskout-report-${new Date().toISOString().slice(0,10)}.csv`, ["metric,value,currency", `gross_sales,${summary.metrics.gross_sales ?? ""},${summary.metrics.currency ?? ""}`, `net_revenue,${summary.metrics.net_revenue ?? ""},${summary.metrics.currency ?? ""}`, `orders,${summary.metrics.orders ?? ""},`, `true_contribution,${summary.metrics.true_contribution ?? ""},${summary.metrics.currency ?? ""}`, `settlement_variance,${summary.metrics.settlement_variance ?? ""},${summary.metrics.currency ?? ""}`].join("\n"), "text/csv");
  return <section className="ps-v2-card ps-v2-module-card"><header><div><h2>Financial report</h2><p>Exports preserve the current evidence state, period, currency, and unavailable values.</p></div></header><div className="ps-v2-report-actions"><button className="ps-v2-action" disabled={disabled} onClick={exportCsv}><Download size={14}/> Download CSV</button><button className="ps-v2-action" disabled={disabled} onClick={exportJson}><FileJson size={14}/> Download evidence JSON</button></div><div className="ps-v2-placeholder-table"><div><span>Metric</span><span>Value</span><span>Evidence state</span><span>Period</span></div>{[["Gross sales", money(summary?.metrics.gross_sales, summary?.metrics.currency)], ["Net revenue", money(summary?.metrics.net_revenue, summary?.metrics.currency)], ["Orders", summary?.metrics.orders ?? "Not calculated"], ["Contribution", money(summary?.metrics.true_contribution, summary?.metrics.currency)], ["Settlement variance", money(summary?.metrics.settlement_variance, summary?.metrics.currency)]].map(([label,value])=><div key={String(label)}><span>{label}</span><span>{value}</span><span>{summary?.metrics.state ?? "unavailable"}</span><span>{summary ? `${summary.scope.days} days` : "—"}</span></div>)}</div></section>;
}

export function DashboardV2ProductWorkspace({ workspace }: { workspace: DashboardV2WorkspaceId }) {
  const load = useDashboardV2Summary(), summary = load.summary, context = useDashboardV2Context(), activity = useDashboardV2Activity();
  const chrome = buildDashboardV2ChromeData(summary);
  const configs: Partial<Record<DashboardV2WorkspaceId, [string,string]>> = { "ai-copilot": ["AI Copilot", "Ask from the governed financial workspace."], "profit-intelligence": ["Profit intelligence", "Understand revenue, cost coverage, and contribution without invented economics."], "menu-intelligence": ["Menu intelligence", "Review retained SKU cost evidence and its effective dates."], channels: ["Channels", "Manage connected commerce channels and evidence readiness."], settlements: ["Settlements", "Review the latest retained reconciliation conclusion."], reports: ["Reports", "Export the current governed financial view."], integrations: ["Integrations", "Connect and manage merchant-authorized sources."], "api-developers": ["API & Developers", "Use the documented, governed PrizeSkout API."], settings: ["Settings", "Manage merchant workspace preferences and protection controls."], "store-access": ["Store access", "Manage the private code used to restore this merchant workspace."], "audit-log": ["Audit log", "Inspect immutable governed events and provenance."] };
  const [label, title] = configs[workspace] ?? [workspace, workspace];
  const auditRows = activity.data?.audit.rows ?? [], channelRows = activity.data?.channels.rows ?? [], costRows = activity.data?.costs.rows ?? [];
  return <DashboardV2Shell activePage={workspace} chromeData={chrome}><div className="ps-v2-page-heading"><div><p className="ps-v2-eyebrow">Workspace / {label}</p><h1>{title}</h1></div></div>
    {workspace === "ai-copilot" && <Copilot />}
    {workspace === "settings" && <section className="ps-v2-card ps-v2-module-card"><SettingsTabs initialTab="Margin Rules" /></section>}
    {workspace === "store-access" && <section className="ps-v2-card ps-v2-module-card"><SettingsTabs initialTab="Store Access" /></section>}
    {(workspace === "integrations" || workspace === "channels") && <><section className="ps-v2-card ps-v2-module-card"><SettingsTabs initialTab="Channels" /></section><section className="ps-v2-card ps-v2-module-card"><header><div><h2>Retained connection status</h2><p>Server-owned channel records for this merchant.</p></div></header><div className="ps-v2-placeholder-table"><div><span>Platform</span><span>Status</span><span>Last verified</span><span>Issue</span></div>{channelRows.length ? channelRows.map((row)=><div key={String(row.id)}><span>{text(row.platform)}</span><span>{text(row.status)}</span><span>{date(row.last_verified_at ?? row.updated_at)}</span><span>{text(row.error_message, "None recorded")}</span></div>) : <div><span>No retained connections</span><span>{activity.loading ? "Loading" : activity.data?.channels.state ?? "Unavailable"}</span><span>—</span><span>{activity.error ?? activity.data?.channels.blocker ?? "Connect a supported channel above"}</span></div>}</div></section></>}
    {workspace === "reports" && <Reports summary={summary} />}
    {workspace === "profit-intelligence" && <section className="ps-v2-card ps-v2-module-card"><header><div><h2>Profit evidence</h2><p>Contribution unlocks only with complete order-level product costs.</p></div></header><div className="ps-v2-metric-grid"><div><span>Gross sales</span><strong>{money(summary?.metrics.gross_sales,summary?.metrics.currency)}</strong></div><div><span>Net revenue</span><strong>{money(summary?.metrics.net_revenue,summary?.metrics.currency)}</strong></div><div><span>Product-cost coverage</span><strong>{summary ? `${summary.metrics.cost_coverage.pct}%` : "—"}</strong></div><div><span>True contribution</span><strong>{money(summary?.metrics.true_contribution,summary?.metrics.currency)}</strong></div><div><span>Margin</span><strong>{summary?.metrics.contribution_margin_pct == null ? "Not calculated" : `${summary.metrics.contribution_margin_pct}%`}</strong></div><div><span>Currency</span><strong>{summary?.metrics.currency ?? context?.currency ?? "—"}</strong></div></div></section>}
    {workspace === "menu-intelligence" && <section className="ps-v2-card ps-v2-module-card"><header><div><h2>Retained product-cost evidence</h2><p>Effective-dated cost evidence; no SKU is ranked without complete economics.</p></div></header><div className="ps-v2-placeholder-table"><div><span>SKU</span><span>Unit cost</span><span>Source</span><span>Effective from</span></div>{costRows.length ? costRows.map((row)=><div key={String(row.id)}><span>{text(row.sku)}</span><span>{money(Number(row.unit_cost), text(row.currency, ""))}</span><span>{text(row.source_provider)}</span><span>{date(row.effective_from ?? row.created_at)}</span></div>) : <div><span>No retained SKU costs</span><span>—</span><span>{activity.data?.costs.state ?? (activity.loading ? "Loading" : "Unavailable")}</span><span>{activity.error ?? activity.data?.costs.blocker ?? "Add product cost evidence"}</span></div>}</div></section>}
    {workspace === "settlements" && <section className="ps-v2-card ps-v2-module-card"><header><div><h2>Latest reconciliation finding</h2><p>Order allocation, statement truth, and receipt confirmation remain separate.</p></div></header>{summary?.reconciliation ? <div className="ps-v2-placeholder-table"><div><span>Conclusion</span><span>Expected</span><span>Reported</span><span>Variance / allocation</span></div><div><span>{summary.reconciliation.label}</span><span>{money(summary.reconciliation.expected_amount,summary.reconciliation.currency)}</span><span>{money(summary.reconciliation.reported_amount,summary.reconciliation.currency)}</span><span>{money(summary.reconciliation.variance,summary.reconciliation.currency)} · {summary.reconciliation.allocation_scope}</span></div></div> : <div className="ps-v2-empty-workspace"><strong>No retained settlement finding</strong><p>Add approved payout evidence before PrizeSkout calculates a difference.</p></div>}</section>}
    {workspace === "audit-log" && <section className="ps-v2-card ps-v2-module-card"><header><div><h2>Governed event history</h2><p>Immutable merchant-scoped records with trace and payload hashes.</p></div><span className="ps-v2-readonly"><Check size={13}/> Append-only</span></header><div className="ps-v2-placeholder-table"><div><span>Event</span><span>Summary</span><span>Source / target</span><span>Recorded</span></div>{auditRows.length ? auditRows.map((row)=><div key={String(row.id)}><span>{text(row.event_type)}</span><span>{text(row.summary_en)}</span><span>{text(row.source_platform)} / {text(row.target_channel)}</span><span>{date(row.created_at)}</span></div>) : <div><span>No governed events</span><span>{activity.error ?? activity.data?.audit.blocker ?? "No event has been retained for this merchant"}</span><span>—</span><span>{activity.loading ? "Loading" : "—"}</span></div>}</div></section>}
    {workspace === "api-developers" && <section className="ps-v2-card ps-v2-module-card"><header><div><h2>Developer contract</h2><p>Use test-mode endpoints before requesting approved live access.</p></div><a className="ps-v2-action" href="/docs">Open API reference</a></header><div className="ps-v2-api-example"><code>POST https://prizeskout.qa/v1/margin</code><button type="button" onClick={() => void navigator.clipboard.writeText("POST https://prizeskout.qa/v1/margin")}><Clipboard size={14}/> Copy</button></div><p>API-key creation remains in the authenticated developer console and is never performed automatically from merchant evidence context.</p></section>}
  </DashboardV2Shell>;
}
