import { Bot, Radio, ShieldAlert } from "lucide-react";
import { DashboardV2Shell } from "./DashboardV2Shell";
import { useDashboardV2Modules } from "./useDashboardV2Modules";
import { useDashboardV2Summary } from "./useDashboardV2Summary";
import { buildDashboardV2ChromeData } from "./dashboard-v2-chrome";

const stages = ["Incoming", "Validation", "Availability check", "Automation rule", "Accepted", "POS sync"];

export function DashboardV2OrderAutomation() {
  const { order } = useDashboardV2Modules();
  const summary = useDashboardV2Summary().summary;
  const hasOrders = Boolean(order?.orders.length);
  return <DashboardV2Shell activePage="automation" chromeData={buildDashboardV2ChromeData(summary)}>
    <div className="ps-v2-page-heading"><div><p className="ps-v2-eyebrow">Operations / Order Automation</p><h1>Automation performance is not calculated. <span className="ps-v2-muted">Order Guard must be provisioned before live order decisions appear.</span></h1></div><div className="ps-v2-status-actions"><button className="ps-v2-action" disabled>Branch override</button><button className="ps-v2-action" disabled>New rule</button></div></div>

    <section className="ps-v2-hero" aria-label="Automation summary"><div className="ps-v2-hero-main"><span className="ps-v2-label">Automation rate</span><h2 className="ps-v2-dominant-metric">Not calculated</h2><p>{order?.blockers[0] ?? "No live or retained order-automation evidence is available in this session."}</p><div className="ps-v2-outcome-bar" aria-label="Automation outcomes unavailable"><span /><span /><span /><span /></div><span className="ps-v2-evidence-reference">SOURCE · ORDER_GUARD · {order?.state.toUpperCase() ?? "UNAVAILABLE"}</span></div><div className="ps-v2-metric-grid"><div><span>Orders received</span><strong>{order ? order.received : "—"}</strong></div><div><span>Live orders</span><strong>{order ? order.live : "—"}</strong></div><div><span>Need attention</span><strong>{order ? order.attention : "—"}</strong></div><div><span>Critical</span><strong>{order ? order.critical : "—"}</strong></div><div data-tone="risk"><span>SLA breaches</span><strong>—</strong></div><div data-tone="brand"><span>Revenue protected</span><strong>—</strong><small>Not inferred from retained orders</small></div></div></section>

    <section className="ps-v2-card ps-v2-module-card ps-v2-flow-card"><header><div><h2>Order flow monitor</h2><p>Merchant-scoped stages from receipt through POS confirmation</p></div><span className="ps-v2-readonly"><Radio size={12} /> {hasOrders ? "Retained" : "Offline"}</span></header><ol className="ps-v2-flow-stages">{stages.map((stage, index) => <li key={stage}><span>{index + 1}</span><strong>{stage}</strong><small>{index === 0 && order ? order.received : "Not proven"}</small></li>)}</ol><div className="ps-v2-dashboard-row ps-v2-order-monitor"><section className="ps-v2-inset-panel"><div className="ps-v2-section-heading"><div><h3>Retained orders</h3><p>Latest merchant-scoped source events</p></div><span className="ps-v2-evidence-reference">Validation → POS sync</span></div>{hasOrders ? <div className="ps-v2-retained-list">{order!.orders.slice(0, 7).map((row) => <div key={row.id}><time>{new Date(row.placed_at).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</time><span>{row.channel?.slice(0, 1) ?? "?"}</span><p><strong>#{row.external_order_id}</strong><small>{row.branch ?? "Unassigned"} · {row.status.replaceAll("_", " ")}</small></p><b>{row.order_total == null ? "—" : `${row.currency} ${row.order_total.toLocaleString()}`}</b></div>)}</div> : <Unavailable title="Live order flow is unavailable" detail="No synthetic feed is shown as live commerce truth." />}</section><section className="ps-v2-inset-panel"><div className="ps-v2-section-heading"><div><h3>Exceptions</h3><p>Orders requiring attention</p></div><span className="ps-v2-evidence-reference">Feeds Priority Centre</span></div>{order?.attention ? <div className="ps-v2-exception-list">{order.orders.filter((row) => ["attention", "manager", "critical"].includes(row.risk_level)).map((row) => <article key={row.id}><header><strong>{row.channel ?? "Channel"} order #{row.external_order_id}</strong><span>{row.branch ?? "Unassigned"}</span></header><b>{row.status.replaceAll("_", " ")}</b><p>Retained risk state: {row.risk_level}. Review the source evidence before any action.</p><button type="button" disabled>Review</button></article>)}</div> : <Unavailable title="No retained exceptions" detail="No attributable order currently carries an attention risk state." />}</section></div></section>

    <div className="ps-v2-dashboard-row"><section className="ps-v2-card ps-v2-module-card"><header><div><h2>Automation by branch</h2><p>Retained volume and risk; automation rate remains unproven</p></div></header><div className="ps-v2-placeholder-table ps-v2-automation-table"><div><span>Branch</span><span>Orders</span><span>Live</span><span>Attention</span><span>Critical</span></div>{order?.branches.length ? order.branches.map((row) => <div key={row.branch}><span>{row.branch}</span><span>{row.received}</span><span>{row.live}</span><span>{row.attention}</span><span>{row.critical}</span></div>) : <div><span>No verified branch automation data</span><span>—</span><span>—</span><span>—</span><span>—</span></div>}</div></section><section className="ps-v2-card ps-v2-module-card ps-v2-ai-card"><header><div><h2>Ask Copilot</h2><p>Evidence-backed order analysis</p></div></header><div className="ps-v2-question-chips"><button disabled>Why are orders manual?</button><button disabled>Where are SLA breaches?</button><button disabled>What should I automate?</button></div><Unavailable dark title="Copilot is waiting for evidence" detail="Answers remain unavailable until order events and rule outcomes can be cited." /></section></div>

    <section id="rules" className="ps-v2-card ps-v2-module-card ps-v2-rules"><header><div><h2>Order rules</h2><p>Rules run top to bottom; the first verified match wins.</p></div><button className="ps-v2-action" disabled>+ New rule</button></header><div className="ps-v2-placeholder-table ps-v2-rules-table"><div><span># / Rule</span><span>Status</span><span>Platforms</span><span>Branches</span><span>Triggers 30d / Success</span></div>{Array.from({ length: 6 }, (_, index) => <div className="ps-v2-empty-rule-row" key={index}><span>{index === 0 ? "No governed rules available" : "Rule slot unavailable"}</span><span>—</span><span>—</span><span>—</span><span>—</span></div>)}</div><div className="ps-v2-rule-editing-heading"><span>Editing rule</span><strong>No governed rule selected</strong><button type="button" disabled>Test on last 30 days</button></div><div className="ps-v2-rule-editor" aria-label="Disabled rule editor"><div><span className="ps-v2-label">Trigger</span><strong>New order received</strong><small>Platform and branch scope unavailable</small></div><b>→</b><div><span className="ps-v2-label">When</span><strong>Verified conditions</strong><small>Conditions require retained sources</small><div className="ps-v2-rule-chips"><span>Platform</span><span>Branch</span><span>Day</span><span>Time</span><span>Order value</span><span>SKU</span><span>Inventory</span><span>POS status</span></div></div><b>→</b><div><span className="ps-v2-label">Then</span><strong>Protected action</strong><small>Merchant approval required</small><div className="ps-v2-rule-chips"><span>Auto accept</span><span>Manual review</span><span>Reject</span><span>Notify manager</span><span>Sync POS</span></div></div></div><div className="ps-v2-rule-note"><ShieldAlert size={16} /><span><strong>Rule editing is safely disabled.</strong> Enable it only after migration verification, role checks, backtesting, and merchant approval controls are active.</span><button className="ps-v2-action" disabled>Save rule</button></div></section>
  </DashboardV2Shell>;
}

function Unavailable({ title, detail, dark = false }: { title: string; detail: string; dark?: boolean }) {
  return <div className="ps-v2-unavailable">{dark ? <Bot size={24} aria-hidden="true" /> : <ShieldAlert size={24} aria-hidden="true" />}<div><strong>{title}</strong><p>{detail}</p></div></div>;
}
