import { Bot, ChartNoAxesCombined, Code2, FileCheck2, History, PackageCheck, PlugZap, ReceiptText, Settings, ShieldCheck, Users } from "lucide-react";
import { DashboardV2Shell, EvidenceStateCard, type DashboardV2Page } from "./DashboardV2Shell";
import { buildDashboardV2ChromeData } from "./dashboard-v2-chrome";
import { useDashboardV2Context } from "./useDashboardV2Context";
import { useDashboardV2Summary } from "./useDashboardV2Summary";

export type DashboardV2WorkspaceId = Exclude<DashboardV2Page, "overview" | "priority" | "automation" | "promotions">;

const WORKSPACES: Record<DashboardV2WorkspaceId, { eyebrow: string; title: string; description: string; boundary: string; icon: typeof Bot }> = {
  "ai-copilot": { eyebrow: "Intelligence / AI Copilot", title: "Ask from the governed financial workspace.", description: "Copilot context stays attached to the same merchant, period, evidence confidence, and priority queue as the rest of Dashboard V2.", boundary: "Protected tasks still require merchant approval and a verified connector readback.", icon: Bot },
  "profit-intelligence": { eyebrow: "Intelligence / Profit intelligence", title: "Profit conclusions remain evidence-gated.", description: "Revenue, contribution, cost coverage, and margin use the same server-owned Economic Twin as Executive Overview.", boundary: "Contribution stays Not calculated whenever product-cost coverage is incomplete.", icon: ChartNoAxesCombined },
  "menu-intelligence": { eyebrow: "Intelligence / Menu intelligence", title: "Menu decisions start with retained cost evidence.", description: "This workspace keeps catalogue scope, product-cost coverage, channel terms, and decision readiness separate.", boundary: "No SKU is ranked or repriced from missing cost or channel-term evidence.", icon: PackageCheck },
  channels: { eyebrow: "Commercial / Channels", title: "Channel scope stays merchant-controlled.", description: "Connected-channel labels come from the authenticated merchant context rather than a browser-owned list.", boundary: "A connected status does not imply complete order, contract, payout, or receipt coverage.", icon: ShieldCheck },
  settlements: { eyebrow: "Finance / Settlements", title: "Settlement truth stays separate from bank receipt.", description: "Expected amount, platform-reported amount, allocation scope, and receipt confirmation remain distinct.", boundary: "Batch differences cannot become order claims without order-level evidence.", icon: ReceiptText },
  reports: { eyebrow: "Finance / Reports", title: "Reports inherit the current evidence boundary.", description: "Every report must preserve currency integrity, source provenance, effective dates, and unavailable states.", boundary: "Exports are not offered from this surface until the V2 report contract is implemented.", icon: FileCheck2 },
  integrations: { eyebrow: "Infrastructure / Integrations", title: "Evidence connections remain read-only here.", description: "The new workspace shows retained connection scope without falling back to the legacy dashboard shell.", boundary: "Connecting, refreshing, or changing credentials remains outside this read-only surface.", icon: PlugZap },
  "api-developers": { eyebrow: "Infrastructure / API & Developers", title: "The API contract remains explicit and test-safe.", description: "Developer access is separated from merchant financial truth and protected production actions.", boundary: "API keys, permissions, and production writes are not created from this dashboard surface.", icon: Code2 },
  settings: { eyebrow: "Account / Settings", title: "Settings stay within the new product shell.", description: "Merchant identity, reporting currency, scope, and evidence state are visible without entering the legacy dashboard.", boundary: "Editable account and connector controls require dedicated V2 contracts before they can be enabled.", icon: Settings },
  "store-access": { eyebrow: "Account / Store access", title: "Store access remains private and merchant-scoped.", description: "This surface confirms the authenticated workspace without exposing reusable access material in the page.", boundary: "Access-code reveal, rotation, and sharing are intentionally unavailable here.", icon: Users },
  "audit-log": { eyebrow: "Governance / Audit log", title: "Audit history stays evidence-linked.", description: "Priority findings retain immutable finding references, evidence strength, blockers, and safe next actions.", boundary: "No missing event or recovery case is reconstructed from browser state.", icon: History },
};

const money = (value: number | null | undefined, currency: string | null | undefined) => value == null ? "Not calculated" : `${currency ? `${currency} ` : ""}${new Intl.NumberFormat(undefined, { maximumFractionDigits: 2 }).format(value)}`;

export function DashboardV2Workspace({ workspace }: { workspace: DashboardV2WorkspaceId }) {
  const config = WORKSPACES[workspace];
  const load = useDashboardV2Summary();
  const summary = load.summary;
  const context = useDashboardV2Context();
  const Icon = config.icon;
  const truthCount = summary ? Object.values(summary.truths).filter((truth) => truth.status === "verified").length : 0;

  return <DashboardV2Shell activePage={workspace} chromeData={buildDashboardV2ChromeData(summary)}>
    <div className="ps-v2-page-heading"><div><p className="ps-v2-eyebrow">{config.eyebrow}</p><h1>{config.title} <span className="ps-v2-muted">{config.description}</span></h1></div><span className="ps-v2-readonly"><Icon size={13} aria-hidden="true" /> New workspace</span></div>

    <section className="ps-v2-hero" aria-label={`${config.title} summary`}><div className="ps-v2-hero-main"><span className="ps-v2-label">Current governed state</span><h2 className="ps-v2-dominant-metric">{load.phase === "ready" ? summary?.conclusion.title : load.phase === "loading" ? "Loading retained evidence" : "Evidence unavailable"}</h2><p>{load.phase === "ready" ? summary?.conclusion.detail : load.message ?? "The authenticated evidence contract is still loading."}</p><span className="ps-v2-evidence-reference">SOURCE · DASHBOARD_V2_SUMMARY · {load.phase.toUpperCase()}</span></div><div className="ps-v2-metric-grid"><div><span>Merchant</span><strong>{context?.merchant_label ?? "—"}</strong></div><div><span>Currency</span><strong>{context?.currency ?? "—"}</strong></div><div><span>Connected channels</span><strong>{context?.channels.length ?? "—"}</strong></div><div><span>Verified truths</span><strong>{summary ? `${truthCount}/4` : "—"}</strong></div><div><span>Orders</span><strong>{summary?.metrics.orders ?? "Not calculated"}</strong></div><div data-tone="brand"><span>Recoverable margin</span><strong>{money(summary?.metrics.recoverable_margin, summary?.metrics.currency)}</strong></div></div></section>

    <section className="ps-v2-card ps-v2-module-card"><header><div><h2>Evidence boundary</h2><p>This module stays in Dashboard V2 and shares its authenticated read-only contracts.</p></div><span className="ps-v2-readonly">No legacy fallback</span></header><div className="ps-v2-truth-grid"><EvidenceStateCard icon={Icon} label="Merchant scope" state={context?.state === "available" ? "verified" : context?.state === "partial" ? "partial" : "unavailable"} detail={context ? `${context.brand_label} · ${context.location_label} · ${context.channel_label}` : "Merchant scope has not loaded."} /><EvidenceStateCard icon={ShieldCheck} label="Financial evidence" state={summary?.conclusion.state === "ready_for_reconciliation" ? "verified" : summary ? "partial" : load.phase === "loading" ? "loading" : "unavailable"} detail={summary?.conclusion.next_action ?? "Financial evidence has not loaded."} /><EvidenceStateCard icon={FileCheck2} label="Safety boundary" state="partial" detail={config.boundary} /></div></section>

    <section className="ps-v2-card ps-v2-module-card"><header><div><h2>What is available now</h2><p>Only evidence-backed, read-only information is shown while native V2 workflows are completed.</p></div></header><div className="ps-v2-placeholder-table"><div><span>Area</span><span>State</span><span>Evidence</span><span>Next safe action</span></div><div><span>Shared merchant context</span><span>{context?.state ?? "loading"}</span><span>{context?.currency ?? "Not proven"}</span><span>{context?.blockers[0] ?? "Review retained scope"}</span></div><div><span>Financial summary</span><span>{summary?.metrics.state ?? load.phase}</span><span>{summary?.scope.days ? `${summary.scope.days} day window` : "Not loaded"}</span><span>{summary?.conclusion.next_action ?? "Load retained evidence"}</span></div><div><span>Protected actions</span><span>Disabled</span><span>Merchant approval required</span><span>Use a governed V2 workflow when available</span></div></div></section>
  </DashboardV2Shell>;
}

export const dashboardV2WorkspaceIds = Object.keys(WORKSPACES) as DashboardV2WorkspaceId[];
