import { Bot, ShieldAlert } from "lucide-react";
import { DashboardV2Shell } from "./DashboardV2Shell";
import { useDashboardV2Modules } from "./useDashboardV2Modules";

const simulatorFields = ["Platform", "Branches", "Menu items", "Discount", "Merchant-funded share", "Expected uplift", "Duration"];

export function DashboardV2Promotions() {
  const { promotions } = useDashboardV2Modules();
  const scenarios = promotions?.scenarios ?? [];
  return <DashboardV2Shell activePage="promotions">
    <div className="ps-v2-page-heading"><div><p className="ps-v2-eyebrow">Commercial / Promotions & Discounts</p><h1>Campaign contribution is not calculated. <span className="ps-v2-muted">Verified campaign terms, SKU costs, and attributable orders are required.</span></h1></div><div className="ps-v2-status-actions"><button className="ps-v2-action" disabled>Guardrails</button><button className="ps-v2-action" disabled>Simulate campaign</button></div></div>

    <section className="ps-v2-hero" aria-label="Promotion summary"><div className="ps-v2-hero-main"><span className="ps-v2-label">Incremental contribution</span><h2 className="ps-v2-dominant-metric">Not calculated</h2><p>{promotions?.blockers[0] ?? "PrizeSkout will not infer promotion profitability from catalog or batch totals."}</p><div className="ps-v2-funding-bar"><span /><i aria-label="50 percent guardrail" /></div><div className="ps-v2-funding-legend"><span>Merchant-funded —</span><span>Platform-funded —</span></div><span className="ps-v2-evidence-reference">SOURCE · PROMOTION_SCENARIOS · {promotions?.state.toUpperCase() ?? "UNAVAILABLE"}</span></div><div className="ps-v2-metric-grid"><div><span>Retained scenarios</span><strong>{promotions ? promotions.counts.total : "—"}</strong></div><div><span>Active</span><strong>{promotions ? promotions.counts.active : "—"}</strong></div><div><span>Pending approval</span><strong>{promotions ? promotions.counts.pending_approval : "—"}</strong></div><div><span>Completed</span><strong>{promotions ? promotions.counts.completed : "—"}</strong></div><div><span>Platform-funded</span><strong>—</strong></div><div data-tone="risk"><span>Campaigns at risk</span><strong>—</strong><small>Not inferred from scenarios</small></div></div></section>

    <section className="ps-v2-card ps-v2-module-card ps-v2-campaign-card"><header><div><h2>Campaigns</h2><p>Retained scenarios; financial outcomes require attributable evidence</p></div><div className="ps-v2-period"><button disabled className="active">All</button><button disabled>At risk</button><button disabled>Watch</button><button disabled>Healthy</button></div></header><div className="ps-v2-table-wrap ps-v2-campaign-table"><table className="ps-v2-channel-table"><thead><tr><th>Campaign</th><th>Platform</th><th>Status</th><th>Evidence</th><th>Funding</th><th>Orders</th><th>Revenue</th><th>Contribution</th><th>Margin</th><th>Health</th></tr></thead><tbody>{scenarios.length ? scenarios.map((row) => <tr key={row.id}><th scope="row">{row.name}</th><td>{row.platform}</td><td>{row.status.replaceAll("_", " ")}</td><td>{row.evidence_ready ? "Ready" : "Incomplete"}</td>{Array.from({ length: 6 }, (_, index) => <td key={index}>—</td>)}</tr>) : <tr><th scope="row">No verified campaigns in scope</th>{Array.from({ length: 9 }, (_, index) => <td key={index}>—</td>)}</tr>}</tbody></table></div><div className="ps-v2-health-panel"><div><span className="ps-v2-label">Campaign health</span><h3>{scenarios[0]?.name ?? "No campaign selected"}</h3><div className="ps-v2-health-score"><strong>—</strong><span>/ 100</span></div><div className="ps-v2-health-segments">{Array.from({ length: 10 }, (_, index) => <span key={index} />)}</div><small>Health requires attributable campaign evidence.</small></div><div><span className="ps-v2-label">Recommendations</span><label><input type="radio" disabled /> Evidence-backed recommendation unavailable</label><label><input type="radio" disabled /> Alternative scenario unavailable</label><div className="ps-v2-status-actions"><button className="ps-v2-action" disabled>Simulate</button><button className="ps-v2-action" disabled>Request approval</button></div></div></div></section>

    <section id="simulator" className="ps-v2-card ps-v2-module-card ps-v2-simulator"><header><div><h2>Promotion simulator</h2><p>Model a scenario without presenting it as a verified outcome.</p></div><span className="ps-v2-readonly">Scenario only</span></header><div className="ps-v2-dashboard-row"><div className="ps-v2-simulator-inputs"><span className="ps-v2-label">Inputs</span>{simulatorFields.map((field) => <label key={field}><span>{field}</span>{field === "Platform" ? <div className="ps-v2-period"><button disabled>Talabat</button><button disabled>Snoonu</button><button disabled>Keeta</button></div> : <input aria-label={field} disabled value="Evidence required" readOnly />}</label>)}</div><div className="ps-v2-simulator-output"><span className="ps-v2-label">Projected outcome</span><div className="ps-v2-verdict"><ShieldAlert size={18} /><div><strong>Simulation unavailable</strong><p>Load verified SKU cost, commission, fee, and baseline-order evidence.</p></div></div><div className="ps-v2-placeholder-table"><div><span>Metric</span><span>Baseline</span><span>Projected</span><span>Delta</span><span>Evidence</span></div>{["Orders", "Gross revenue", "Product cost", "Merchant promo cost", "Contribution"].map((metric) => <div key={metric}><span>{metric}</span><span>—</span><span>—</span><span>—</span><span>Missing</span></div>)}</div><div className="ps-v2-guardrail-check"><strong>Guardrail checks</strong><span>Campaign margin floor · Not evaluated</span><span>Merchant funding limit · Not evaluated</span><span>Loss-making SKU block · Not evaluated</span></div></div></div></section>

    <div className="ps-v2-dashboard-row"><section id="guardrails" className="ps-v2-card ps-v2-module-card"><header><div><h2>Margin guardrails</h2><p>Conditions, protected responses, and recent hits</p></div></header><div className="ps-v2-placeholder-table"><div><span>Guardrail</span><span>Condition</span><span>Action</span><span>Hits 30d</span><span>Status</span></div><div><span>No governed guardrails available</span><span>—</span><span>—</span><span>—</span><span>Off</span></div></div><Unavailable title="Guardrail configuration is unavailable" detail="Role checks and merchant approval are required before activation." /></section><section className="ps-v2-card ps-v2-module-card ps-v2-ai-card"><header><div><h2>Ask Copilot</h2><p>Evidence-backed promotion analysis</p></div></header><div className="ps-v2-question-chips"><button disabled>Which campaigns lose margin?</button><button disabled>What should I change?</button><button disabled>Who funds each discount?</button><button disabled>What is break-even uplift?</button></div><Unavailable dark title="Copilot is waiting for evidence" detail="No campaign claim is generated without attributable revenue, funding, and cost evidence." /></section></div>
  </DashboardV2Shell>;
}

function Unavailable({ title, detail, dark = false }: { title: string; detail: string; dark?: boolean }) {
  return <div className="ps-v2-unavailable">{dark ? <Bot size={24} aria-hidden="true" /> : <ShieldAlert size={24} aria-hidden="true" />}<div><strong>{title}</strong><p>{detail}</p></div></div>;
}
