import { AlertTriangle, Boxes, CheckCircle2, CircleDollarSign, PlugZap, ShieldCheck } from "lucide-react";
import type { CSSProperties } from "react";

type ChannelRow = { name: string; connected: boolean; termsReady: boolean };
type RiskRow = { name: string; channel: string; gap: string };
type TwinDimension={key:string;gross_sales:number;net_revenue:number;fees:number;discounts:number;product_cost:number;contribution:number;orders:number;margin_pct:number|null};
export type EconomicTwinSummary={currency:string|null;gross_sales:number;net_revenue:number;fees:number;discounts:number;refunds:number;product_cost:number;contribution:number;contribution_margin_pct:number|null;expected_payout:number;actual_payout:number;variance:number;orders:number;recoverable_amount:number;by_channel:TwinDimension[];by_branch:TwinDimension[];by_sku:TwinDimension[]};
type Props = { currency:string; trackedProducts:number; verifiedCosts:number; missingCosts:number; atRiskProducts:number; activeRules:number; attentionCount:number; confirmedActions:number; expectedPayout:number|null; economicTwin?:EconomicTwinSummary|null; channels:ChannelRow[]; risks:RiskRow[]; onCatalog:()=>void; onMargin:()=>void; onRecovery:()=>void; onAlerts:()=>void; onIntegrations:()=>void };
const money=(amount:number|null,currency:string)=>amount==null?"Not calculated":`${currency} ${amount.toLocaleString(undefined,{maximumFractionDigits:0})}`;
const channelColors=["#10B981","#4F8DF7","#F47320","#EF4444","#8B5CF6","#14B8A6"];

export function ExecutiveOverview(props:Props){
  const twin=props.economicTwin,twinReady=Boolean(twin?.orders);
  const connected=props.channels.filter(c=>c.connected).length;
  const termsReady=props.channels.filter(c=>c.termsReady).length;
  const evidencePct=props.trackedProducts?Math.round(props.verifiedCosts/props.trackedProducts*100):0;
  const missingPct=props.trackedProducts?Math.round(props.missingCosts/props.trackedProducts*100):0;
  const metrics=twinReady?[
    {label:"Gross Sales",value:money(twin!.gross_sales,twin!.currency??props.currency),note:`${twin!.orders} normalized orders`,icon:Boxes,tone:"#4F8DF7",action:props.onMargin},
    {label:"Net Revenue",value:money(twin!.net_revenue,twin!.currency??props.currency),note:`Fees ${money(twin!.fees,twin!.currency??props.currency)}`,icon:CircleDollarSign,tone:"#10B981",action:props.onMargin},
    {label:"Contribution",value:money(twin!.contribution,twin!.currency??props.currency),note:twin!.contribution_margin_pct==null?"Cost evidence incomplete":`${twin!.contribution_margin_pct}% contribution margin`,icon:ShieldCheck,tone:twin!.contribution>=0?"#10B981":"#EF4444",action:props.onMargin},
    {label:"Expected Payout",value:money(twin!.expected_payout,twin!.currency??props.currency),note:"From normalized payout evidence",icon:CircleDollarSign,tone:"#6366F1",action:props.onRecovery},
    {label:"Actual Payout",value:money(twin!.actual_payout,twin!.currency??props.currency),note:`Variance ${money(twin!.variance,twin!.currency??props.currency)}`,icon:CheckCircle2,tone:twin!.variance<0?"#EF4444":"#10B981",action:props.onRecovery},
    {label:"Recoverable",value:money(twin!.recoverable_amount,twin!.currency??props.currency),note:"Claim-ready amount still open",icon:AlertTriangle,tone:"#F47320",action:props.onRecovery},
  ]:[
    {label:"Catalog Items Synced",value:props.trackedProducts.toLocaleString(),note:`${props.verifiedCosts} with confirmed costs`,icon:Boxes,tone:"#4F8DF7",action:props.onCatalog},
    {label:"Channels Monitored",value:String(connected),note:`${props.channels.length} evidence sources`,icon:PlugZap,tone:"#4F8DF7",action:props.onIntegrations},
    {label:"Cost Evidence",value:`${evidencePct}%`,note:`${props.missingCosts} still need evidence`,icon:CheckCircle2,tone:"#10B981",action:props.onCatalog},
    {label:"Revenue at Risk",value:String(props.atRiskProducts),note:"Verified products below target",icon:AlertTriangle,tone:"#F47320",action:props.onMargin},
    {label:"Recoverable Payouts",value:money(props.expectedPayout,props.currency),note:"Latest retained calculation",icon:CircleDollarSign,tone:"#6366F1",action:props.onRecovery},
    {label:"Protected Pricing Actions",value:String(props.confirmedActions),note:`${props.activeRules} active guardrail${props.activeRules===1?"":"s"}`,icon:ShieldCheck,tone:"#2563EB",action:props.onAlerts},
  ];
  return <div className="exec-overview">
    <style>{`
      .exec-overview{display:grid;gap:12px;font-family:inherit}.exec-metrics{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:10px}
      .exec-card,.exec-panel{background:var(--surface);border:1px solid var(--border);border-radius:11px;box-shadow:0 3px 12px rgba(15,31,61,.035)}
      .exec-metric{min-height:110px;padding:14px;text-align:start;color:var(--text);cursor:pointer;transition:border-color .16s,box-shadow .16s}.exec-metric:hover{border-color:color-mix(in srgb,var(--metric-tone) 38%,var(--border));box-shadow:0 9px 22px -15px rgba(15,31,61,.34)}
      .exec-metric-top{display:flex;justify-content:space-between;gap:8px;align-items:center}.exec-metric-label{font-size:11px;color:var(--text);font-weight:750;line-height:1.35}.exec-metric-icon{width:30px;height:30px;display:grid;place-items:center;border-radius:9px;flex:0 0 auto}.exec-metric-value{font-size:20px;font-weight:800;margin-top:9px;letter-spacing:-.025em;line-height:1.15;font-variant-numeric:tabular-nums}.exec-metric-note{color:var(--muted);font-size:10.5px;margin-top:5px;line-height:1.4}
      .exec-grid{display:grid;grid-template-columns:1.05fr 1.45fr 1.05fr .9fr;gap:10px;align-items:stretch}.exec-lower{display:grid;grid-template-columns:1.55fr 1fr;gap:10px}.exec-panel{padding:15px;min-width:0;overflow:hidden}.exec-grid>.exec-panel{min-height:258px;box-sizing:border-box}.exec-panel h2{font-size:13.5px;font-weight:750;line-height:1.3;margin:0;color:var(--text)}.exec-sub{font-size:10.5px;color:var(--muted);margin-top:3px;line-height:1.45}.exec-panel-head{display:flex;align-items:center;justify-content:space-between;gap:10px}
      .exec-health{display:flex;align-items:center;gap:13px;margin-top:17px}.exec-donut{width:118px;height:118px;border-radius:50%;display:grid;place-items:center;flex:0 0 auto;position:relative}.exec-donut:after{content:"";width:76px;height:76px;border-radius:50%;background:var(--surface);position:absolute}.exec-donut-value{position:relative;z-index:1;text-align:center;font-size:20px;font-weight:800;color:var(--text)}.exec-donut-value small{display:block;font-size:8px;color:var(--muted);font-weight:700;text-transform:uppercase;margin-top:2px}
      .exec-legend{display:flex;align-items:center;gap:8px;font-size:10.5px;line-height:1.35}.exec-legend i{width:7px;height:7px;border-radius:50%;flex:0 0 auto}.exec-legend span{flex:1;color:var(--muted)}
      .exec-channel-bars{height:181px;display:flex;align-items:end;gap:9px;padding:17px 4px 0;border-bottom:1px solid var(--border);background:repeating-linear-gradient(to top,transparent 0,transparent 44px,var(--border) 45px)}.exec-channel-column{height:100%;display:flex;flex:1;min-width:0;flex-direction:column;justify-content:end;align-items:center;gap:5px}.exec-channel-column strong{font-size:10px;font-variant-numeric:tabular-nums}.exec-channel-bar{width:min(34px,72%);min-height:3px;border-radius:5px 5px 0 0}.exec-channel-column span{font-size:9px;text-transform:capitalize;max-width:100%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
      .exec-leakage{display:flex;align-items:center;gap:12px;margin-top:14px}.exec-leakage .exec-donut{width:108px;height:108px}.exec-leakage .exec-donut:after{width:68px;height:68px}.exec-alert{display:grid;grid-template-columns:30px 1fr auto;gap:9px;align-items:center;padding:10px 0;border-bottom:1px solid var(--border)}.exec-alert-icon{width:30px;height:30px;border-radius:9px;display:grid;place-items:center;background:#FFF7ED;color:#EA580C}.exec-alert strong{display:block;font-size:10.5px;line-height:1.35}.exec-alert small{color:var(--muted);font-size:9.5px;line-height:1.35}
      .exec-table{overflow:auto}.exec-table table{width:100%;border-collapse:collapse;min-width:650px}.exec-table th{font-size:9.5px;text-transform:uppercase;letter-spacing:.04em;color:var(--muted);font-weight:750;text-align:start;padding:10px 12px;background:var(--surface2)}.exec-table td{font-size:11px;padding:11px 12px;border-top:1px solid var(--border)}.exec-integrations>div{display:grid;grid-template-columns:1fr auto auto;gap:8px;align-items:center;border-top:1px solid var(--border);padding:8px 0;font-size:10.5px}.exec-integrations b{text-transform:capitalize}.exec-integrations .connected{color:#059669}.exec-integrations .manual{color:var(--muted)}.exec-link{border:0;background:transparent;color:#2563EB;font-family:inherit;font-size:10.5px;font-weight:750;padding:9px 0 0;cursor:pointer}
      @media(max-width:1250px){.exec-metrics{grid-template-columns:repeat(3,1fr)}.exec-grid{grid-template-columns:1fr 1fr}.exec-grid>.exec-panel{min-height:250px}.exec-lower{grid-template-columns:1fr}}@media(max-width:700px){.exec-metrics{grid-template-columns:1fr 1fr}.exec-grid{grid-template-columns:1fr}.exec-health{align-items:flex-start;flex-direction:column}.exec-donut{align-self:center}.exec-metric{min-height:104px;padding:13px}.exec-link{min-height:44px;display:inline-flex;align-items:center}.exec-alert{min-height:48px}}@media(max-width:420px){.exec-metrics{grid-template-columns:1fr}.exec-panel{padding:14px}.exec-channel-bars{gap:6px}}
      .exec-overview button:focus-visible{outline:2px solid var(--accent);outline-offset:2px}
      @media(prefers-reduced-motion:reduce){.exec-overview *{animation-duration:.01ms!important;animation-iteration-count:1!important;transition-duration:.01ms!important}}
    `}</style>
    <div className="exec-metrics">{metrics.map(({label,value,note,icon:Icon,tone,action})=><button key={label} type="button" className="exec-card exec-metric" style={{"--metric-tone":tone} as CSSProperties} onClick={action} aria-label={`${label}: ${value}. ${note}`}><div className="exec-metric-top"><span className="exec-metric-label">{label}</span><span className="exec-metric-icon" style={{background:`color-mix(in srgb,${tone} 10%,var(--surface))`,color:tone}}><Icon size={14} aria-hidden="true"/></span></div><div className="exec-metric-value" style={{fontSize:value.length>13?15:undefined}}>{value}</div><div className="exec-metric-note">{note}</div></button>)}</div>
    <div className="exec-grid">
      <section className="exec-panel"><div className="exec-panel-head"><div><h2>Catalog Health</h2><div className="exec-sub">Cost evidence across imported products</div></div><button className="exec-link" onClick={props.onCatalog}>View details →</button></div><div className="exec-health"><div className="exec-donut" style={{background:props.trackedProducts?`conic-gradient(#10B981 0 ${evidencePct}%,#4F8DF7 ${evidencePct}% ${Math.min(100,evidencePct+Math.max(2,Math.round(props.atRiskProducts/Math.max(1,props.trackedProducts)*100)))}%,#F47320 0 100%)`:"var(--surface2)"}}><div className="exec-donut-value">{props.trackedProducts.toLocaleString()}<small>Total items</small></div></div><div style={{flex:1,display:"grid",gap:9}}><Legend color="#10B981" label="Confirmed costs" value={props.verifiedCosts}/><Legend color="#4F8DF7" label="Below target" value={props.atRiskProducts}/><Legend color="#F47320" label="Missing evidence" value={props.missingCosts}/></div></div></section>
      <section className="exec-panel"><div className="exec-panel-head"><div><h2>Margin by Channel</h2><div className="exec-sub">{twinReady?"Normalized contribution margin":"Evidence readiness for protected-margin decisions"}</div></div><button className="exec-link" onClick={props.onMargin}>True margin %</button></div><div className="exec-channel-bars">{(twinReady?twin!.by_channel.slice(0,6).map(row=>({name:row.key,value:row.margin_pct??0})):props.channels.slice(0,6).map(channel=>({name:channel.name,value:channel.connected&&channel.termsReady?100:channel.connected?60:channel.termsReady?35:8}))).map((channel,index)=><div className="exec-channel-column" key={channel.name}><strong>{channel.value.toFixed(1)}%</strong><div className="exec-channel-bar" style={{height:`${Math.max(3,Math.min(100,Math.abs(channel.value)))}%`,background:channelColors[index%channelColors.length]}}/><span>{channel.name}</span></div>)}</div></section>
      <section className="exec-panel"><div className="exec-panel-head"><div><h2>Leakage Breakdown</h2><div className="exec-sub">Current evidence and margin signals</div></div></div><div className="exec-leakage"><div className="exec-donut" style={{background:props.missingCosts+props.atRiskProducts?`conic-gradient(#3159C9 0 ${100-missingPct}%,#F47320 0 100%)`:"var(--surface2)"}}><div className="exec-donut-value">{props.missingCosts+props.atRiskProducts}<small>Total at risk</small></div></div><div style={{flex:1,display:"grid",gap:9}}><Legend color="#3159C9" label="Cost evidenced" value={props.verifiedCosts}/><Legend color="#F47320" label="Missing evidence" value={props.missingCosts}/><Legend color="#8B5CF6" label="Margin risks" value={props.atRiskProducts}/></div></div></section>
      <section className="exec-panel"><div className="exec-panel-head"><div><h2>Top Alerts</h2><div className="exec-sub">Merchant attention queue</div></div><button className="exec-link" onClick={props.onAlerts}>View all →</button></div><Alert label="Cost evidence missing" detail={`${props.missingCosts} products`}/><Alert label="Low-margin products" detail={`${props.atRiskProducts} products`}/><Alert label="Commercial terms needed" detail={`${props.channels.length-termsReady} channels`}/></section>
    </div>
    <div className="exec-lower">
      <section className="exec-panel" style={{padding:0,minHeight:210}}><div style={{padding:"13px 14px",display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><h2>Catalog Action Queue</h2><div className="exec-sub">Verified products ranked by protected-margin gap</div></div><button className="exec-link" onClick={props.onCatalog}>View all →</button></div><div className="exec-table"><table><thead><tr><th>Product</th><th>Channel</th><th>Issue</th><th>Recommendation</th><th>Status</th></tr></thead><tbody>{props.risks.length?props.risks.slice(0,5).map(risk=><tr key={`${risk.channel}-${risk.name}`}><td><strong>{risk.name}</strong></td><td style={{textTransform:"capitalize"}}>{risk.channel}</td><td>Below protected margin</td><td>Review price gap {risk.gap}</td><td><span style={{color:"#C2410C",background:"#FFF7ED",borderRadius:999,padding:"3px 7px",fontWeight:750}}>Review</span></td></tr>):<tr><td colSpan={5} style={{color:"var(--muted)",textAlign:"center",padding:22}}>No verified products are currently below the active margin floor.</td></tr>}</tbody></table></div></section>
      <section className="exec-panel" style={{minHeight:210}}><div className="exec-panel-head"><div><h2>Integrations Status</h2><div className="exec-sub">Source access and agreement readiness</div></div><CheckCircle2 size={15} color="#059669"/></div><div className="exec-integrations" style={{marginTop:10}}>{props.channels.slice(0,6).map(channel=><div key={channel.name}><b>{channel.name}</b><span className={channel.connected?"connected":"manual"}>{channel.connected?"Connected":"Manual evidence"}</span><span style={{color:channel.termsReady?"#059669":"#EA580C"}}>{channel.termsReady?"Terms ready":"Terms needed"}</span></div>)}</div><button type="button" onClick={props.onIntegrations} className="exec-link">View integration health →</button></section>
    </div>
  </div>;
}

function Legend({color,label,value}:{color:string;label:string;value:number}){return <div className="exec-legend"><i style={{background:color}}/><span>{label}</span><strong>{value}</strong></div>}
function Alert({label,detail}:{label:string;detail:string}){return <div className="exec-alert"><span className="exec-alert-icon"><AlertTriangle size={13}/></span><div><strong>{label}</strong><small>{detail}</small></div><span style={{color:"var(--muted)"}}>›</span></div>}
