import { useEffect,useMemo,useState } from "react";

type Item={id:string;item_type:string;title:string;detail:string;priority:"critical"|"high"|"medium"|"low";status:"open"|"assigned"|"waiting_approval"|"snoozed"|"resolved"|"dismissed";amount:number|null;currency:string|null;evidence_strength:string;copilot_prompt:string|null;assigned_to:string|null;snoozed_until:string|null;resolution_note:string|null;detected_at:string;resolved_at:string|null};
type Ledger={id:string;category:string;label:string;amount:number;currency:string;evidence_strength:string;occurred_at:string};
type Experience={items:Item[];ledger:Ledger[];totals:Record<string,number>;recent_resolved:number;profit_brief:{order_count?:number;verified_cost_coverage_pct?:number;retrieved_at?:string}|null;settings:{automation_level:string;weekly_review_enabled:boolean;progressive_mode:boolean}};
const OG="#EF681A",GN="#10B981",RED="#DC2626";
const LEVELS=[{id:"observe",label:"Observe",desc:"Monitor only"},{id:"recommend",label:"Recommend",desc:"Prepare safe actions"},{id:"approve",label:"Approve",desc:"Wait for every approval"},{id:"auto_protect",label:"Auto-protect",desc:"Act only inside active limits"}];

export function MerchantOperatingLoop({mode="hub",onAskCopilot}:{mode?:"hub"|"history";onAskCopilot?:(prompt:string)=>void}){
  const [data,setData]=useState<Experience|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[filter,setFilter]=useState("active"),[detail,setDetail]=useState(false),[message,setMessage]=useState("");
  const call=async(body:Record<string,string>)=>{const response=await fetch("/api/channels/connect",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({merchant_id:localStorage.getItem("ps_merchant_id")??"",access_code:localStorage.getItem("ps_access_code")??"",platform:"merchant_experience",...body})});const result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error??"Request failed");return result;};
  const load=async()=>{try{const result=await call({action:"get"});setData(result);}catch{setMessage("Your attention list could not be loaded. Refresh and try again.");}finally{setLoading(false);}};
  useEffect(()=>{void load();void call({action:"track",event_name:"today_viewed"});const refresh=window.setTimeout(()=>void load(),3000);return()=>window.clearTimeout(refresh);},[]);
  useEffect(()=>{if(!data||!location.hash.startsWith("#attention-"))return;const target=document.querySelector(location.hash);if(target){target.scrollIntoView({behavior:"smooth",block:"center"});void call({action:"track",event_name:"attention_deep_link_opened",object_id:location.hash.replace("#attention-","")});}},[data]);
  const update=async(item:Item,action:string,value="")=>{setBusy(item.id);setMessage("");try{await call({action:"attention",id:item.id,attention_action:action,value});await load();setMessage(action==="resolve"?"Marked resolved and added to Activity & Evidence.":action==="snooze"?"Snoozed for one day.":action==="assign"?"Assigned.":"Dismissed.");}catch{setMessage("That change was not saved. Try again.");}finally{setBusy("");}};
  const saveLevel=async(level:string)=>{if(!data)return;setBusy("settings");try{const result=await call({action:"settings",automation_level:level,weekly_review_enabled:String(data.settings.weekly_review_enabled),progressive_mode:String(data.settings.progressive_mode)});setData({...data,settings:result.settings});setMessage("Protection level saved.");}catch{setMessage("Protection level was not saved.");}finally{setBusy("");}};
  const toggleWeekly=async()=>{if(!data)return;setBusy("settings");try{const result=await call({action:"settings",automation_level:data.settings.automation_level,weekly_review_enabled:String(!data.settings.weekly_review_enabled),progressive_mode:String(data.settings.progressive_mode)});setData({...data,settings:result.settings});setMessage(result.settings.weekly_review_enabled?"Weekly in-app review enabled.":"Weekly in-app review paused.");}catch{setMessage("Weekly review choice was not saved.");}finally{setBusy("");}};
  const active=data?.items.filter(item=>["open","assigned","waiting_approval","snoozed"].includes(item.status))??[],resolved=data?.items.filter(item=>item.status==="resolved")??[];
  const visible=filter==="active"?active:filter==="resolved"?resolved:data?.items??[];
  const urgent=active.filter(item=>["critical","high"].includes(item.priority)),moneyAtRisk=active.reduce((sum,item)=>sum+(item.amount??0),0),currency=active.find(item=>item.currency)?.currency??data?.ledger[0]?.currency??"SAR";
  const ledgerGroups=useMemo(()=>["recovered","protected","identified","estimated","pending"].map(category=>({category,value:data?.totals[category]??0})),[data]);
  if(loading)return <div style={{padding:20,border:"1px solid var(--border)",borderRadius:14,color:"var(--muted)"}}>Preparing today’s merchant briefing…</div>;
  const askCopilot=(prompt:string)=>{void call({action:"track",event_name:"copilot_from_attention"});onAskCopilot?.(prompt);};
  if(mode==="history")return <section style={card}><Header eyebrow="Activity & Evidence" title="Resolved attention items" sub="What was detected, who handled it, and how it was closed."/><Items items={resolved} busy={busy} history onUpdate={update} onAsk={askCopilot}/></section>;
  return <section data-tour="merchant-operating-loop" style={{...card,gap:20}}>
    <Header eyebrow="Today" title={urgent.length?`${urgent.length} important item${urgent.length===1?" needs":"s need"} your attention`:active.length?`${active.length} item${active.length===1?" is":"s are"} being watched`:"Your protection queue is clear"} sub={data?.profit_brief?.order_count!=null?`PrizeSkout checked ${data.profit_brief.order_count} recent Zid orders and your current protection evidence.`:"PrizeSkout is watching connected products, orders, promotions and payouts."}/>
    <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(155px,1fr))",gap:10}}>{[["Open",active.length,"Needs a decision"],["High priority",urgent.length,"Review first"],["Money identified",`${currency} ${moneyAtRisk.toFixed(2)}`,"Not claimed as recovered"],["Resolved this week",data?.recent_resolved??0,"Recorded as evidence"]].map(([label,value,note])=><Metric key={String(label)} label={String(label)} value={String(value)} note={String(note)}/>)}</div>

    {(data?.profit_brief?.verified_cost_coverage_pct??100)<80&&<div style={{padding:"14px 16px",borderRadius:11,border:"1px solid color-mix(in srgb,#F59E0B 30%,var(--border))",background:"color-mix(in srgb,#F59E0B 7%,var(--surface))"}}><strong>Finish your first-value setup</strong><div style={{fontSize:12.5,color:"var(--muted)",marginTop:4}}>✓ Zid connected · ✓ Orders checked · Next: confirm product costs. Evidence is {Math.round(data?.profit_brief?.verified_cost_coverage_pct??0)}%.</div>{onAskCopilot&&<button onClick={()=>askCopilot("Show my highest-priority products with missing costs")} style={linkButton}>Continue setup →</button>}</div>}

    <div><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"}}><h3 style={{margin:0}}>Attention Inbox</h3><div style={{display:"flex",gap:6}}>{["active","resolved","all"].map(value=><button key={value} onClick={()=>setFilter(value)} style={{...smallButton,background:filter===value?OG:"var(--surface)",color:filter===value?"#fff":"var(--muted)"}}>{value[0].toUpperCase()+value.slice(1)}</button>)}</div></div><Items items={visible} busy={busy} onUpdate={update} onAsk={askCopilot}/></div>

    <button type="button" onClick={()=>setDetail(value=>!value)} style={{...linkButton,alignSelf:"flex-start"}}>{detail?"Hide weekly review and controls ↑":"Weekly review, value and automation →"}</button>
    {detail&&<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(280px,1fr))",gap:14}}>
      <div style={subCard}><div style={{display:"flex",justifyContent:"space-between",gap:8}}><h3 style={{margin:"0 0 10px"}}>Weekly protection review</h3><button onClick={()=>{void call({action:"track",event_name:"weekly_review_opened"});void toggleWeekly();}} style={smallButton}>{data?.settings.weekly_review_enabled?"Enabled":"Paused"}</button></div><p style={copy}>This week PrizeSkout resolved {data?.recent_resolved??0} item{data?.recent_resolved===1?"":"s"}; {active.length} remain open. The value below remains separated by evidence state.</p><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}>{ledgerGroups.map(group=><Metric key={group.category} label={group.category} value={`${currency} ${group.value.toFixed(2)}`} note={group.category==="identified"?"Detected, not recovered":"Evidence ledger"}/>)}</div></div>
      <div style={subCard}><h3 style={{margin:"0 0 6px"}}>How much should PrizeSkout do?</h3><p style={copy}>Increase automation only as trust grows. Active Margin Policy Engine limits still apply.</p><div style={{display:"flex",flexDirection:"column",gap:7}}>{LEVELS.map(level=><button key={level.id} disabled={busy==="settings"} onClick={()=>void saveLevel(level.id)} style={{padding:"10px 12px",textAlign:"left",borderRadius:9,border:`1px solid ${data?.settings.automation_level===level.id?OG:"var(--border)"}`,background:data?.settings.automation_level===level.id?`color-mix(in srgb,${OG} 7%,var(--surface))`:"var(--surface)",color:"var(--text)",fontFamily:"inherit",cursor:"pointer"}}><strong>{level.label}</strong><span style={{marginLeft:8,color:"var(--muted)",fontSize:12}}>{level.desc}</span></button>)}</div></div>
    </div>}
    <div aria-live="polite" style={{minHeight:18,fontSize:12,color:message.includes("not")||message.includes("could not")?RED:"var(--muted)"}}>{message}</div>
  </section>;
}

function Items({items,busy,history=false,onUpdate,onAsk}:{items:Item[];busy:string;history?:boolean;onUpdate:(item:Item,action:string,value?:string)=>void;onAsk?:((prompt:string)=>void)}){if(!items.length)return <div style={{marginTop:12,padding:18,border:"1px solid var(--border)",borderRadius:11,color:"var(--muted)"}}>Nothing here right now.</div>;return <div style={{marginTop:12,border:"1px solid var(--border)",borderRadius:12,overflow:"hidden"}}>{items.map(item=><article id={`attention-${item.id}`} key={item.id} style={{padding:"14px 16px",borderTop:"1px solid var(--border)",display:"grid",gridTemplateColumns:"minmax(0,1fr)",gap:12}}><div><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><strong>{item.title}</strong><Badge text={item.priority} color={item.priority==="critical"||item.priority==="high"?RED:item.priority==="medium"?"#B45309":GN}/><Badge text={item.evidence_strength} color="var(--muted)"/><Badge text={item.status.replace("_"," ")} color="var(--muted)"/></div><div style={{fontSize:12.5,color:"var(--muted)",marginTop:4,lineHeight:1.5}}>{item.detail}</div>{history&&<div style={{fontSize:11.5,color:"var(--muted)",marginTop:5}}>{item.resolution_note??"Resolved"} · {item.resolved_at?new Date(item.resolved_at).toLocaleString():""}</div>}</div>{!history&&<div style={{display:"flex",gap:6,alignItems:"center",flexWrap:"wrap"}}>{onAsk&&item.copilot_prompt&&<button onClick={()=>onAsk(item.copilot_prompt!)} style={smallButton}>Ask Copilot</button>}<button onClick={()=>void navigator.clipboard.writeText(`${location.origin}${location.pathname}#attention-${item.id}`)} style={smallButton}>Copy link</button><button disabled={busy===item.id} onClick={()=>onUpdate(item,"assign","Merchant owner")} style={smallButton}>Assign</button><button disabled={busy===item.id} onClick={()=>onUpdate(item,"request_approval","Finance approver")} style={smallButton}>Request approval</button><button disabled={busy===item.id} onClick={()=>onUpdate(item,"snooze","1")} style={smallButton}>Snooze</button><button disabled={busy===item.id} onClick={()=>{const reason=window.prompt("Why are you dismissing this item?");if(reason?.trim())onUpdate(item,"dismiss",reason.trim());}} style={smallButton}>Dismiss</button><button disabled={busy===item.id} onClick={()=>{const note=window.prompt("What resolved this item?","Reviewed and resolved by merchant.");if(note?.trim())onUpdate(item,"resolve",note.trim());}} style={{...smallButton,color:GN}}>Resolve</button></div>}</article>)}</div>;}
function Header({eyebrow,title,sub}:{eyebrow:string;title:string;sub:string}){return <div><div style={{fontSize:11,fontWeight:900,color:OG,textTransform:"uppercase",letterSpacing:".08em"}}>{eyebrow}</div><h2 style={{margin:"5px 0",fontSize:25}}>{title}</h2><p style={{...copy,margin:0}}>{sub}</p></div>}
function Metric({label,value,note}:{label:string;value:string;note:string}){return <div style={{padding:"12px 13px",border:"1px solid var(--border)",borderRadius:10,background:"var(--surface2)"}}><div style={{fontSize:10.5,textTransform:"uppercase",fontWeight:800,color:"var(--muted)"}}>{label}</div><div style={{fontSize:21,fontWeight:850,marginTop:4}}>{value}</div><div style={{fontSize:11,color:"var(--muted)",marginTop:2}}>{note}</div></div>}
function Badge({text,color}:{text:string;color:string}){return <span style={{fontSize:9.5,fontWeight:850,textTransform:"uppercase",color,border:"1px solid var(--border)",borderRadius:999,padding:"3px 7px"}}>{text}</span>}
const card:React.CSSProperties={background:"var(--surface)",border:"1px solid var(--border)",borderRadius:18,boxShadow:"var(--shadow)",padding:"24px 26px",display:"flex",flexDirection:"column"};
const subCard:React.CSSProperties={padding:16,border:"1px solid var(--border)",borderRadius:12,background:"var(--surface2)"};
const copy:React.CSSProperties={fontSize:13,color:"var(--muted)",lineHeight:1.55};
const smallButton:React.CSSProperties={border:"1px solid var(--border)",borderRadius:8,padding:"7px 9px",background:"var(--surface)",color:"var(--text)",fontFamily:"inherit",fontSize:11.5,fontWeight:750,cursor:"pointer"};
const linkButton:React.CSSProperties={border:"none",background:"transparent",color:OG,padding:"8px 0 0",fontFamily:"inherit",fontWeight:850,cursor:"pointer"};
