import { useEffect, useState } from "react";

type Task={status:string;priority:string};
type Attention={status:string;priority:string};
const OG="#EF681A",RED="#DC2626";

export function StoreManagerCommandBar({context,examples,onSubmit,onOpenManager,busy=false}:{context:string;examples:string[];onSubmit:(prompt:string)=>void;onOpenManager:()=>void;busy?:boolean}){
  const [value,setValue]=useState(""),[tasks,setTasks]=useState<Task[]>([]),[attention,setAttention]=useState<Attention[]>([]);
  useEffect(()=>{let active=true;const load=async()=>{try{const response=await fetch("/api/channels/connect",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({merchant_id:localStorage.getItem("ps_merchant_id")??"",access_code:localStorage.getItem("ps_access_code")??"",platform:"merchant_experience",action:"get"})}),body=await response.json();if(active&&response.ok&&body.ok){setTasks(body.manager?.tasks??[]);setAttention(body.items??[]);}}catch{/* The command bar remains usable if status cannot be loaded. */}};void load();const timer=window.setInterval(()=>void load(),60_000);return()=>{active=false;window.clearInterval(timer);};},[]);
  const openTasks=tasks.filter(task=>!["completed","cancelled"].includes(task.status)),approvals=openTasks.filter(task=>task.status==="waiting_approval"),urgent=attention.filter(item=>["open","assigned","waiting_approval"].includes(item.status)&&["critical","high"].includes(item.priority));
  const submit=()=>{const prompt=value.trim();if(!prompt||busy)return;onSubmit(prompt);setValue("");};
  return <section data-tour="store-manager-command" style={{margin:"18px 30px 0",padding:"16px 18px",border:`1px solid color-mix(in srgb,${OG} 30%,var(--border))`,borderRadius:15,background:`linear-gradient(135deg,color-mix(in srgb,${OG} 7%,var(--surface)),var(--surface))`,boxShadow:"0 10px 28px rgba(15,23,42,.06)"}}>
    <div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap",marginBottom:11}}><div><div style={{fontSize:11,fontWeight:900,color:OG,textTransform:"uppercase",letterSpacing:".08em"}}>Store Manager · {context}</div><div style={{fontSize:13,color:"var(--muted)",marginTop:3}}>Ask a question or delegate backend work. PrizeSkout previews protected changes before applying them.</div></div><button type="button" onClick={onOpenManager} style={{border:"1px solid var(--border)",borderRadius:999,padding:"7px 10px",background:"var(--surface)",color:"var(--text)",fontFamily:"inherit",fontWeight:750,fontSize:11.5,cursor:"pointer"}}>{approvals.length?`${approvals.length} approval${approvals.length===1?"":"s"} waiting`:openTasks.length?`${openTasks.length} task${openTasks.length===1?"":"s"} open`:"Management desk"}{urgent.length?<span style={{color:RED}}> · {urgent.length} urgent</span>:null}</button></div>
    <div style={{display:"flex",gap:8,alignItems:"stretch"}}><input aria-label="Ask or delegate to Store Manager" value={value} onChange={event=>setValue(event.target.value)} onKeyDown={event=>{if(event.key==="Enter")submit();}} placeholder="What should PrizeSkout handle today?" style={{flex:1,minWidth:0,border:"1.5px solid var(--border)",borderRadius:11,padding:"12px 14px",background:"var(--surface)",color:"var(--text)",fontFamily:"inherit",fontSize:14.5,outline:"none"}}/><button type="button" disabled={!value.trim()||busy} onClick={submit} style={{border:0,borderRadius:11,padding:"11px 16px",background:OG,color:"#fff",fontFamily:"inherit",fontWeight:850,cursor:value.trim()&&!busy?"pointer":"default",opacity:value.trim()&&!busy?1:.55}}>Delegate →</button></div>
    <div style={{display:"flex",gap:7,overflowX:"auto",marginTop:9,paddingBottom:1}}>{examples.slice(0,3).map(example=><button key={example} type="button" onClick={()=>setValue(example)} style={{whiteSpace:"nowrap",border:"1px solid var(--border)",borderRadius:999,padding:"6px 9px",background:"var(--surface)",color:"var(--muted)",fontFamily:"inherit",fontSize:10.5,cursor:"pointer"}}>{example}</button>)}</div>
  </section>;
}
