import { useEffect,useState } from "react";

type Order={id:string;code:string;status:string;gross_revenue:number;vat_amount:number;return_amount:number;revenue:number;contribution:number|null;cost_coverage_pct:number;attention:string|null};
type Coupon={id:string;code:string;discount_label:string;products_below_floor:number;verified_products_tested:number;risk:"review"|"safe"|"unknown"};
type Brief={currency:string;order_count:number;gross_revenue:number;revenue:number;contribution:number;contribution_pct:number|null;loss_order_count:number;loss_amount:number;verified_cost_coverage_pct:number;excluded_order_count:number;vat:{available:boolean;active:boolean;included_in_prices:boolean;rate:number|null;amount:number;message:string};stock:{products:number;available:number;out_of_stock:number;low_stock:number;unknown:number;units_available:number};returns:{orders:number;amount:number;status:string;message:string};orders:Order[];coupons:Coupon[];priorities:Array<{kind:string;title:string;detail:string}>;limitations:string[]};
const OG="#EF681A",GN="#10B981",RED="#DC2626";
const money=(n:number,c:string)=>`${c} ${n.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;

export function ZidProfitBrief({connected}:{connected:boolean}){
  const [brief,setBrief]=useState<Brief|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(""),[open,setOpen]=useState(false);
  async function load(){if(!connected||loading)return;setLoading(true);setError("");try{const response=await fetch("/api/copilot/store",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({merchant_id:localStorage.getItem("ps_merchant_id")??"",access_code:localStorage.getItem("ps_access_code")??"",action:"profit_brief",days:30})});const data=await response.json() as {brief?:Brief;error?:string};if(!response.ok||!data.brief)throw new Error(data.error??"Could not analyse Zid orders.");setBrief(data.brief);}catch(reason){setError(reason instanceof Error?reason.message:"Could not analyse Zid orders.");}finally{setLoading(false);}}
  useEffect(()=>{if(connected)void load();},[connected]);
  if(!connected)return null;
  const stats=brief?[["Zid sales",money(brief.gross_revenue,brief.currency),`${brief.order_count} orders before tax and returns`],["Amount kept*",money(brief.contribution,brief.currency),brief.contribution_pct==null?"Needs complete costs":`${(brief.contribution_pct*100).toFixed(1)}% after confirmed VAT and returns`],["VAT removed",money(brief.vat.amount,brief.currency),brief.vat.available?brief.vat.message:"VAT permission needed"],["Returns removed",money(brief.returns.amount,brief.currency),`${brief.returns.orders} affected order${brief.returns.orders===1?"":"s"}`],["Stock ready",String(brief.stock.available),`${brief.stock.out_of_stock} out · ${brief.stock.low_stock} low`],["Cost evidence",`${Math.round(brief.verified_cost_coverage_pct)}%`,`${brief.excluded_order_count} orders withheld`]]:[];
  return <section data-tour="zid-profit-brief" style={{background:"var(--surface)",border:"1px solid var(--border)",borderRadius:18,boxShadow:"var(--shadow)",padding:"24px 26px",display:"flex",flexDirection:"column",gap:18}}>
    <div style={{display:"flex",justifyContent:"space-between",gap:16,alignItems:"flex-start",flexWrap:"wrap"}}><div><div style={{fontSize:11,fontWeight:900,color:OG,textTransform:"uppercase",letterSpacing:".08em"}}>Zid Profit Brief · Last 30 days</div><h2 style={{margin:"6px 0 5px",fontSize:25}}>Know what your Zid orders actually kept</h2><p style={{margin:0,color:"var(--muted)",fontSize:13.5}}>Orders, verified product costs and coupon risk—translated into the actions that matter now.</p></div><button type="button" onClick={()=>void load()} disabled={loading} style={{border:"1px solid var(--border)",background:"var(--surface)",color:"var(--text)",borderRadius:9,padding:"10px 14px",fontFamily:"inherit",fontWeight:750,cursor:loading?"default":"pointer",opacity:loading?.6:1}}>{loading?"Checking Zid…":"Refresh from Zid"}</button></div>
    {error&&<div style={{padding:"12px 14px",borderRadius:10,background:"color-mix(in srgb,#DC2626 7%,var(--surface))",border:"1px solid color-mix(in srgb,#DC2626 25%,var(--border))",color:RED,fontSize:13}}><strong>Profit Brief needs attention.</strong> {error}</div>}
    {!brief&&!error&&<div style={{padding:22,textAlign:"center",color:"var(--muted)"}}>Reading recent orders, costs and coupons from Zid…</div>}
    {brief&&<><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(155px,1fr))",gap:10}}>{stats.map(([label,value,note])=><div key={label} style={{padding:"14px 15px",border:"1px solid var(--border)",borderRadius:11,background:"var(--surface2)"}}><div style={{fontSize:10.5,textTransform:"uppercase",fontWeight:800,color:"var(--muted)"}}>{label}</div><div style={{fontSize:23,fontWeight:850,marginTop:5,color:label==="Orders losing money"&&brief.loss_order_count?RED:"var(--text)"}}>{value}</div><div style={{fontSize:11.5,color:"var(--muted)",marginTop:3}}>{note}</div></div>)}</div>
      <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:10}}>{brief.priorities.slice(0,3).map((item,index)=><div key={`${item.kind}-${index}`} style={{padding:"14px 15px",borderRadius:11,border:`1px solid ${item.kind==="healthy"?`color-mix(in srgb,${GN} 30%,var(--border))`:`color-mix(in srgb,${OG} 28%,var(--border))`}`,background:"var(--surface2)"}}><strong>{item.title}</strong><div style={{fontSize:12.5,color:"var(--muted)",marginTop:4,lineHeight:1.5}}>{item.detail}</div></div>)}</div>
      <button type="button" onClick={()=>setOpen(v=>!v)} style={{alignSelf:"flex-start",border:"none",background:"transparent",color:OG,padding:0,fontFamily:"inherit",fontWeight:850,cursor:"pointer"}}>{open?"Hide details ↑":"Review orders and coupons →"}</button>
      {open&&<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(300px,1fr))",gap:14}}><Detail title="Orders needing attention">{brief.orders.filter(o=>o.attention||o.vat_amount>0||o.return_amount>0).slice(0,12).map(order=><div key={order.id} style={{display:"flex",justifyContent:"space-between",gap:10,padding:"11px 14px",borderTop:"1px solid var(--border)"}}><div><strong>{order.code}</strong><div style={{fontSize:11.5,color:order.contribution!=null&&order.contribution<0?RED:"#B45309",marginTop:3}}>{order.attention??[order.vat_amount?`${money(order.vat_amount,brief.currency)} VAT`:"",order.return_amount?`${money(order.return_amount,brief.currency)} returned`:""].filter(Boolean).join(" · ")}</div></div><div style={{textAlign:"right",fontSize:12}}><strong>{money(order.revenue,brief.currency)} usable revenue</strong><div style={{color:"var(--muted)",marginTop:3}}>{order.contribution==null?`${Math.round(order.cost_coverage_pct)}% costs`:money(order.contribution,brief.currency)+" kept"}</div></div></div>)}</Detail><Detail title="Coupon safety check">{brief.coupons.slice(0,10).map(coupon=><div key={coupon.id} style={{padding:"11px 14px",borderTop:"1px solid var(--border)"}}><div style={{display:"flex",justifyContent:"space-between"}}><strong>{coupon.code}</strong><strong style={{color:coupon.risk==="review"?RED:coupon.risk==="safe"?GN:"var(--muted)"}}>{coupon.discount_label}</strong></div><div style={{fontSize:11.5,color:"var(--muted)",marginTop:3}}>{coupon.risk==="review"?`${coupon.products_below_floor} available products would fall below your floor`:coupon.risk==="safe"?`Safe across ${coupon.verified_products_tested} available, verified products`:"Not enough evidence to judge safely"}</div></div>)}</Detail></div>}
      <div style={{fontSize:11.5,color:"var(--muted)",lineHeight:1.5}}>* {brief.limitations[0]} Orders without complete cost evidence are withheld rather than guessed.</div></>}
  </section>;
}

function Detail({title,children}:{title:string;children:React.ReactNode}){return <div style={{border:"1px solid var(--border)",borderRadius:12,overflow:"hidden"}}><div style={{padding:"12px 14px",fontWeight:850,background:"var(--surface2)"}}>{title}</div>{children}</div>;}
