import {readFileSync} from "node:fs";
import {strict as assert} from "node:assert";
import {classifyReconciliationEvidence,evidenceFingerprint} from "../src/server/core/merchant-evidence";
import {prepareMerchantEvidenceIntake} from "../src/server/core/merchant-evidence-intake";
import {buildNormalizedCommerceEvents} from "../src/server/core/normalized-commerce-events";
import {assessReconciliationReadiness,buildNormalizedReconciliationInput,classifyAllocationFinding,compareShadowParity,reconciliationCoverage} from "../src/server/core/normalized-reconciliation-shadow";
import {createHmac} from "node:crypto";
import {verifyInboundEmailSignature} from "../src/server/core/evidence-mailbox";
import {classifyStructuredText,extractStructuredEvidence,inferEvidencePlatform} from "../src/server/core/evidence-document-processor";
import {assessPdfTextQuality} from "../src/server/core/server-pdf-text";
import {sanitizeOcrEvidenceDraft} from "../src/server/core/ocr-evidence-extractor";
import {allowedRecoveryTransitions,assertRecoveryTransition} from "../src/server/core/recovery-lifecycle";
import {summarizeCopilotFinancialEvidence} from "../src/server/core/copilot-financial-evidence";
import {detectEvidenceLayout} from "../src/server/core/evidence-layout-registry";
import {classifyLayoutDrift} from "../src/server/core/evidence-layout-drift";
import {assessEvidenceSourceHealth,prepareEvidenceSource,summarizeEvidenceSourceCoverage} from "../src/server/core/evidence-source-connections";
import {buildEvidenceSourceAttention} from "../src/server/core/evidence-source-attention";
import {assessSourceDeliveryCompleteness,prepareSourceOrderBatch,validateAuthorizedSourceRecords} from "../src/server/core/evidence-source-sync";
import writeXlsxFile from "write-excel-file/node";
import {rankAgreementCandidates} from "../src/server/core/evidence-agreement-matcher";
import {buildRecoveryCaseFromFinding} from "../src/server/core/recovery-cases";
import {buildReconciliationAttentionGroups} from "../src/server/core/reconciliation-attention";
import {retainCurrentEventRevisions} from "../src/server/core/normalized-reconciliation-shadow";
import {fingerprintRecoveryEvidenceManifest} from "../src/server/core/recovery-evidence-pack";

const migration=readFileSync("supabase/migrations/20260830000000_api_independent_evidence_foundation.sql","utf8");
const mailboxMigration=readFileSync("supabase/migrations/20260832000000_merchant_evidence_mailboxes.sql","utf8");
const reviewMigration=readFileSync("supabase/migrations/20260833000000_evidence_review_approval.sql","utf8");
const reliabilityMigration=readFileSync("supabase/migrations/20260834000000_evidence_processing_reliability.sql","utf8");
const agreementMigration=readFileSync("supabase/migrations/20260835000000_evidence_agreement_matching.sql","utf8");
const contractDraftMigration=readFileSync("supabase/migrations/20260836000000_evidence_contract_drafts.sql","utf8");
const findingMigration=readFileSync("supabase/migrations/20260837000000_reconciliation_findings.sql","utf8");
const recoveryBridgeMigration=readFileSync("supabase/migrations/20260838000000_reconciliation_recovery_bridge.sql","utf8");
const crossDocumentMigration=readFileSync("supabase/migrations/20260839000000_cross_document_reconciliation.sql","utf8");
const rematchMigration=readFileSync("supabase/migrations/20260840000000_agreement_rematch_revisions.sql","utf8");
const evidencePackMigration=readFileSync("supabase/migrations/20260841000000_recovery_evidence_packs.sql","utf8");

assert(!/alter table public\.ps_(zid|salla)_/i.test(migration),"Foundation must not alter protected Zid or Salla tables.");
assert(migration.includes("protected_integration_copy"),"Protected integration copies must be explicit and shadow-only.");
assert(migration.includes("optional_api"),"Optional API evidence must remain an optional source kind.");
assert(migration.includes("watched_folder"),"Merchant-controlled watched-folder evidence is required.");
assert(migration.includes("forwarded_email"),"Merchant-controlled forwarded email evidence is required.");
assert(mailboxMigration.includes("ps_evidence_mailboxes"),"Private merchant forwarding aliases are required.");
assert(mailboxMigration.includes("private_forwarding_address")&&mailboxMigration.includes("automatic_forwarding_rule")&&mailboxMigration.includes("connected_mailbox"),"All three merchant email collection options must remain available.");
assert(!/alter table public\.ps_(zid|salla)_/i.test(mailboxMigration),"Mailbox automation must not alter protected Zid or Salla tables.");
assert(reviewMigration.includes("ps_evidence_review_drafts")&&reviewMigration.includes("ps_evidence_review_decisions"),"Machine extraction must pass through a permanent merchant review gate.");
assert(reliabilityMigration.includes("ps_lease_evidence_processing_jobs")&&reliabilityMigration.includes("for update skip locked"),"Automatic evidence processing requires atomic leased jobs.");
assert(reliabilityMigration.includes("dead_letter")&&reliabilityMigration.includes("max_attempts"),"Repeated evidence failures must enter a bounded holding area.");
assert(reliabilityMigration.includes("ps_evidence_processor_runs"),"Automatic processing must persist a health heartbeat.");
assert(!/alter table public\.ps_(zid|salla)_/i.test(`${reviewMigration}\n${reliabilityMigration}`),"Review and processing reliability must not alter protected Zid or Salla tables.");
assert(agreementMigration.includes("ps_evidence_agreement_matches")&&agreementMigration.includes("needs_confirmation"),"Agreement matching must persist ambiguous choices for merchant confirmation.");
assert(!/alter table public\.ps_(zid|salla)_/i.test(agreementMigration),"Agreement matching must not alter protected Zid or Salla tables.");
assert(contractDraftMigration.includes("source_evidence_item_id")&&contractDraftMigration.includes("source_review_decision_id"),"Evidence-created agreement drafts must retain document and review provenance.");
assert(contractDraftMigration.includes("on delete restrict"),"Agreement draft provenance must not be silently deleted.");
assert(!/alter table public\.ps_(zid|salla)_/i.test(contractDraftMigration),"Agreement draft provenance must not alter protected Zid or Salla tables.");
assert(findingMigration.includes("confirmed_discrepancy")&&findingMigration.includes("unallocated_batch_difference"),"Reconciliation findings must preserve evidence-strength conclusions.");
assert(findingMigration.includes("ps_reconciliation_findings_immutable"),"Reconciliation findings must be append-only.");
assert(!/alter table public\.ps_(zid|salla)_/i.test(findingMigration),"Reconciliation findings must not alter protected Zid or Salla tables.");
assert(recoveryBridgeMigration.includes("reconciliation_finding_id")&&recoveryBridgeMigration.includes("on delete restrict"),"Recovery cases must retain immutable finding provenance.");
assert(!/alter table public\.ps_(zid|salla)_/i.test(recoveryBridgeMigration),"Recovery provenance must not alter protected Zid or Salla tables.");
assert(crossDocumentMigration.includes("ps_reconciliation_run_evidence")&&crossDocumentMigration.includes("evidence_role"),"Cross-document runs must retain a complete evidence manifest.");
assert(crossDocumentMigration.includes("ps_reconciliation_run_evidence_immutable"),"Cross-document evidence manifests must be append-only.");
assert(!/alter table public\.ps_(zid|salla)_/i.test(crossDocumentMigration),"Cross-document reconciliation must not alter protected Zid or Salla tables.");
assert(rematchMigration.includes("revision integer")&&rematchMigration.includes("ps_evidence_agreement_match_revision_unique"),"Agreement rematches must create append-only revisions.");
assert(!/alter table public\.ps_(zid|salla)_/i.test(rematchMigration),"Agreement rematches must not alter protected Zid or Salla tables.");
assert(evidencePackMigration.includes("ps_recovery_evidence_packs")&&evidencePackMigration.includes("ps_recovery_evidence_pack_approvals"),"Recovery evidence manifests and their approvals must be stored separately.");
assert((evidencePackMigration.match(/ps_reject_reconciliation_mutation/g)??[]).length>=2,"Recovery evidence packs and approvals must be immutable.");
assert(!/alter table public\.ps_(zid|salla)_/i.test(evidencePackMigration),"Recovery evidence packs must not alter protected Zid or Salla tables.");

assert.equal(classifyReconciliationEvidence({hasOrderTruth:true,hasContractTruth:true,hasPayoutTruth:true,hasOrderLevelPayoutAllocation:true,variance:0}),"reconciled");
assert.equal(classifyReconciliationEvidence({hasOrderTruth:true,hasContractTruth:true,hasPayoutTruth:true,hasOrderLevelPayoutAllocation:true,variance:25}),"confirmed_discrepancy");
assert.equal(classifyReconciliationEvidence({hasOrderTruth:true,hasContractTruth:true,hasPayoutTruth:true,hasOrderLevelPayoutAllocation:true,variance:25,evidenceStrength:"partial"}),"probable_discrepancy");
assert.equal(classifyReconciliationEvidence({hasOrderTruth:true,hasContractTruth:true,hasPayoutTruth:true,hasOrderLevelPayoutAllocation:false,variance:25}),"unallocated_batch_difference");
assert.equal(classifyReconciliationEvidence({hasOrderTruth:false,hasContractTruth:true,hasPayoutTruth:true,hasOrderLevelPayoutAllocation:false,variance:25}),"unallocated_batch_difference");
assert.equal(classifyReconciliationEvidence({hasOrderTruth:true,hasContractTruth:false,hasPayoutTruth:true,hasOrderLevelPayoutAllocation:true,variance:25}),"insufficient_evidence");
assert.match(evidenceFingerprint({merchant:"demo",amount:10}),/^[a-f0-9]{64}$/);

const prepared=prepareMerchantEvidenceIntake({accountId:" account-1 ",merchantId:"merchant-1",sourceKind:"forwarded_email",sourceProvider:" Gmail ",sourceExternalId:"message-1",documentKind:"payout_notice",contentSha256:"A".repeat(64),mediaType:"application/pdf",originalFilename:"payout.pdf"});
assert.equal(prepared.account_id,"account-1");
assert.equal(prepared.source_provider,"gmail");
assert.equal(prepared.content_sha256,"a".repeat(64));
assert.throws(()=>prepareMerchantEvidenceIntake({...prepared,accountId:"account-1",merchantId:"merchant-1",sourceKind:"forwarded_email",sourceProvider:"gmail",sourceExternalId:"message-1",documentKind:"payout_notice",contentSha256:"not-a-hash"} as any),/SHA-256/);

const normalized=buildNormalizedCommerceEvents({accountId:"account-1",merchantId:"merchant-1",evidenceItemId:"evidence-1",sourceKind:"file_upload",sourceProvider:"talabat",documentKind:"settlement_report",result:{ok:true,platform:"talabat",currency:"QAR",period_start:"2026-08-01",period_end:"2026-08-07",expected_payout:82,sub_total_sum:100,commission_amount:18,transaction_rows:[{order_id:"ORDER-1",date:"2026-08-01",gross_sales:100,refund_amount:10,status:"delivered",eligible:true,claims_ready:true}],settlement_rows:[{settlement_reference:"SET-1",order_id:"ORDER-1",amount:82,currency:"QAR"}]}});
assert.deepEqual(normalized.events.map(event=>event.event_kind),["order_snapshot","refund","settlement_line","payout_total"]);
assert(normalized.events.every(event=>/^[a-f0-9]{64}$/.test(event.event_fingerprint)));
assert.equal(normalized.events.find(event=>event.event_kind==="refund")?.net_amount,-10);

const aggregateOnly=buildNormalizedCommerceEvents({accountId:"account-1",merchantId:"merchant-1",evidenceItemId:"evidence-2",sourceKind:"file_upload",sourceProvider:"snoonu",documentKind:"order_summary",result:{ok:true,platform:"snoonu",daily_rows:[{date:"2026-08-01",orders:4,sales:200}]}});
assert.equal(aggregateOnly.events.length,0);
assert(aggregateOnly.limitations.some(value=>value.includes("fictional order")));

const adjustment=buildNormalizedCommerceEvents({accountId:"account-1",merchantId:"merchant-1",evidenceItemId:"evidence-adjustment",sourceKind:"file_upload",sourceProvider:"talabat",documentKind:"credit_note",result:{ok:true,platform:"talabat",currency:"QAR",period_end:"2026-08-07",adjustment_amount:25,adjustment_direction:"credit",adjustment_reason:"Fee correction",order_references:["ORDER-1"]}});
assert.equal(adjustment.events[0].event_kind,"commercial_adjustment");assert.equal(adjustment.events[0].net_amount,25);assert.equal(adjustment.events[0].order_external_id,"ORDER-1");
const uncertainAdjustment=buildNormalizedCommerceEvents({accountId:"account-1",merchantId:"merchant-1",evidenceItemId:"evidence-adjustment-2",sourceKind:"file_upload",sourceProvider:"talabat",documentKind:"adjustment_notice",result:{ok:true,adjustment_amount:10,adjustment_direction:"unknown"}});
assert.equal(uncertainAdjustment.events[0].net_amount,null);assert(uncertainAdjustment.events[0].limitations.some(value=>value.includes("credit or debit")));
const promotion=buildNormalizedCommerceEvents({accountId:"account-1",merchantId:"merchant-1",evidenceItemId:"evidence-promo",sourceKind:"file_upload",sourceProvider:"talabat",documentKind:"promotion_confirmation",result:{ok:true,currency:"QAR",promotion_discount_total:20,platform_funding_amount:12,merchant_funding_amount:8}});
assert.equal(promotion.events[0].event_kind,"promotion_term");assert.equal(promotion.events[0].discount_amount,20);
const receipt=buildNormalizedCommerceEvents({accountId:"account-1",merchantId:"merchant-1",evidenceItemId:"evidence-receipt",sourceKind:"file_upload",sourceProvider:"talabat",documentKind:"merchant_confirmation",result:{ok:true,currency:"QAR",received_amount:82,confirmation_reference:"CONF-1",settlement_references:["SET-1"]}});
assert.equal(receipt.events[0].event_kind,"receipt_confirmation");assert.equal(receipt.events[0].evidence_strength,"confirmed");

const shadowInput=buildNormalizedReconciliationInput(normalized.events,{
  id:"contract-1",platform:"talabat",contract_name:"Reviewed agreement",commission_rate_pct:10,vat_on_fees_pct:5,payment_fee_pct:2,fixed_order_fee:1,delivery_contribution:2,commission_base:"eligible_sales",promotion_funding_platform_pct:null,refund_liability:"merchant",cancellation_liability:"merchant",settlement_frequency:null,settlement_days:null,settlement_day_basis:null,settlement_schedule_type:null,settlement_weekday:null,settlement_month_days:[],settlement_cutoff_hour:null,settlement_timezone:null,settlement_weekend_days:[],settlement_holidays:[],settlement_reserve_days:0,minimum_payout_threshold:null,dispute_deadline_days:null,advertising_commitment:null,minimum_spend:null,currency:"QAR",coverage_legal_entity:null,coverage_brands:[],coverage_branches:[],effective_from:"2026-01-01",effective_to:null,status:"approved",source_file_name:null,source_sha256:null,notes:null,reviewed_by:"owner",approved_at:"2026-01-01T00:00:00Z",created_at:"2026-01-01T00:00:00Z",extraction_json:null,extraction_model:null,extraction_confidence:null,extracted_at:null,
});
assert.equal(shadowInput.orders[0].amount,75.75);
assert.equal(shadowInput.settlements[0].amount,82);
const shadowWithReceipt=buildNormalizedReconciliationInput([...normalized.events,...receipt.events],null);
assert.equal(shadowWithReceipt.receipts[0].bankReference,"CONF-1");assert.equal(shadowWithReceipt.receipts[0].amount,82);
const noContract=buildNormalizedReconciliationInput(normalized.events,null);
assert.equal(noContract.orders.length,0);
assert(noContract.limitations.some(value=>value.includes("approved")));
assert.deepEqual(compareShadowParity(75.75,75.75),{state:"matching",difference:0});
assert.deepEqual(compareShadowParity(75.75,82),{state:"mismatch",difference:-6.25});
assert.deepEqual(compareShadowParity(null,82),{state:"not_comparable",difference:null});
assert.deepEqual(reconciliationCoverage([{event_kind:"payout_total",channel:"talabat",order_external_id:null,settlement_reference:"SET-1",occurred_at:"2026-08-07T00:00:00Z",currency:"QAR",gross_amount:null,net_amount:90,normalized_payload:{period_start:"2026-08-01",period_end:"2026-08-07"},evidence_strength:"strong",event_fingerprint:"x"}]),{start:"2026-08-01",end:"2026-08-07"});
assert.deepEqual(assessReconciliationReadiness({orderCount:2,settlementCount:2,contractTermId:"contract-1",allocatedSettlementCount:2,strongOrderCount:2,currencyCount:1}).state,"ready");
const blockedReadiness=assessReconciliationReadiness({orderCount:0,settlementCount:1,contractTermId:null,allocatedSettlementCount:0,strongOrderCount:0,currencyCount:1});assert.equal(blockedReadiness.state,"blocked");assert(blockedReadiness.missing.some(item=>item.includes("order-level")));assert(blockedReadiness.missing.some(item=>item.includes("agreement")));
assert.deepEqual(classifyAllocationFinding({expectedAmount:100,settledAmount:90,orderId:"ORDER-1",matchBasis:"exact_order_reference",contractTermId:"contract-1",evidenceStrength:"confirmed",blockers:[]}),{conclusion:"confirmed_discrepancy",recoverability:"claims_ready",variance:-10,explanation:"Order, agreement and allocated payout evidence support a specific discrepancy."});
assert.equal(classifyAllocationFinding({expectedAmount:100,settledAmount:90,orderId:null,matchBasis:"unmatched",contractTermId:"contract-1",evidenceStrength:"partial",blockers:[]}).conclusion,"unallocated_batch_difference");
assert.equal(classifyAllocationFinding({expectedAmount:100,settledAmount:110,orderId:"ORDER-1",matchBasis:"exact_order_reference",contractTermId:"contract-1",evidenceStrength:"confirmed",blockers:[]}).recoverability,"review_required");
const recoveryDraft=buildRecoveryCaseFromFinding({id:"finding-1",run_id:"run-1",account_id:"account-1",evidence_item_id:"evidence-1",contract_term_id:"contract-1",conclusion:"confirmed_discrepancy",recoverability:"claims_ready",order_external_id:"ORDER-1",settlement_reference:"SET-1",currency:"QAR",expected_amount:100,reported_amount:90,variance:-10,evidence_strength:"confirmed",explanation:"Supported difference.",blockers:[]});
assert.equal(recoveryDraft.status,"ready");assert.equal(recoveryDraft.claims_ready_amount,10);assert.equal(recoveryDraft.reconciliation_finding_id,"finding-1");
const incompleteRecovery=buildRecoveryCaseFromFinding({...recoveryDraft.calculation,id:"finding-2",run_id:"run-1",account_id:"account-1",evidence_item_id:"evidence-1",contract_term_id:null,conclusion:"probable_discrepancy",recoverability:"review_required",order_external_id:"ORDER-2",settlement_reference:"SET-1",currency:"QAR",expected_amount:100,reported_amount:90,variance:-10,evidence_strength:"partial",explanation:"Possible difference.",blockers:["Missing agreement."]} as any);
assert.equal(incompleteRecovery.status,"evidence_required");assert.equal(incompleteRecovery.claims_ready_amount,0);
const attentionGroups=buildReconciliationAttentionGroups([{id:"finding-1",run_id:"run-1",conclusion:"confirmed_discrepancy",recoverability:"claims_ready",currency:"QAR",variance:-10,evidence_strength:"confirmed",explanation:"Supported."},{id:"finding-2",run_id:"run-1",conclusion:"confirmed_discrepancy",recoverability:"claims_ready",currency:"QAR",variance:-5,evidence_strength:"confirmed",explanation:"Supported."},{id:"finding-3",run_id:"run-1",conclusion:"reconciled",recoverability:"none",currency:"QAR",variance:0,evidence_strength:"confirmed",explanation:"Matched."}],[]);
assert.equal(attentionGroups.length,1);assert.equal(attentionGroups[0].amount,15);assert.equal(attentionGroups[0].findingIds.length,2);
assert.equal(buildReconciliationAttentionGroups([{id:"finding-1",run_id:"run-1",conclusion:"confirmed_discrepancy",recoverability:"claims_ready",currency:"QAR",variance:-10,evidence_strength:"confirmed",explanation:"Supported."}],[{reconciliation_finding_id:"finding-1"}]).length,0);
const manifestFingerprint=fingerprintRecoveryEvidenceManifest({pack_version:"v1",documents:[{id:"evidence-1",content_sha256:"a".repeat(64)}],calculation:{expected:100,reported:90}});assert.match(manifestFingerprint,/^[a-f0-9]{64}$/);assert.equal(manifestFingerprint,fingerprintRecoveryEvidenceManifest({pack_version:"v1",documents:[{id:"evidence-1",content_sha256:"a".repeat(64)}],calculation:{expected:100,reported:90}}));
const globalAgreement={id:"agreement-global",platform:"jahez",status:"approved",effective_from:"2026-01-01",effective_to:null,currency:"SAR",coverage_branches:[],coverage_brands:[],coverage_legal_entity:null} as any;
const exactAgreementMatch=rankAgreementCandidates([globalAgreement],{platform:"jahez",periodStart:"2026-08-01",periodEnd:"2026-08-07",currency:"SAR",branch:null,brand:null,legalEntity:null});
assert.equal(exactAgreementMatch.state,"automatic");assert.equal(exactAgreementMatch.contract?.id,"agreement-global");
const scopedAgreement={...globalAgreement,id:"agreement-doha",coverage_branches:["Doha"]};
assert.equal(rankAgreementCandidates([scopedAgreement],{platform:"jahez",periodStart:"2026-08-01",periodEnd:"2026-08-07",currency:"SAR",branch:null,brand:null,legalEntity:null}).state,"needs_confirmation");
assert.equal(rankAgreementCandidates([globalAgreement],{platform:"jahez",periodStart:"2026-08-01",periodEnd:"2026-08-07",currency:"QAR",branch:null,brand:null,legalEntity:null}).state,"no_match");
const aprilAgreement={...globalAgreement,id:"agreement-april",effective_from:"2026-01-01",effective_to:"2026-05-31"},juneAgreement={...globalAgreement,id:"agreement-june",effective_from:"2026-06-01",effective_to:null};
assert.equal(rankAgreementCandidates([aprilAgreement,juneAgreement],{platform:"jahez",periodStart:"2026-04-01",periodEnd:"2026-04-30",currency:"SAR",branch:null,brand:null,legalEntity:null}).contract?.id,"agreement-april");
assert.equal(rankAgreementCandidates([aprilAgreement,juneAgreement],{platform:"jahez",periodStart:"2026-08-01",periodEnd:"2026-08-31",currency:"SAR",branch:null,brand:null,legalEntity:null}).contract?.id,"agreement-june");
const inboundBody=JSON.stringify({recipient:"merchant@example.test",message_id:"message-1"}),inboundSecret="test-secret";
const inboundSignature=createHmac("sha256",inboundSecret).update(inboundBody).digest("hex");
assert.equal(verifyInboundEmailSignature(inboundBody,inboundSignature,inboundSecret),true);
assert.equal(verifyInboundEmailSignature(`${inboundBody}x`,inboundSignature,inboundSecret),false);
assert.equal(inferEvidencePlatform("Payout from Talabat"),"talabat");
assert.equal(classifyStructuredText("Order ID,Date,Sales,Status\n1,2026-08-01,100,delivered","unknown"),"order_export");
assert.equal(detectEvidenceLayout("Order ID,Date,Sales,Status\n1,2026-08-01,100,delivered").profile,"order_transaction_v1");
assert.equal(detectEvidenceLayout("Date,Orders,GMV\n2026-08-01,2,100").profile,"daily_order_summary_v1");
assert.equal(detectEvidenceLayout("Mystery,Amount\nvalue,100").supported,false);
const processedCsv=await extractStructuredEvidence({bytes:Buffer.from("Order ID,Date,Sales,Status,Settlement Reference,Settlement Amount,Currency\nORDER-1,2026-08-01,100,delivered,SET-1,88,QAR"),mediaType:"text/csv",filename:"orders.csv",documentKind:"unknown",platformHint:"talabat"});
assert.equal(processedCsv.ok,true);
if(processedCsv.ok){assert.equal(processedCsv.result.transaction_rows?.length,1);assert.equal(processedCsv.result.settlement_rows?.length,1);}
const workbook=await writeXlsxFile([{sheet:"Doha",data:[["Order ID","Date","Sales","Status"],["J-1","2026-08-01",100,"delivered"]]},{sheet:"Lusail",data:[["Order ID","Date","Sales","Status"],["J-2","2026-08-02",150,"delivered"]]},{sheet:"Read me",data:[["Notes"],["Not financial data"]]}]).toBuffer();
const processedWorkbook=await extractStructuredEvidence({bytes:workbook,mediaType:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",filename:"jahez-orders.xlsx",documentKind:"order_export",platformHint:"jahez"});
assert.equal(processedWorkbook.ok,true);
if(processedWorkbook.ok){assert.equal(processedWorkbook.result.transaction_rows?.length,2);assert.equal(processedWorkbook.result.order_count,2);assert.equal((processedWorkbook.quality as any).sheet_count,3);assert.equal((processedWorkbook.quality as any).parsed_sheet_count,2);}
const legacyWorkbook=await extractStructuredEvidence({bytes:Buffer.from("legacy"),mediaType:"application/vnd.ms-excel",filename:"legacy.xls",documentKind:"order_export",platformHint:"jahez"});assert.equal(legacyWorkbook.ok,false);if(!legacyWorkbook.ok)assert.equal(legacyWorkbook.errorCode,"LEGACY_XLS_UNSUPPORTED");
assert.equal(assessPdfTextQuality(["Settlement report with enough readable commercial evidence ".repeat(3)]).usable,true);
assert.equal(assessPdfTextQuality(["","scanned"]).usable,false);
const ocrDraft=sanitizeOcrEvidenceDraft({document_kind:"settlement_report",platform:" Talabat ",currency:"qar",branch_external_id:" Doha-01 ",brand:"Main Kitchen",legal_entity:"Prize Foods LLC",payout_total:88.125,adjustment_amount:12.345,adjustment_direction:"credit",received_amount:80,confirmation_reference:" CONF-1 ",confidence:1.4,order_references:[" ORDER-1 "],settlement_references:["SET-1"],evidence:[{field:"payout_total",value:"88.13",source_quote:"Total payout QAR 88.13",page:1,confidence:.9}],missing_information:["order allocation"],warnings:[]});
assert.equal(ocrDraft.payout_total,88.13);assert.equal(ocrDraft.branch_external_id,"Doha-01");assert.equal(ocrDraft.legal_entity,"Prize Foods LLC");assert.equal(ocrDraft.adjustment_amount,12.35);assert.equal(ocrDraft.confirmation_reference,"CONF-1");assert.equal(ocrDraft.confidence,1);assert.equal(ocrDraft.platform,"talabat");assert.equal(ocrDraft.evidence.length,1);
assert.deepEqual(allowedRecoveryTransitions("platform_review"),["accepted","rejected"]);assert.doesNotThrow(()=>assertRecoveryTransition("accepted","recovered"));assert.throws(()=>assertRecoveryTransition("ready","recovered"),/cannot move directly/);
const copilotEvidence=summarizeCopilotFinancialEvidence({runs:[{id:"run-1",platform:"talabat",currency:"QAR",status:"completed",summary:{claims_ready_amount:10}}],findings:[{id:"finding-1",run_id:"run-1",recoverability:"claims_ready",variance:-10,currency:"QAR"}],contracts:[],cases:[],evidenceCount:3});assert.equal(copilotEvidence.findings.claims_ready_amount,10);assert.equal(copilotEvidence.reviewed_evidence_count,3);assert.equal((copilotEvidence as any).raw_document_content,undefined);
assert.deepEqual(classifyLayoutDrift("new",["old"]),{drift:true,firstSeen:false});assert.deepEqual(classifyLayoutDrift("known",["known"]),{drift:false,firstSeen:false});assert.deepEqual(classifyLayoutDrift("first",[]),{drift:false,firstSeen:true});
const evidenceSource=prepareEvidenceSource({provider:" Foodics ",connectionKind:"optional_api",permissions:["completed_orders","refunds"],branches:["Riyadh-1"]});assert.equal(evidenceSource.provider,"foodics");assert.equal(evidenceSource.read_only,true);assert.throws(()=>prepareEvidenceSource({provider:"foodics",connectionKind:"optional_api",permissions:["write_orders"]}),/read-only/);
assert.equal(assessEvidenceSourceHealth({status:"active",last_success_at:"2026-08-20T00:00:00Z",expected_sync_interval_minutes:1440},Date.parse("2026-08-22T00:00:00Z")).state,"late");assert.equal(assessEvidenceSourceHealth({status:"active",last_sync_at:"2026-08-21T01:00:00Z",last_success_at:"2026-08-21T00:00:00Z",last_error:"timeout"}).state,"failed");
const lateSource={id:"source-1",provider:"foodics",connection_kind:"optional_api",status:"active",last_sync_at:"2026-08-20T00:00:00Z",last_success_at:"2026-08-20T00:00:00Z",last_error:null,expected_sync_interval_minutes:1440};const lateAttention=buildEvidenceSourceAttention(lateSource,Date.parse("2026-08-22T00:00:00Z"));assert.equal(lateAttention?.fingerprint,"evidence-source:source-1");assert.match(lateAttention?.detail??"",/cannot confirm/i);assert.equal(buildEvidenceSourceAttention({...lateSource,status:"paused"},Date.parse("2026-08-22T00:00:00Z")),null);
const sourceCoverage=summarizeEvidenceSourceCoverage([{state:"completed",records_seen:3,evidence_period_start:"2026-08-20T08:00:00Z",evidence_period_end:"2026-08-20T10:00:00Z",final_records:2,non_final_records:1,channels:["talabat"],currencies:["SAR"],branch_references:["branch-1"],finished_at:"2026-08-20T10:01:00Z"}]);assert.equal(sourceCoverage.records_seen,3);assert.equal(sourceCoverage.non_final_records,1);assert.equal(sourceCoverage.completeness,"not_guaranteed");assert.equal(sourceCoverage.period_end,"2026-08-20T10:00:00.000Z");
assert.deepEqual(retainCurrentEventRevisions([{id:"partial",final:false},{id:"final",final:true}],new Set(["final"])),[{id:"final",final:true}]);
const sourceOrders=prepareSourceOrderBatch([{external_event_id:"evt-1",order_id:"ORDER-1",occurred_at:"2026-08-20T12:00:00Z",channel:" Foodics ",currency:"sar",gross_amount:100,discount_amount:10,tax_amount:5,customer_email:"must-not-be-retained",final:true}]);assert.equal(sourceOrders[0].channel,"foodics");assert.equal(sourceOrders[0].discount_amount,10);assert.equal((sourceOrders[0] as any).customer_email,undefined);assert.throws(()=>prepareSourceOrderBatch([{external_event_id:"evt-1",order_id:"ORDER-1",occurred_at:"bad",channel:"foodics",currency:"SAR",gross_amount:100}]),/missing a valid/);
assert.doesNotThrow(()=>validateAuthorizedSourceRecords(sourceOrders,["completed_orders","discount_funding","taxes"]));assert.throws(()=>validateAuthorizedSourceRecords(sourceOrders,["completed_orders"]),/discount_funding, taxes/);assert.throws(()=>validateAuthorizedSourceRecords([{...sourceOrders[0],refund_amount:5}],["completed_orders","discount_funding","taxes"]),/refunds/);
assert.equal(assessSourceDeliveryCompleteness(10,10,true).state,"completed");assert.equal(assessSourceDeliveryCompleteness(9,10,true).state,"partial");assert.equal(assessSourceDeliveryCompleteness(10,null,false).state,"partial");

console.log("API-independent evidence foundation verification passed.");
