import {useCallback,useEffect,useMemo,useState,type CSSProperties} from "react";
import {AlertTriangle,CheckCircle2,ChevronRight,FileText,Inbox,Loader2,ShieldCheck,XCircle} from "lucide-react";

type AgreementMatch={id:string;state:string;contract_term_id:string|null;match_score:number;reasons:string[];blockers:string[];candidates:Array<{id:string;contract_name:string;platform:string;effective_from:string;effective_to:string|null;currency:string|null;coverage_branches:string[]}>;confirmed_by:string|null;confirmed_at:string|null};
type ReconciliationFinding={id:string;conclusion:string;recoverability:string;order_external_id:string|null;settlement_reference:string|null;currency:string;expected_amount:number|null;reported_amount:number|null;variance:number|null;evidence_strength:string;explanation:string;blockers:string[];recovery_case:{id:string;status:string}|null};
type Review={id:string;document_kind:string;platform:string|null;extraction_payload:Record<string,any>;source_citations:Array<{field?:string;value?:string;source_quote?:string;page?:number|null;confidence?:number}>;missing_information:string[];warnings:string[];confidence:number|null;status:string;created_at:string;decision_record:{decision:string;reviewer_email:string|null;decided_at:string;correction_summary:string|null}|null;agreement_match:AgreementMatch|null;reconciliation_findings:ReconciliationFinding[];reconciliation_run:{id:string;status:string;summary:{readiness?:{state:string;score:number;missing:string[]};evidence_item_ids?:string[]}}|null;item:{original_filename:string|null;media_type:string|null;received_at:string;source_provider:string}|null;original_url:string|null};
type ProcessingStatus={queued:number;processing:number;completed:number;failed:number;stalled:boolean;last_heartbeat:string|null;failed_documents:Array<{id:string;original_filename:string|null;last_error:string|null;attempts:number;max_attempts:number}>};
const FIELDS=["document_kind","platform","currency","branch_external_id","brand","legal_entity","period_start","period_end","payout_total","gross_total","commission_total","other_charges_total","adjustment_amount","adjustment_direction","adjustment_reason","promotion_discount_total","platform_funding_amount","merchant_funding_amount","cancellation_amount","received_amount","confirmation_reference","settlement_reference","expected_payout","sub_total_sum","commission_amount","additional_charges"];
const CONTRACT_FIELDS=["contract_name","platform","commission_rate_pct","vat_on_fees_pct","payment_fee_pct","fixed_order_fee","delivery_contribution","commission_base","promotion_funding_platform_pct","settlement_frequency","settlement_days","dispute_deadline_days","currency","effective_from","effective_to","coverage_legal_entity","coverage_brands","coverage_branches"];
const labels:Record<string,string>={document_kind:"Document type",platform:"Platform",currency:"Currency",period_start:"Period start",period_end:"Period end",payout_total:"Payout total",gross_total:"Gross total",commission_total:"Commission total",other_charges_total:"Other charges",adjustment_amount:"Adjustment amount",adjustment_direction:"Adjustment direction",adjustment_reason:"Adjustment reason",promotion_discount_total:"Promotion discount total",platform_funding_amount:"Platform-funded amount",merchant_funding_amount:"Merchant-funded amount",cancellation_amount:"Cancellation amount",received_amount:"Payment received",confirmation_reference:"Confirmation reference",settlement_reference:"Settlement reference",expected_payout:"Expected payout",sub_total_sum:"Gross sales",commission_amount:"Commission",additional_charges:"Additional charges",contract_name:"Agreement name",commission_rate_pct:"Commission %",vat_on_fees_pct:"VAT on fees %",payment_fee_pct:"Payment fee %",fixed_order_fee:"Fixed fee per order",delivery_contribution:"Delivery contribution",commission_base:"Commission calculation base",promotion_funding_platform_pct:"Platform-funded promotion %",settlement_frequency:"Settlement frequency",settlement_days:"Settlement delay (days)",dispute_deadline_days:"Dispute deadline (days)",effective_from:"Effective from",effective_to:"Effective to",coverage_legal_entity:"Covered legal entity",coverage_brands:"Covered brands",coverage_branches:"Covered branches"};
Object.assign(labels,{branch_external_id:"Branch reference",brand:"Brand",legal_entity:"Legal entity"});
const credentials=()=>({merchant_id:localStorage.getItem("ps_merchant_id")??"",access_code:localStorage.getItem("ps_access_code")??""});
const editablePayload=(review:Review)=>review.extraction_payload.format==="structured"?{...review.extraction_payload.result}:review.extraction_payload.format==="contract_terms"?{...review.extraction_payload.extraction,document_kind:review.extraction_payload.document_kind}:{...review.extraction_payload};

export function EvidenceReviewWorkspace(){
  const [reviews,setReviews]=useState<Review[]>([]),[status,setStatus]=useState<ProcessingStatus|null>(null),[selected,setSelected]=useState<Review|null>(null),[edited,setEdited]=useState<Record<string,any>>({}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const load=useCallback(async(id?:string)=>{const auth=credentials(),params=new URLSearchParams(id?{draft_id:id}:{});const response=await fetch(`/api/evidence/reviews?${params}`,{headers:{"x-merchant-id":auth.merchant_id,"x-access-code":auth.access_code}}),body=await response.json();if(!response.ok)throw new Error(body.error??"Reviews could not be loaded.");setStatus(body.processing_status??null);if(id){const review=body.reviews?.[0]??null;setSelected(review);setEdited(review?editablePayload(review):{});}else setReviews(body.reviews??[]);},[]);
  useEffect(()=>{load().catch(e=>setMessage(e.message)).finally(()=>setLoading(false));},[load]);
  const open=async(review:Review)=>{setMessage("");try{await load(review.id);}catch(e){setMessage(e instanceof Error?e.message:"Document could not be opened.");}};
  const isContract=selected?.extraction_payload.format==="contract_terms";
  const visibleFields=useMemo(()=>(isContract?CONTRACT_FIELDS:FIELDS).filter(key=>key in edited||["document_kind","platform","currency"].includes(key)),[edited,isContract]);
  const decide=async(decision:"approved"|"rejected")=>{if(!selected||busy)return;const reason=decision==="rejected"?window.prompt("Why are you rejecting this extraction? This will be kept in the audit record.","")??"":"Merchant reviewed extracted values and source citations.";if(decision==="rejected"&&!reason.trim())return;setBusy(true);setMessage("");try{const reviewedPayload=selected.extraction_payload.format==="structured"?{...selected.extraction_payload,result:edited}:selected.extraction_payload.format==="contract_terms"?{...selected.extraction_payload,extraction:{...edited}}:edited;const response=await fetch("/api/evidence/reviews",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...credentials(),draft_id:selected.id,decision,reviewed_payload:reviewedPayload,correction_summary:reason})}),body=await response.json();if(!response.ok)throw new Error(body.error??"Decision could not be saved.");setMessage(decision==="approved"?(body.contractDraftId?"Reviewed. An editable agreement draft was created; it is not active until separately approved.":`Approved. ${body.eventCount??0} verified financial event(s) were created.`):"Rejected. No financial events were created.");setSelected(null);await load();}catch(e){setMessage(e instanceof Error?e.message:"Decision could not be saved.");}finally{setBusy(false);}};
  const pending=reviews.filter(r=>r.status==="pending"),completed=reviews.filter(r=>r.status!=="pending");
  const unsupported=["unsupported","contract_unsupported"].includes(String(selected?.extraction_payload.format));
  return <div style={{display:"grid",gridTemplateColumns:selected?"minmax(260px,0.8fr) minmax(0,2.2fr)":"1fr",gap:16}}>
    <div style={{display:"flex",flexDirection:"column",gap:12}}>{status&&<section style={card}><div style={sectionHead}><div><h2 style={h2}><Loader2 size={18}/> Processing status</h2><p style={muted}>{status.stalled?"Automatic processing may be stalled.":status.processing?"Documents are being processed.":"Automatic processing is healthy."}</p></div><span style={status.stalled?errorBadge:doneBadge}>{status.stalled?"Attention required":"Operational"}</span></div><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:8}}>{[["Waiting",status.queued],["Processing",status.processing],["Completed",status.completed],["Failed",status.failed]].map(([label,value])=><div key={String(label)} style={metric}><strong style={{fontSize:20}}>{value}</strong><span style={muted}>{label}</span></div>)}</div>{status.failed_documents.map(doc=><div key={doc.id} style={{...row,marginTop:10}}><AlertTriangle size={16} color="#B91C1C"/><span style={{flex:1,fontSize:12}}><strong>{doc.original_filename??"Evidence document"}</strong><span style={{display:"block",color:"#78716C",marginTop:2}}>{doc.last_error??"Processing failed repeatedly."}</span></span><button onClick={async()=>{setBusy(true);try{const response=await fetch("/api/evidence/reviews",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...credentials(),action:"retry_failed",job_id:doc.id})}),body=await response.json();if(!response.ok)throw new Error(body.error);setMessage("Document queued for another processing attempt.");await load();}catch(e){setMessage(e instanceof Error?e.message:"Retry failed.");}finally{setBusy(false);}}} disabled={busy} style={rejectButton}>Retry</button></div>)}</section>}
    <section style={card}><div style={sectionHead}><div><h2 style={h2}><Inbox size={18}/> Review queue</h2><p style={muted}>Only approved values become financial evidence.</p></div><span style={badge}>{pending.length} awaiting</span></div>
      {message&&<div role="status" style={{padding:12,marginBottom:12,borderRadius:8,background:"#FFF7ED",color:"#9A3412",fontSize:13}}>{message}</div>}
      {loading?<div style={empty}><Loader2 size={20}/> Loading documents…</div>:reviews.length===0?<div style={empty}><CheckCircle2 size={28} color="#16A34A"/><strong>Nothing needs review</strong><span>New extracted documents will appear here.</span></div>:<div style={{display:"flex",flexDirection:"column",gap:8}}>{[...pending,...completed].map(review=><button key={review.id} onClick={()=>open(review)} style={{...row,borderColor:selected?.id===review.id?"#EA580C":"#E5E2DB"}}><FileText size={18} color="#6B6B6B"/><span style={{flex:1,minWidth:0,textAlign:"left"}}><strong style={{display:"block",fontSize:13,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{review.item?.original_filename??"Evidence document"}</strong><span style={muted}>{review.platform??review.item?.source_provider??"Unknown source"} · {new Date(review.created_at).toLocaleDateString()}</span></span><span style={review.status==="pending"?pendingBadge:doneBadge}>{review.status.replace("_"," ")}</span><ChevronRight size={15}/></button>)}</div>}
    </section></div>
    {selected&&<section style={card}><div style={sectionHead}><div><h2 style={h2}><ShieldCheck size={18}/> Verify extracted evidence</h2><p style={muted}>{selected.item?.original_filename}</p></div><button onClick={()=>setSelected(null)} style={closeButton} aria-label="Close review">×</button></div>
      <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(300px,1fr))",gap:16}}>
        <div><h3 style={h3}>Original document</h3>{selected.original_url?(selected.item?.media_type?.startsWith("image/")?<img src={selected.original_url} alt="Original evidence" style={preview}/>:<iframe src={selected.original_url} title="Original evidence document" style={preview}/>):<div style={empty}>Original preview is unavailable.</div>}</div>
        <div><h3 style={h3}>{isContract?"Agreement terms":"Extracted values"}</h3>{isContract&&<p style={{...muted,marginBottom:10}}>Reviewing these values creates an editable agreement draft. A separate agreement approval is required before any payout calculation uses it.</p>}<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}>{visibleFields.map(key=><label key={key} style={{fontSize:12,color:"#6B6B6B"}}>{labels[key]??key}<input value={Array.isArray(edited[key])?edited[key].join(", "):edited[key]??""} onChange={e=>setEdited(v=>({...v,[key]:["coverage_brands","coverage_branches"].includes(key)?e.target.value.split(",").map(x=>x.trim()).filter(Boolean):/_pct$|_fee$|contribution$|_days$|total|amount|payout|sales|commission|charges/.test(key)?(e.target.value===""?null:Number(e.target.value)):e.target.value}))} style={input}/></label>)}</div>
          {(selected.missing_information.length>0||selected.warnings.length>0)&&<div style={{marginTop:14,padding:12,border:"1px solid #FDE68A",background:"#FFFBEB",borderRadius:8}}><strong style={{fontSize:12,display:"flex",gap:6}}><AlertTriangle size={15}/> Missing information and warnings</strong>{[...selected.missing_information,...selected.warnings].map((x,i)=><div key={i} style={{fontSize:12,marginTop:6,color:"#92400E"}}>• {x}</div>)}</div>}
        </div>
      </div>
      <h3 style={{...h3,marginTop:18}}>Source citations</h3>{selected.source_citations.length?<div style={{display:"flex",flexDirection:"column",gap:8}}>{selected.source_citations.map((c,i)=><div key={i} style={{padding:10,border:"1px solid #E5E2DB",borderRadius:8,fontSize:12}}><strong>{c.field}: {c.value}</strong><div style={{marginTop:4,color:"#57534E"}}>“{c.source_quote}” {c.page?`— page ${c.page}`:""}</div><div style={{marginTop:3,color:"#9A9A9A"}}>{Math.round((c.confidence??0)*100)}% extraction confidence</div></div>)}</div>:<p style={muted}>No page-level citations were produced. Review the original carefully.</p>}
      {selected.decision_record&&<div style={{marginTop:16,padding:12,border:"1px solid #D6D3D1",borderRadius:8,fontSize:12,color:"#57534E"}}><strong>Permanent review record</strong><div style={{marginTop:5}}>Decision: {selected.decision_record.decision} · By {selected.decision_record.reviewer_email??"verified merchant"} · {new Date(selected.decision_record.decided_at).toLocaleString()}</div>{selected.decision_record.correction_summary&&<div style={{marginTop:4}}>{selected.decision_record.correction_summary}</div>}</div>}
      {selected.agreement_match&&<div style={{marginTop:16,padding:12,border:"1px solid #D6D3D1",borderRadius:8,fontSize:12,color:"#57534E"}}><strong>Agreement match · {selected.agreement_match.state.replace("_"," ")}</strong><div style={{marginTop:5}}>Confidence score: {selected.agreement_match.match_score}/100</div>{selected.agreement_match.reasons.map((reason,i)=><div key={`r${i}`} style={{marginTop:4,color:"#166534"}}>✓ {reason}</div>)}{selected.agreement_match.blockers.map((blocker,i)=><div key={`b${i}`} style={{marginTop:4,color:"#9A3412"}}>• {blocker}</div>)}{selected.agreement_match.state==="needs_confirmation"&&<div style={{display:"flex",flexDirection:"column",gap:7,marginTop:10}}>{selected.agreement_match.candidates.map(term=><button key={term.id} disabled={busy} style={{...row,cursor:"pointer",textAlign:"left"}} onClick={async()=>{setBusy(true);try{const response=await fetch("/api/evidence/reviews",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...credentials(),action:"confirm_agreement",match_id:selected.agreement_match!.id,contract_term_id:term.id})}),body=await response.json();if(!response.ok)throw new Error(body.error??"Agreement could not be confirmed.");setMessage("Agreement confirmed and reconciliation refreshed.");await load(selected.id);}catch(e){setMessage(e instanceof Error?e.message:"Agreement confirmation failed.");}finally{setBusy(false);}}}><ShieldCheck size={15}/><span><strong>{term.contract_name}</strong><span style={{display:"block",color:"#78716C",marginTop:2}}>{term.platform.toUpperCase()} · effective {term.effective_from}{term.effective_to?` to ${term.effective_to}`:" onward"}{term.currency?` · ${term.currency}`:""}</span></span></button>)}</div>}</div>}
      {selected.reconciliation_run?.summary.readiness&&<div style={{marginTop:16,padding:12,border:"1px solid #D6D3D1",borderRadius:8,fontSize:12}}><div style={{display:"flex",justifyContent:"space-between",gap:8}}><strong>Evidence readiness · {selected.reconciliation_run.summary.readiness.state}</strong><span style={selected.reconciliation_run.summary.readiness.score===100?doneBadge:pendingBadge}>{selected.reconciliation_run.summary.readiness.score}%</span></div><div style={{marginTop:5,color:"#78716C"}}>{selected.reconciliation_run.summary.evidence_item_ids?.length??1} approved document(s) used in this reconciliation.</div>{selected.reconciliation_run.summary.readiness.missing.map((item,i)=><div key={i} style={{marginTop:5,color:"#9A3412"}}>• {item}</div>)}</div>}
      {!!selected.reconciliation_findings?.length&&<div style={{marginTop:16}}><h3 style={h3}>Reconciliation conclusions</h3><div style={{display:"flex",flexDirection:"column",gap:8}}>{selected.reconciliation_findings.map(finding=><div key={finding.id} style={{padding:11,border:"1px solid #D6D3D1",borderRadius:8,fontSize:12}}><div style={{display:"flex",justifyContent:"space-between",gap:8}}><strong>{finding.conclusion.replaceAll("_"," ")}</strong><span style={finding.recoverability==="claims_ready"?doneBadge:pendingBadge}>{finding.recoverability.replaceAll("_"," ")}</span></div><div style={{marginTop:5,color:"#57534E"}}>{finding.explanation}</div><div style={{marginTop:5,color:"#78716C"}}>{finding.order_external_id?`Order ${finding.order_external_id}`:"Batch-level evidence"}{finding.variance!==null?` · difference ${finding.currency} ${Math.abs(finding.variance).toFixed(2)}`:""} · {finding.evidence_strength} evidence</div>{finding.blockers.map((blocker,i)=><div key={i} style={{marginTop:4,color:"#9A3412"}}>• {blocker}</div>)}{finding.conclusion!=="reconciled"&&(finding.recovery_case?<div style={{marginTop:8,color:"#166534",fontWeight:700}}>Recovery case prepared · {finding.recovery_case.status.replaceAll("_"," ")}</div>:<button disabled={busy} style={{...approveButton,marginTop:8,padding:"7px 10px"}} onClick={async()=>{setBusy(true);try{const response=await fetch("/api/evidence/reviews",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...credentials(),action:"prepare_recovery",finding_id:finding.id})}),body=await response.json();if(!response.ok)throw new Error(body.error??"Recovery case could not be prepared.");setMessage(body.status==="ready"?"Claims-ready recovery case prepared. Nothing was submitted externally.":"Evidence-required recovery case prepared. Nothing was submitted externally.");await load(selected.id);}catch(e){setMessage(e instanceof Error?e.message:"Recovery case could not be prepared.");}finally{setBusy(false);}}}>Prepare recovery case</button>)}</div>)}</div></div>}
      {unsupported&&selected.status==="pending"&&<div style={{marginTop:16,padding:12,border:"1px solid #FED7AA",borderRadius:8,background:"#FFF7ED",fontSize:12,color:"#9A3412"}}>This layout cannot be approved for financial calculations yet. The original is preserved for a verified parser update.</div>}
      {selected.status==="pending"&&<div style={{display:"flex",justifyContent:"flex-end",gap:10,marginTop:18,paddingTop:16,borderTop:"1px solid #E5E2DB"}}><button disabled={busy} onClick={()=>decide("rejected")} style={rejectButton}><XCircle size={16}/> Reject</button>{!unsupported&&<button disabled={busy} onClick={()=>decide("approved")} style={approveButton}>{busy?<Loader2 size={16}/>:<CheckCircle2 size={16}/>} Approve verified values</button>}</div>}
    </section>}
  </div>;
}

const card:CSSProperties={background:"#FFF",border:"1px solid #E5E2DB",borderRadius:12,padding:18,boxShadow:"0 1px 2px rgba(0,0,0,.03)"},sectionHead:CSSProperties={display:"flex",alignItems:"flex-start",justifyContent:"space-between",gap:12,marginBottom:16},h2:CSSProperties={display:"flex",alignItems:"center",gap:8,fontSize:16,margin:0,color:"#1C1917"},h3:CSSProperties={fontSize:12,textTransform:"uppercase",letterSpacing:".06em",color:"#78716C",margin:"0 0 10px"},muted:CSSProperties={fontSize:12,color:"#78716C",margin:"4px 0 0"},badge:CSSProperties={fontSize:11,fontWeight:700,padding:"4px 8px",borderRadius:99,background:"#FFF7ED",color:"#C2410C"},pendingBadge:CSSProperties={...badge},doneBadge:CSSProperties={...badge,background:"#F5F5F4",color:"#57534E"},errorBadge:CSSProperties={...badge,background:"#FEF2F2",color:"#B91C1C"},metric:CSSProperties={display:"flex",flexDirection:"column",padding:10,borderRadius:8,background:"#FAFAF9"},row:CSSProperties={display:"flex",alignItems:"center",gap:10,padding:11,border:"1px solid",borderRadius:8,background:"#FFF",cursor:"pointer",width:"100%"},empty:CSSProperties={minHeight:120,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:8,color:"#78716C",fontSize:13},preview:CSSProperties={width:"100%",height:480,objectFit:"contain",border:"1px solid #E5E2DB",borderRadius:8,background:"#F5F5F4"},input:CSSProperties={display:"block",width:"100%",marginTop:4,padding:"8px 9px",border:"1px solid #D6D3D1",borderRadius:7,fontSize:13,color:"#1C1917",background:"#FFF"},closeButton:CSSProperties={border:0,background:"transparent",fontSize:24,cursor:"pointer",color:"#78716C"},approveButton:CSSProperties={display:"flex",alignItems:"center",gap:7,border:0,borderRadius:8,padding:"9px 14px",background:"#EA580C",color:"#FFF",fontWeight:700,cursor:"pointer"},rejectButton:CSSProperties={display:"flex",alignItems:"center",gap:7,border:"1px solid #D6D3D1",borderRadius:8,padding:"9px 14px",background:"#FFF",color:"#991B1B",fontWeight:600,cursor:"pointer"};
