import {useCallback,useEffect,useMemo,useState,type CSSProperties} from "react";
import {ExternalLink,FileCheck2,FileQuestion,FileText,Search,ShieldCheck} from "lucide-react";

type EvidenceItem={id:string;source_kind:string;source_provider:string;document_kind:string;observed_at:string|null;received_at:string;media_type:string|null;original_filename:string|null;content_sha256:string;original_retained:boolean;processing_state:string;review_state:string|null};
const credentials=()=>({merchant_id:localStorage.getItem("ps_merchant_id")??"",access_code:localStorage.getItem("ps_access_code")??""});
const title=(value:string)=>value.split(/[_-]+/).map(part=>part.charAt(0).toUpperCase()+part.slice(1)).join(" ");

export function EvidenceLibrary(){
  const [items,setItems]=useState<EvidenceItem[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[query,setQuery]=useState(""),[opening,setOpening]=useState("");
  const load=useCallback(async()=>{const auth=credentials(),response=await fetch("/api/evidence/reviews",{headers:{"x-merchant-id":auth.merchant_id,"x-access-code":auth.access_code}}),body=await response.json();if(!response.ok)throw new Error(body.error??"Evidence library could not be loaded.");setItems(body.evidence_library??[]);},[]);
  useEffect(()=>{load().catch(reason=>setError(reason instanceof Error?reason.message:"Evidence library could not be loaded.")).finally(()=>setLoading(false));},[load]);
  const filtered=useMemo(()=>{const needle=query.trim().toLowerCase();return needle?items.filter(item=>`${item.original_filename??""} ${item.document_kind} ${item.source_provider} ${item.source_kind}`.toLowerCase().includes(needle)):items;},[items,query]);
  const retained=items.filter(item=>item.original_retained).length;
  const openOriginal=async(item:EvidenceItem)=>{setOpening(item.id);setError("");try{const auth=credentials(),response=await fetch(`/api/evidence/reviews?evidence_id=${encodeURIComponent(item.id)}`,{headers:{"x-merchant-id":auth.merchant_id,"x-access-code":auth.access_code}}),body=await response.json();if(!response.ok)throw new Error(body.error??"Original evidence could not be opened.");if(!body.evidence_original_url)throw new Error("The original file was not retained for this evidence record.");window.open(body.evidence_original_url,"_blank","noopener,noreferrer");}catch(reason){setError(reason instanceof Error?reason.message:"Original evidence could not be opened.");}finally{setOpening("");}};
  return <section className="ps-evidence-library" style={card} aria-labelledby="evidence-library-title">
    <div style={heading}><div><div style={eyebrow}>IMMUTABLE EVIDENCE VAULT</div><h2 id="evidence-library-title" style={h2}><ShieldCheck size={18}/> Evidence Library</h2><p style={muted}>Every registered source remains visible. Originals are read-only and open through a five-minute secure link.</p></div><div style={summary}><strong>{items.length}</strong> records · <strong>{retained}</strong> originals retained</div></div>
    <label style={search}><Search size={16}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search filename, provider, or document type"/></label>
    {error&&<div role="status" style={warning}>{error}</div>}
    {loading?<div style={empty}>Loading retained evidence…</div>:items.length===0?<div style={empty}><FileQuestion size={24}/><strong>No evidence has been registered yet</strong><span>Uploaded and automatically sourced documents will appear here.</span></div>:<div style={{overflowX:"auto"}}><table style={table}><thead><tr><th>Document</th><th>Type</th><th>Source</th><th>Received</th><th>State</th><th>Fingerprint</th><th>Original</th></tr></thead><tbody>{filtered.map(item=><tr key={item.id}><td><span style={document}><FileText size={17}/><span><strong>{item.original_filename??"Evidence record"}</strong><small>{item.media_type??"Media type unavailable"}</small></span></span></td><td>{title(item.document_kind)}</td><td><strong>{title(item.source_provider)}</strong><small style={block}>{title(item.source_kind)}</small></td><td>{new Date(item.received_at).toLocaleString()}</td><td><span style={item.processing_state==="dead_letter"?failedBadge:item.review_state==="pending"?reviewBadge:stateBadge}>{item.review_state?`Review ${item.review_state}`:title(item.processing_state)}</span></td><td><code title={item.content_sha256}>{item.content_sha256.slice(0,12)}…</code></td><td>{item.original_retained?<button disabled={opening===item.id} onClick={()=>void openOriginal(item)} style={viewButton}><ExternalLink size={13}/>{opening===item.id?"Opening…":"View original"}</button>:<span style={notRetained}><FileCheck2 size={13}/> Record only</span>}</td></tr>)}</tbody></table></div>}
    <style>{`.ps-evidence-library input{border:0;outline:0;background:transparent;width:100%;font:inherit;color:#1c1917}.ps-evidence-library th{text-align:left;padding:9px 10px;background:#fafaf9;color:#78716c;font-size:10px;text-transform:uppercase;letter-spacing:.04em}.ps-evidence-library td{padding:10px;border-top:1px solid #e7e5e4;color:#44403c;vertical-align:middle}.ps-evidence-library td small{display:block;color:#78716c;margin-top:2px}.ps-evidence-library code{font-size:10.5px;color:#57534e}`}</style>
  </section>;
}

const card:CSSProperties={background:"#fff",border:"1px solid #E7E5E4",borderRadius:12,padding:18,boxShadow:"0 1px 2px rgba(15,23,42,.04)"},heading:CSSProperties={display:"flex",justifyContent:"space-between",alignItems:"flex-start",gap:14,flexWrap:"wrap"},eyebrow:CSSProperties={fontSize:10.5,fontWeight:850,letterSpacing:".08em",color:"#EA580C"},h2:CSSProperties={display:"flex",alignItems:"center",gap:8,fontSize:18,margin:"5px 0 3px",color:"#1C1917"},muted:CSSProperties={fontSize:12,color:"#78716C",margin:0},summary:CSSProperties={fontSize:11.5,color:"#57534E",padding:"7px 10px",borderRadius:99,background:"#F5F5F4"},search:CSSProperties={display:"flex",alignItems:"center",gap:8,border:"1px solid #D6D3D1",borderRadius:9,padding:"8px 10px",margin:"15px 0 12px",color:"#78716C"},table:CSSProperties={width:"100%",borderCollapse:"collapse",minWidth:980,fontSize:11.5},document:CSSProperties={display:"flex",alignItems:"center",gap:8,maxWidth:240},block:CSSProperties={display:"block",color:"#78716C",marginTop:2},stateBadge:CSSProperties={display:"inline-flex",fontSize:10.5,fontWeight:750,padding:"4px 7px",borderRadius:99,background:"#ECFDF3",color:"#166534",whiteSpace:"nowrap"},reviewBadge:CSSProperties={...stateBadge,background:"#FFF7ED",color:"#9A3412"},failedBadge:CSSProperties={...stateBadge,background:"#FEF2F2",color:"#B91C1C"},viewButton:CSSProperties={display:"inline-flex",alignItems:"center",gap:5,border:"1px solid #D6D3D1",borderRadius:7,padding:"6px 8px",background:"#fff",color:"#1C1917",fontSize:10.5,fontWeight:750,cursor:"pointer",whiteSpace:"nowrap"},notRetained:CSSProperties={display:"inline-flex",alignItems:"center",gap:5,color:"#A16207",whiteSpace:"nowrap"},warning:CSSProperties={padding:10,borderRadius:8,background:"#FFF7ED",color:"#9A3412",fontSize:12,marginBottom:10},empty:CSSProperties={minHeight:120,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:7,color:"#78716C",fontSize:12};
