/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RoiCalculatorRouteImport } from './routes/roi-calculator'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MarginDashboardRouteImport } from './routes/margin-dashboard'
import { Route as MarginRouteImport } from './routes/margin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as ApiReferenceRouteImport } from './routes/api-reference'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccessRouteImport } from './routes/access'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarginDashboardIndexRouteImport } from './routes/margin-dashboard.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StoreSlugRouteImport } from './routes/store.$slug'
import { Route as ProductsPromotionsRouteImport } from './routes/products.promotions'
import { Route as ProductsPricingRouteImport } from './routes/products.pricing'
import { Route as ProductsMarketRouteImport } from './routes/products.market'
import { Route as ProductsFieldIntelRouteImport } from './routes/products.field-intel'
import { Route as ProductsCompetitorsRouteImport } from './routes/products.competitors'
import { Route as MarginDashboardUploadRouteImport } from './routes/margin-dashboard.upload'
import { Route as MarginDashboardSettingsRouteImport } from './routes/margin-dashboard.settings'
import { Route as MarginDashboardItemsRouteImport } from './routes/margin-dashboard.items'
import { Route as MarginDashboardDemoRouteImport } from './routes/margin-dashboard.demo'
import { Route as MarginDashboardChannelsRouteImport } from './routes/margin-dashboard.channels'
import { Route as EmbeddedZidRouteImport } from './routes/embedded/zid'
import { Route as EmbedWidgetRouteImport } from './routes/embed/widget'
import { Route as DocsGuidesRouteImport } from './routes/docs.guides'
import { Route as DocsChangelogRouteImport } from './routes/docs.changelog'
import { Route as DashboardRevenueHubRouteImport } from './routes/dashboard.revenue-hub'
import { Route as DashboardPricingRouteImport } from './routes/dashboard.pricing'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiRestoreRouteImport } from './routes/api/restore'
import { Route as ApiRegisterCodeRouteImport } from './routes/api/register-code'
import { Route as AdminSystemRouteImport } from './routes/admin.system'
import { Route as AdminMerchantsRouteImport } from './routes/admin.merchants'
import { Route as AdminLiveAccessRouteImport } from './routes/admin.live-access'
import { Route as AdminCodesRouteImport } from './routes/admin.codes'
import { Route as AdminChannelsRouteImport } from './routes/admin.channels'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as DocsGuidesWebhooksRouteImport } from './routes/docs.guides.webhooks'
import { Route as DocsGuidesSdkQuickstartRouteImport } from './routes/docs.guides.sdk-quickstart'
import { Route as DocsGuidesQuickstartRouteImport } from './routes/docs.guides.quickstart'
import { Route as DocsGuidesAuthenticationRouteImport } from './routes/docs.guides.authentication'
import { Route as DashboardScenariosSlugRouteImport } from './routes/dashboard.scenarios.$slug'
import { Route as ApiWebhooksPlatformRouteImport } from './routes/api/webhooks/$platform'
import { Route as ApiRepricingCatalogRouteImport } from './routes/api/repricing/catalog'
import { Route as ApiRepricingApplyRouteImport } from './routes/api/repricing/apply'
import { Route as ApiDisputeVoucherRouteImport } from './routes/api/dispute/voucher'
import { Route as ApiCopilotStoreRouteImport } from './routes/api/copilot/store'
import { Route as ApiCopilotImagesRouteImport } from './routes/api/copilot/images'
import { Route as ApiCopilotCompileRouteImport } from './routes/api/copilot/compile'
import { Route as ApiChannelsStatusRouteImport } from './routes/api/channels/status'
import { Route as ApiChannelsDisconnectRouteImport } from './routes/api/channels/disconnect'
import { Route as ApiChannelsConnectRouteImport } from './routes/api/channels/connect'
import { Route as ApiAuthZidRouteImport } from './routes/api/auth/zid'
import { Route as ApiAuthSallaRouteImport } from './routes/api/auth/salla'
import { Route as ApiAuthResolveMerchantRouteImport } from './routes/api/auth/resolve-merchant'
import { Route as ApiAuthKeetaRouteImport } from './routes/api/auth/keeta'
import { Route as ApiAuthEmailBridgeRouteImport } from './routes/api/auth/email-bridge'
import { Route as ApiWebhooksZidAppMarketRouteImport } from './routes/api/webhooks/zid/app-market'
import { Route as ApiPublicV1SplatRouteImport } from './routes/api/public/v1/$'
import { Route as ApiPublicHooksWeeklyMarginDigestRouteImport } from './routes/api/public/hooks/weekly-margin-digest'
import { Route as ApiPublicHooksWebhookRetryRouteImport } from './routes/api/public/hooks/webhook-retry'
import { Route as ApiPublicHooksWebhookIntelligenceRetryRouteImport } from './routes/api/public/hooks/webhook-intelligence-retry'
import { Route as ApiPublicHooksScrapeAllRouteImport } from './routes/api/public/hooks/scrape-all'
import { Route as ApiPublicHooksMapMonitorRouteImport } from './routes/api/public/hooks/map-monitor'
import { Route as ApiPublicHooksGroupExpireRouteImport } from './routes/api/public/hooks/group-expire'
import { Route as ApiPublicHooksFlashStartRouteImport } from './routes/api/public/hooks/flash-start'
import { Route as ApiPublicHooksFlashEndRouteImport } from './routes/api/public/hooks/flash-end'
import { Route as ApiPublicHooksDispatchQueueRouteImport } from './routes/api/public/hooks/dispatch-queue'
import { Route as ApiPublicHooksDispatchConfirmationRouteImport } from './routes/api/public/hooks/dispatch-confirmation'
import { Route as ApiPublicHooksCopilotSchedulesRouteImport } from './routes/api/public/hooks/copilot-schedules'
import { Route as ApiAuthZidCallbackRouteImport } from './routes/api/auth/zid/callback'
import { Route as ApiAuthSallaCallbackRouteImport } from './routes/api/auth/salla/callback'
import { Route as ApiAuthKeetaCallbackRouteImport } from './routes/api/auth/keeta/callback'
import { Route as ApiPublicV1WebhooksTestSignatureRouteImport } from './routes/api/public/v1/webhooks.test-signature'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RoiCalculatorRoute = RoiCalculatorRouteImport.update({
  id: '/roi-calculator',
  path: '/roi-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MarginDashboardRoute = MarginDashboardRouteImport.update({
  id: '/margin-dashboard',
  path: '/margin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MarginRoute = MarginRouteImport.update({
  id: '/margin',
  path: '/margin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferenceRoute = ApiReferenceRouteImport.update({
  id: '/api-reference',
  path: '/api-reference',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarginDashboardIndexRoute = MarginDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarginDashboardRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StoreSlugRoute = StoreSlugRouteImport.update({
  id: '/store/$slug',
  path: '/store/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsPromotionsRoute = ProductsPromotionsRouteImport.update({
  id: '/products/promotions',
  path: '/products/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsPricingRoute = ProductsPricingRouteImport.update({
  id: '/products/pricing',
  path: '/products/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsMarketRoute = ProductsMarketRouteImport.update({
  id: '/products/market',
  path: '/products/market',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsFieldIntelRoute = ProductsFieldIntelRouteImport.update({
  id: '/products/field-intel',
  path: '/products/field-intel',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCompetitorsRoute = ProductsCompetitorsRouteImport.update({
  id: '/products/competitors',
  path: '/products/competitors',
  getParentRoute: () => rootRouteImport,
} as any)
const MarginDashboardUploadRoute = MarginDashboardUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => MarginDashboardRoute,
} as any)
const MarginDashboardSettingsRoute = MarginDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MarginDashboardRoute,
} as any)
const MarginDashboardItemsRoute = MarginDashboardItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => MarginDashboardRoute,
} as any)
const MarginDashboardDemoRoute = MarginDashboardDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => MarginDashboardRoute,
} as any)
const MarginDashboardChannelsRoute = MarginDashboardChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => MarginDashboardRoute,
} as any)
const EmbeddedZidRoute = EmbeddedZidRouteImport.update({
  id: '/embedded/zid',
  path: '/embedded/zid',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedWidgetRoute = EmbedWidgetRouteImport.update({
  id: '/embed/widget',
  path: '/embed/widget',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsGuidesRoute = DocsGuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => DocsRoute,
} as any)
const DocsChangelogRoute = DocsChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => DocsRoute,
} as any)
const DashboardRevenueHubRoute = DashboardRevenueHubRouteImport.update({
  id: '/revenue-hub',
  path: '/revenue-hub',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPricingRoute = DashboardPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRestoreRoute = ApiRestoreRouteImport.update({
  id: '/api/restore',
  path: '/api/restore',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegisterCodeRoute = ApiRegisterCodeRouteImport.update({
  id: '/api/register-code',
  path: '/api/register-code',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMerchantsRoute = AdminMerchantsRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLiveAccessRoute = AdminLiveAccessRouteImport.update({
  id: '/live-access',
  path: '/live-access',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCodesRoute = AdminCodesRouteImport.update({
  id: '/codes',
  path: '/codes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChannelsRoute = AdminChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const DocsGuidesWebhooksRoute = DocsGuidesWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => DocsGuidesRoute,
} as any)
const DocsGuidesSdkQuickstartRoute = DocsGuidesSdkQuickstartRouteImport.update({
  id: '/sdk-quickstart',
  path: '/sdk-quickstart',
  getParentRoute: () => DocsGuidesRoute,
} as any)
const DocsGuidesQuickstartRoute = DocsGuidesQuickstartRouteImport.update({
  id: '/quickstart',
  path: '/quickstart',
  getParentRoute: () => DocsGuidesRoute,
} as any)
const DocsGuidesAuthenticationRoute =
  DocsGuidesAuthenticationRouteImport.update({
    id: '/authentication',
    path: '/authentication',
    getParentRoute: () => DocsGuidesRoute,
  } as any)
const DashboardScenariosSlugRoute = DashboardScenariosSlugRouteImport.update({
  id: '/scenarios/$slug',
  path: '/scenarios/$slug',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiWebhooksPlatformRoute = ApiWebhooksPlatformRouteImport.update({
  id: '/api/webhooks/$platform',
  path: '/api/webhooks/$platform',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRepricingCatalogRoute = ApiRepricingCatalogRouteImport.update({
  id: '/api/repricing/catalog',
  path: '/api/repricing/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRepricingApplyRoute = ApiRepricingApplyRouteImport.update({
  id: '/api/repricing/apply',
  path: '/api/repricing/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDisputeVoucherRoute = ApiDisputeVoucherRouteImport.update({
  id: '/api/dispute/voucher',
  path: '/api/dispute/voucher',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCopilotStoreRoute = ApiCopilotStoreRouteImport.update({
  id: '/api/copilot/store',
  path: '/api/copilot/store',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCopilotImagesRoute = ApiCopilotImagesRouteImport.update({
  id: '/api/copilot/images',
  path: '/api/copilot/images',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCopilotCompileRoute = ApiCopilotCompileRouteImport.update({
  id: '/api/copilot/compile',
  path: '/api/copilot/compile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChannelsStatusRoute = ApiChannelsStatusRouteImport.update({
  id: '/api/channels/status',
  path: '/api/channels/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChannelsDisconnectRoute = ApiChannelsDisconnectRouteImport.update({
  id: '/api/channels/disconnect',
  path: '/api/channels/disconnect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChannelsConnectRoute = ApiChannelsConnectRouteImport.update({
  id: '/api/channels/connect',
  path: '/api/channels/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthZidRoute = ApiAuthZidRouteImport.update({
  id: '/api/auth/zid',
  path: '/api/auth/zid',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSallaRoute = ApiAuthSallaRouteImport.update({
  id: '/api/auth/salla',
  path: '/api/auth/salla',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthResolveMerchantRoute = ApiAuthResolveMerchantRouteImport.update({
  id: '/api/auth/resolve-merchant',
  path: '/api/auth/resolve-merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthKeetaRoute = ApiAuthKeetaRouteImport.update({
  id: '/api/auth/keeta',
  path: '/api/auth/keeta',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthEmailBridgeRoute = ApiAuthEmailBridgeRouteImport.update({
  id: '/api/auth/email-bridge',
  path: '/api/auth/email-bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksZidAppMarketRoute = ApiWebhooksZidAppMarketRouteImport.update({
  id: '/api/webhooks/zid/app-market',
  path: '/api/webhooks/zid/app-market',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1SplatRoute = ApiPublicV1SplatRouteImport.update({
  id: '/api/public/v1/$',
  path: '/api/public/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksWeeklyMarginDigestRoute =
  ApiPublicHooksWeeklyMarginDigestRouteImport.update({
    id: '/api/public/hooks/weekly-margin-digest',
    path: '/api/public/hooks/weekly-margin-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWebhookRetryRoute =
  ApiPublicHooksWebhookRetryRouteImport.update({
    id: '/api/public/hooks/webhook-retry',
    path: '/api/public/hooks/webhook-retry',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWebhookIntelligenceRetryRoute =
  ApiPublicHooksWebhookIntelligenceRetryRouteImport.update({
    id: '/api/public/hooks/webhook-intelligence-retry',
    path: '/api/public/hooks/webhook-intelligence-retry',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksScrapeAllRoute = ApiPublicHooksScrapeAllRouteImport.update({
  id: '/api/public/hooks/scrape-all',
  path: '/api/public/hooks/scrape-all',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksMapMonitorRoute =
  ApiPublicHooksMapMonitorRouteImport.update({
    id: '/api/public/hooks/map-monitor',
    path: '/api/public/hooks/map-monitor',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksGroupExpireRoute =
  ApiPublicHooksGroupExpireRouteImport.update({
    id: '/api/public/hooks/group-expire',
    path: '/api/public/hooks/group-expire',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksFlashStartRoute =
  ApiPublicHooksFlashStartRouteImport.update({
    id: '/api/public/hooks/flash-start',
    path: '/api/public/hooks/flash-start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksFlashEndRoute = ApiPublicHooksFlashEndRouteImport.update({
  id: '/api/public/hooks/flash-end',
  path: '/api/public/hooks/flash-end',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDispatchQueueRoute =
  ApiPublicHooksDispatchQueueRouteImport.update({
    id: '/api/public/hooks/dispatch-queue',
    path: '/api/public/hooks/dispatch-queue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDispatchConfirmationRoute =
  ApiPublicHooksDispatchConfirmationRouteImport.update({
    id: '/api/public/hooks/dispatch-confirmation',
    path: '/api/public/hooks/dispatch-confirmation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCopilotSchedulesRoute =
  ApiPublicHooksCopilotSchedulesRouteImport.update({
    id: '/api/public/hooks/copilot-schedules',
    path: '/api/public/hooks/copilot-schedules',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthZidCallbackRoute = ApiAuthZidCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthZidRoute,
} as any)
const ApiAuthSallaCallbackRoute = ApiAuthSallaCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthSallaRoute,
} as any)
const ApiAuthKeetaCallbackRoute = ApiAuthKeetaCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthKeetaRoute,
} as any)
const ApiPublicV1WebhooksTestSignatureRoute =
  ApiPublicV1WebhooksTestSignatureRouteImport.update({
    id: '/api/public/v1/webhooks/test-signature',
    path: '/api/public/v1/webhooks/test-signature',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/admin': typeof AdminRouteWithChildren
  '/api-reference': typeof ApiReferenceRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/margin': typeof MarginRoute
  '/margin-dashboard': typeof MarginDashboardRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/roi-calculator': typeof RoiCalculatorRoute
  '/signup': typeof SignupRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/channels': typeof AdminChannelsRoute
  '/admin/codes': typeof AdminCodesRoute
  '/admin/live-access': typeof AdminLiveAccessRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/system': typeof AdminSystemRoute
  '/api/register-code': typeof ApiRegisterCodeRoute
  '/api/restore': typeof ApiRestoreRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/pricing': typeof DashboardPricingRoute
  '/dashboard/revenue-hub': typeof DashboardRevenueHubRoute
  '/docs/changelog': typeof DocsChangelogRoute
  '/docs/guides': typeof DocsGuidesRouteWithChildren
  '/embed/widget': typeof EmbedWidgetRoute
  '/embedded/zid': typeof EmbeddedZidRoute
  '/margin-dashboard/channels': typeof MarginDashboardChannelsRoute
  '/margin-dashboard/demo': typeof MarginDashboardDemoRoute
  '/margin-dashboard/items': typeof MarginDashboardItemsRoute
  '/margin-dashboard/settings': typeof MarginDashboardSettingsRoute
  '/margin-dashboard/upload': typeof MarginDashboardUploadRoute
  '/products/competitors': typeof ProductsCompetitorsRoute
  '/products/field-intel': typeof ProductsFieldIntelRoute
  '/products/market': typeof ProductsMarketRoute
  '/products/pricing': typeof ProductsPricingRoute
  '/products/promotions': typeof ProductsPromotionsRoute
  '/store/$slug': typeof StoreSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/margin-dashboard/': typeof MarginDashboardIndexRoute
  '/api/auth/email-bridge': typeof ApiAuthEmailBridgeRoute
  '/api/auth/keeta': typeof ApiAuthKeetaRouteWithChildren
  '/api/auth/resolve-merchant': typeof ApiAuthResolveMerchantRoute
  '/api/auth/salla': typeof ApiAuthSallaRouteWithChildren
  '/api/auth/zid': typeof ApiAuthZidRouteWithChildren
  '/api/channels/connect': typeof ApiChannelsConnectRoute
  '/api/channels/disconnect': typeof ApiChannelsDisconnectRoute
  '/api/channels/status': typeof ApiChannelsStatusRoute
  '/api/copilot/compile': typeof ApiCopilotCompileRoute
  '/api/copilot/images': typeof ApiCopilotImagesRoute
  '/api/copilot/store': typeof ApiCopilotStoreRoute
  '/api/dispute/voucher': typeof ApiDisputeVoucherRoute
  '/api/repricing/apply': typeof ApiRepricingApplyRoute
  '/api/repricing/catalog': typeof ApiRepricingCatalogRoute
  '/api/webhooks/$platform': typeof ApiWebhooksPlatformRoute
  '/dashboard/scenarios/$slug': typeof DashboardScenariosSlugRoute
  '/docs/guides/authentication': typeof DocsGuidesAuthenticationRoute
  '/docs/guides/quickstart': typeof DocsGuidesQuickstartRoute
  '/docs/guides/sdk-quickstart': typeof DocsGuidesSdkQuickstartRoute
  '/docs/guides/webhooks': typeof DocsGuidesWebhooksRoute
  '/api/auth/keeta/callback': typeof ApiAuthKeetaCallbackRoute
  '/api/auth/salla/callback': typeof ApiAuthSallaCallbackRoute
  '/api/auth/zid/callback': typeof ApiAuthZidCallbackRoute
  '/api/public/hooks/copilot-schedules': typeof ApiPublicHooksCopilotSchedulesRoute
  '/api/public/hooks/dispatch-confirmation': typeof ApiPublicHooksDispatchConfirmationRoute
  '/api/public/hooks/dispatch-queue': typeof ApiPublicHooksDispatchQueueRoute
  '/api/public/hooks/flash-end': typeof ApiPublicHooksFlashEndRoute
  '/api/public/hooks/flash-start': typeof ApiPublicHooksFlashStartRoute
  '/api/public/hooks/group-expire': typeof ApiPublicHooksGroupExpireRoute
  '/api/public/hooks/map-monitor': typeof ApiPublicHooksMapMonitorRoute
  '/api/public/hooks/scrape-all': typeof ApiPublicHooksScrapeAllRoute
  '/api/public/hooks/webhook-intelligence-retry': typeof ApiPublicHooksWebhookIntelligenceRetryRoute
  '/api/public/hooks/webhook-retry': typeof ApiPublicHooksWebhookRetryRoute
  '/api/public/hooks/weekly-margin-digest': typeof ApiPublicHooksWeeklyMarginDigestRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
  '/api/webhooks/zid/app-market': typeof ApiWebhooksZidAppMarketRoute
  '/api/public/v1/webhooks/test-signature': typeof ApiPublicV1WebhooksTestSignatureRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/api-reference': typeof ApiReferenceRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/margin': typeof MarginRoute
  '/onboarding': typeof OnboardingRoute
  '/roi-calculator': typeof RoiCalculatorRoute
  '/signup': typeof SignupRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/channels': typeof AdminChannelsRoute
  '/admin/codes': typeof AdminCodesRoute
  '/admin/live-access': typeof AdminLiveAccessRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/system': typeof AdminSystemRoute
  '/api/register-code': typeof ApiRegisterCodeRoute
  '/api/restore': typeof ApiRestoreRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/pricing': typeof DashboardPricingRoute
  '/dashboard/revenue-hub': typeof DashboardRevenueHubRoute
  '/docs/changelog': typeof DocsChangelogRoute
  '/docs/guides': typeof DocsGuidesRouteWithChildren
  '/embed/widget': typeof EmbedWidgetRoute
  '/embedded/zid': typeof EmbeddedZidRoute
  '/margin-dashboard/channels': typeof MarginDashboardChannelsRoute
  '/margin-dashboard/demo': typeof MarginDashboardDemoRoute
  '/margin-dashboard/items': typeof MarginDashboardItemsRoute
  '/margin-dashboard/settings': typeof MarginDashboardSettingsRoute
  '/margin-dashboard/upload': typeof MarginDashboardUploadRoute
  '/products/competitors': typeof ProductsCompetitorsRoute
  '/products/field-intel': typeof ProductsFieldIntelRoute
  '/products/market': typeof ProductsMarketRoute
  '/products/pricing': typeof ProductsPricingRoute
  '/products/promotions': typeof ProductsPromotionsRoute
  '/store/$slug': typeof StoreSlugRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/margin-dashboard': typeof MarginDashboardIndexRoute
  '/api/auth/email-bridge': typeof ApiAuthEmailBridgeRoute
  '/api/auth/keeta': typeof ApiAuthKeetaRouteWithChildren
  '/api/auth/resolve-merchant': typeof ApiAuthResolveMerchantRoute
  '/api/auth/salla': typeof ApiAuthSallaRouteWithChildren
  '/api/auth/zid': typeof ApiAuthZidRouteWithChildren
  '/api/channels/connect': typeof ApiChannelsConnectRoute
  '/api/channels/disconnect': typeof ApiChannelsDisconnectRoute
  '/api/channels/status': typeof ApiChannelsStatusRoute
  '/api/copilot/compile': typeof ApiCopilotCompileRoute
  '/api/copilot/images': typeof ApiCopilotImagesRoute
  '/api/copilot/store': typeof ApiCopilotStoreRoute
  '/api/dispute/voucher': typeof ApiDisputeVoucherRoute
  '/api/repricing/apply': typeof ApiRepricingApplyRoute
  '/api/repricing/catalog': typeof ApiRepricingCatalogRoute
  '/api/webhooks/$platform': typeof ApiWebhooksPlatformRoute
  '/dashboard/scenarios/$slug': typeof DashboardScenariosSlugRoute
  '/docs/guides/authentication': typeof DocsGuidesAuthenticationRoute
  '/docs/guides/quickstart': typeof DocsGuidesQuickstartRoute
  '/docs/guides/sdk-quickstart': typeof DocsGuidesSdkQuickstartRoute
  '/docs/guides/webhooks': typeof DocsGuidesWebhooksRoute
  '/api/auth/keeta/callback': typeof ApiAuthKeetaCallbackRoute
  '/api/auth/salla/callback': typeof ApiAuthSallaCallbackRoute
  '/api/auth/zid/callback': typeof ApiAuthZidCallbackRoute
  '/api/public/hooks/copilot-schedules': typeof ApiPublicHooksCopilotSchedulesRoute
  '/api/public/hooks/dispatch-confirmation': typeof ApiPublicHooksDispatchConfirmationRoute
  '/api/public/hooks/dispatch-queue': typeof ApiPublicHooksDispatchQueueRoute
  '/api/public/hooks/flash-end': typeof ApiPublicHooksFlashEndRoute
  '/api/public/hooks/flash-start': typeof ApiPublicHooksFlashStartRoute
  '/api/public/hooks/group-expire': typeof ApiPublicHooksGroupExpireRoute
  '/api/public/hooks/map-monitor': typeof ApiPublicHooksMapMonitorRoute
  '/api/public/hooks/scrape-all': typeof ApiPublicHooksScrapeAllRoute
  '/api/public/hooks/webhook-intelligence-retry': typeof ApiPublicHooksWebhookIntelligenceRetryRoute
  '/api/public/hooks/webhook-retry': typeof ApiPublicHooksWebhookRetryRoute
  '/api/public/hooks/weekly-margin-digest': typeof ApiPublicHooksWeeklyMarginDigestRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
  '/api/webhooks/zid/app-market': typeof ApiWebhooksZidAppMarketRoute
  '/api/public/v1/webhooks/test-signature': typeof ApiPublicV1WebhooksTestSignatureRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/admin': typeof AdminRouteWithChildren
  '/api-reference': typeof ApiReferenceRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/margin': typeof MarginRoute
  '/margin-dashboard': typeof MarginDashboardRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/roi-calculator': typeof RoiCalculatorRoute
  '/signup': typeof SignupRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/channels': typeof AdminChannelsRoute
  '/admin/codes': typeof AdminCodesRoute
  '/admin/live-access': typeof AdminLiveAccessRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/system': typeof AdminSystemRoute
  '/api/register-code': typeof ApiRegisterCodeRoute
  '/api/restore': typeof ApiRestoreRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/pricing': typeof DashboardPricingRoute
  '/dashboard/revenue-hub': typeof DashboardRevenueHubRoute
  '/docs/changelog': typeof DocsChangelogRoute
  '/docs/guides': typeof DocsGuidesRouteWithChildren
  '/embed/widget': typeof EmbedWidgetRoute
  '/embedded/zid': typeof EmbeddedZidRoute
  '/margin-dashboard/channels': typeof MarginDashboardChannelsRoute
  '/margin-dashboard/demo': typeof MarginDashboardDemoRoute
  '/margin-dashboard/items': typeof MarginDashboardItemsRoute
  '/margin-dashboard/settings': typeof MarginDashboardSettingsRoute
  '/margin-dashboard/upload': typeof MarginDashboardUploadRoute
  '/products/competitors': typeof ProductsCompetitorsRoute
  '/products/field-intel': typeof ProductsFieldIntelRoute
  '/products/market': typeof ProductsMarketRoute
  '/products/pricing': typeof ProductsPricingRoute
  '/products/promotions': typeof ProductsPromotionsRoute
  '/store/$slug': typeof StoreSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/margin-dashboard/': typeof MarginDashboardIndexRoute
  '/api/auth/email-bridge': typeof ApiAuthEmailBridgeRoute
  '/api/auth/keeta': typeof ApiAuthKeetaRouteWithChildren
  '/api/auth/resolve-merchant': typeof ApiAuthResolveMerchantRoute
  '/api/auth/salla': typeof ApiAuthSallaRouteWithChildren
  '/api/auth/zid': typeof ApiAuthZidRouteWithChildren
  '/api/channels/connect': typeof ApiChannelsConnectRoute
  '/api/channels/disconnect': typeof ApiChannelsDisconnectRoute
  '/api/channels/status': typeof ApiChannelsStatusRoute
  '/api/copilot/compile': typeof ApiCopilotCompileRoute
  '/api/copilot/images': typeof ApiCopilotImagesRoute
  '/api/copilot/store': typeof ApiCopilotStoreRoute
  '/api/dispute/voucher': typeof ApiDisputeVoucherRoute
  '/api/repricing/apply': typeof ApiRepricingApplyRoute
  '/api/repricing/catalog': typeof ApiRepricingCatalogRoute
  '/api/webhooks/$platform': typeof ApiWebhooksPlatformRoute
  '/dashboard/scenarios/$slug': typeof DashboardScenariosSlugRoute
  '/docs/guides/authentication': typeof DocsGuidesAuthenticationRoute
  '/docs/guides/quickstart': typeof DocsGuidesQuickstartRoute
  '/docs/guides/sdk-quickstart': typeof DocsGuidesSdkQuickstartRoute
  '/docs/guides/webhooks': typeof DocsGuidesWebhooksRoute
  '/api/auth/keeta/callback': typeof ApiAuthKeetaCallbackRoute
  '/api/auth/salla/callback': typeof ApiAuthSallaCallbackRoute
  '/api/auth/zid/callback': typeof ApiAuthZidCallbackRoute
  '/api/public/hooks/copilot-schedules': typeof ApiPublicHooksCopilotSchedulesRoute
  '/api/public/hooks/dispatch-confirmation': typeof ApiPublicHooksDispatchConfirmationRoute
  '/api/public/hooks/dispatch-queue': typeof ApiPublicHooksDispatchQueueRoute
  '/api/public/hooks/flash-end': typeof ApiPublicHooksFlashEndRoute
  '/api/public/hooks/flash-start': typeof ApiPublicHooksFlashStartRoute
  '/api/public/hooks/group-expire': typeof ApiPublicHooksGroupExpireRoute
  '/api/public/hooks/map-monitor': typeof ApiPublicHooksMapMonitorRoute
  '/api/public/hooks/scrape-all': typeof ApiPublicHooksScrapeAllRoute
  '/api/public/hooks/webhook-intelligence-retry': typeof ApiPublicHooksWebhookIntelligenceRetryRoute
  '/api/public/hooks/webhook-retry': typeof ApiPublicHooksWebhookRetryRoute
  '/api/public/hooks/weekly-margin-digest': typeof ApiPublicHooksWeeklyMarginDigestRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
  '/api/webhooks/zid/app-market': typeof ApiWebhooksZidAppMarketRoute
  '/api/public/v1/webhooks/test-signature': typeof ApiPublicV1WebhooksTestSignatureRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/admin'
    | '/api-reference'
    | '/changelog'
    | '/contact'
    | '/dashboard'
    | '/docs'
    | '/forgot-password'
    | '/legal'
    | '/login'
    | '/margin'
    | '/margin-dashboard'
    | '/onboarding'
    | '/roi-calculator'
    | '/signup'
    | '/admin/audit'
    | '/admin/channels'
    | '/admin/codes'
    | '/admin/live-access'
    | '/admin/merchants'
    | '/admin/system'
    | '/api/register-code'
    | '/api/restore'
    | '/auth/callback'
    | '/dashboard/pricing'
    | '/dashboard/revenue-hub'
    | '/docs/changelog'
    | '/docs/guides'
    | '/embed/widget'
    | '/embedded/zid'
    | '/margin-dashboard/channels'
    | '/margin-dashboard/demo'
    | '/margin-dashboard/items'
    | '/margin-dashboard/settings'
    | '/margin-dashboard/upload'
    | '/products/competitors'
    | '/products/field-intel'
    | '/products/market'
    | '/products/pricing'
    | '/products/promotions'
    | '/store/$slug'
    | '/admin/'
    | '/dashboard/'
    | '/margin-dashboard/'
    | '/api/auth/email-bridge'
    | '/api/auth/keeta'
    | '/api/auth/resolve-merchant'
    | '/api/auth/salla'
    | '/api/auth/zid'
    | '/api/channels/connect'
    | '/api/channels/disconnect'
    | '/api/channels/status'
    | '/api/copilot/compile'
    | '/api/copilot/images'
    | '/api/copilot/store'
    | '/api/dispute/voucher'
    | '/api/repricing/apply'
    | '/api/repricing/catalog'
    | '/api/webhooks/$platform'
    | '/dashboard/scenarios/$slug'
    | '/docs/guides/authentication'
    | '/docs/guides/quickstart'
    | '/docs/guides/sdk-quickstart'
    | '/docs/guides/webhooks'
    | '/api/auth/keeta/callback'
    | '/api/auth/salla/callback'
    | '/api/auth/zid/callback'
    | '/api/public/hooks/copilot-schedules'
    | '/api/public/hooks/dispatch-confirmation'
    | '/api/public/hooks/dispatch-queue'
    | '/api/public/hooks/flash-end'
    | '/api/public/hooks/flash-start'
    | '/api/public/hooks/group-expire'
    | '/api/public/hooks/map-monitor'
    | '/api/public/hooks/scrape-all'
    | '/api/public/hooks/webhook-intelligence-retry'
    | '/api/public/hooks/webhook-retry'
    | '/api/public/hooks/weekly-margin-digest'
    | '/api/public/v1/$'
    | '/api/webhooks/zid/app-market'
    | '/api/public/v1/webhooks/test-signature'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/api-reference'
    | '/changelog'
    | '/contact'
    | '/docs'
    | '/forgot-password'
    | '/legal'
    | '/login'
    | '/margin'
    | '/onboarding'
    | '/roi-calculator'
    | '/signup'
    | '/admin/audit'
    | '/admin/channels'
    | '/admin/codes'
    | '/admin/live-access'
    | '/admin/merchants'
    | '/admin/system'
    | '/api/register-code'
    | '/api/restore'
    | '/auth/callback'
    | '/dashboard/pricing'
    | '/dashboard/revenue-hub'
    | '/docs/changelog'
    | '/docs/guides'
    | '/embed/widget'
    | '/embedded/zid'
    | '/margin-dashboard/channels'
    | '/margin-dashboard/demo'
    | '/margin-dashboard/items'
    | '/margin-dashboard/settings'
    | '/margin-dashboard/upload'
    | '/products/competitors'
    | '/products/field-intel'
    | '/products/market'
    | '/products/pricing'
    | '/products/promotions'
    | '/store/$slug'
    | '/admin'
    | '/dashboard'
    | '/margin-dashboard'
    | '/api/auth/email-bridge'
    | '/api/auth/keeta'
    | '/api/auth/resolve-merchant'
    | '/api/auth/salla'
    | '/api/auth/zid'
    | '/api/channels/connect'
    | '/api/channels/disconnect'
    | '/api/channels/status'
    | '/api/copilot/compile'
    | '/api/copilot/images'
    | '/api/copilot/store'
    | '/api/dispute/voucher'
    | '/api/repricing/apply'
    | '/api/repricing/catalog'
    | '/api/webhooks/$platform'
    | '/dashboard/scenarios/$slug'
    | '/docs/guides/authentication'
    | '/docs/guides/quickstart'
    | '/docs/guides/sdk-quickstart'
    | '/docs/guides/webhooks'
    | '/api/auth/keeta/callback'
    | '/api/auth/salla/callback'
    | '/api/auth/zid/callback'
    | '/api/public/hooks/copilot-schedules'
    | '/api/public/hooks/dispatch-confirmation'
    | '/api/public/hooks/dispatch-queue'
    | '/api/public/hooks/flash-end'
    | '/api/public/hooks/flash-start'
    | '/api/public/hooks/group-expire'
    | '/api/public/hooks/map-monitor'
    | '/api/public/hooks/scrape-all'
    | '/api/public/hooks/webhook-intelligence-retry'
    | '/api/public/hooks/webhook-retry'
    | '/api/public/hooks/weekly-margin-digest'
    | '/api/public/v1/$'
    | '/api/webhooks/zid/app-market'
    | '/api/public/v1/webhooks/test-signature'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/admin'
    | '/api-reference'
    | '/changelog'
    | '/contact'
    | '/dashboard'
    | '/docs'
    | '/forgot-password'
    | '/legal'
    | '/login'
    | '/margin'
    | '/margin-dashboard'
    | '/onboarding'
    | '/roi-calculator'
    | '/signup'
    | '/admin/audit'
    | '/admin/channels'
    | '/admin/codes'
    | '/admin/live-access'
    | '/admin/merchants'
    | '/admin/system'
    | '/api/register-code'
    | '/api/restore'
    | '/auth/callback'
    | '/dashboard/pricing'
    | '/dashboard/revenue-hub'
    | '/docs/changelog'
    | '/docs/guides'
    | '/embed/widget'
    | '/embedded/zid'
    | '/margin-dashboard/channels'
    | '/margin-dashboard/demo'
    | '/margin-dashboard/items'
    | '/margin-dashboard/settings'
    | '/margin-dashboard/upload'
    | '/products/competitors'
    | '/products/field-intel'
    | '/products/market'
    | '/products/pricing'
    | '/products/promotions'
    | '/store/$slug'
    | '/admin/'
    | '/dashboard/'
    | '/margin-dashboard/'
    | '/api/auth/email-bridge'
    | '/api/auth/keeta'
    | '/api/auth/resolve-merchant'
    | '/api/auth/salla'
    | '/api/auth/zid'
    | '/api/channels/connect'
    | '/api/channels/disconnect'
    | '/api/channels/status'
    | '/api/copilot/compile'
    | '/api/copilot/images'
    | '/api/copilot/store'
    | '/api/dispute/voucher'
    | '/api/repricing/apply'
    | '/api/repricing/catalog'
    | '/api/webhooks/$platform'
    | '/dashboard/scenarios/$slug'
    | '/docs/guides/authentication'
    | '/docs/guides/quickstart'
    | '/docs/guides/sdk-quickstart'
    | '/docs/guides/webhooks'
    | '/api/auth/keeta/callback'
    | '/api/auth/salla/callback'
    | '/api/auth/zid/callback'
    | '/api/public/hooks/copilot-schedules'
    | '/api/public/hooks/dispatch-confirmation'
    | '/api/public/hooks/dispatch-queue'
    | '/api/public/hooks/flash-end'
    | '/api/public/hooks/flash-start'
    | '/api/public/hooks/group-expire'
    | '/api/public/hooks/map-monitor'
    | '/api/public/hooks/scrape-all'
    | '/api/public/hooks/webhook-intelligence-retry'
    | '/api/public/hooks/webhook-retry'
    | '/api/public/hooks/weekly-margin-digest'
    | '/api/public/v1/$'
    | '/api/webhooks/zid/app-market'
    | '/api/public/v1/webhooks/test-signature'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRoute: typeof AccessRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApiReferenceRoute: typeof ApiReferenceRoute
  ChangelogRoute: typeof ChangelogRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LegalRoute: typeof LegalRoute
  LoginRoute: typeof LoginRoute
  MarginRoute: typeof MarginRoute
  MarginDashboardRoute: typeof MarginDashboardRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  RoiCalculatorRoute: typeof RoiCalculatorRoute
  SignupRoute: typeof SignupRoute
  ApiRegisterCodeRoute: typeof ApiRegisterCodeRoute
  ApiRestoreRoute: typeof ApiRestoreRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  EmbedWidgetRoute: typeof EmbedWidgetRoute
  EmbeddedZidRoute: typeof EmbeddedZidRoute
  ProductsCompetitorsRoute: typeof ProductsCompetitorsRoute
  ProductsFieldIntelRoute: typeof ProductsFieldIntelRoute
  ProductsMarketRoute: typeof ProductsMarketRoute
  ProductsPricingRoute: typeof ProductsPricingRoute
  ProductsPromotionsRoute: typeof ProductsPromotionsRoute
  StoreSlugRoute: typeof StoreSlugRoute
  ApiAuthEmailBridgeRoute: typeof ApiAuthEmailBridgeRoute
  ApiAuthKeetaRoute: typeof ApiAuthKeetaRouteWithChildren
  ApiAuthResolveMerchantRoute: typeof ApiAuthResolveMerchantRoute
  ApiAuthSallaRoute: typeof ApiAuthSallaRouteWithChildren
  ApiAuthZidRoute: typeof ApiAuthZidRouteWithChildren
  ApiChannelsConnectRoute: typeof ApiChannelsConnectRoute
  ApiChannelsDisconnectRoute: typeof ApiChannelsDisconnectRoute
  ApiChannelsStatusRoute: typeof ApiChannelsStatusRoute
  ApiCopilotCompileRoute: typeof ApiCopilotCompileRoute
  ApiCopilotImagesRoute: typeof ApiCopilotImagesRoute
  ApiCopilotStoreRoute: typeof ApiCopilotStoreRoute
  ApiDisputeVoucherRoute: typeof ApiDisputeVoucherRoute
  ApiRepricingApplyRoute: typeof ApiRepricingApplyRoute
  ApiRepricingCatalogRoute: typeof ApiRepricingCatalogRoute
  ApiWebhooksPlatformRoute: typeof ApiWebhooksPlatformRoute
  ApiPublicHooksCopilotSchedulesRoute: typeof ApiPublicHooksCopilotSchedulesRoute
  ApiPublicHooksDispatchConfirmationRoute: typeof ApiPublicHooksDispatchConfirmationRoute
  ApiPublicHooksDispatchQueueRoute: typeof ApiPublicHooksDispatchQueueRoute
  ApiPublicHooksFlashEndRoute: typeof ApiPublicHooksFlashEndRoute
  ApiPublicHooksFlashStartRoute: typeof ApiPublicHooksFlashStartRoute
  ApiPublicHooksGroupExpireRoute: typeof ApiPublicHooksGroupExpireRoute
  ApiPublicHooksMapMonitorRoute: typeof ApiPublicHooksMapMonitorRoute
  ApiPublicHooksScrapeAllRoute: typeof ApiPublicHooksScrapeAllRoute
  ApiPublicHooksWebhookIntelligenceRetryRoute: typeof ApiPublicHooksWebhookIntelligenceRetryRoute
  ApiPublicHooksWebhookRetryRoute: typeof ApiPublicHooksWebhookRetryRoute
  ApiPublicHooksWeeklyMarginDigestRoute: typeof ApiPublicHooksWeeklyMarginDigestRoute
  ApiPublicV1SplatRoute: typeof ApiPublicV1SplatRoute
  ApiWebhooksZidAppMarketRoute: typeof ApiWebhooksZidAppMarketRoute
  ApiPublicV1WebhooksTestSignatureRoute: typeof ApiPublicV1WebhooksTestSignatureRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roi-calculator': {
      id: '/roi-calculator'
      path: '/roi-calculator'
      fullPath: '/roi-calculator'
      preLoaderRoute: typeof RoiCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/margin-dashboard': {
      id: '/margin-dashboard'
      path: '/margin-dashboard'
      fullPath: '/margin-dashboard'
      preLoaderRoute: typeof MarginDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/margin': {
      id: '/margin'
      path: '/margin'
      fullPath: '/margin'
      preLoaderRoute: typeof MarginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-reference': {
      id: '/api-reference'
      path: '/api-reference'
      fullPath: '/api-reference'
      preLoaderRoute: typeof ApiReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/margin-dashboard/': {
      id: '/margin-dashboard/'
      path: '/'
      fullPath: '/margin-dashboard/'
      preLoaderRoute: typeof MarginDashboardIndexRouteImport
      parentRoute: typeof MarginDashboardRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/store/$slug': {
      id: '/store/$slug'
      path: '/store/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof StoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/promotions': {
      id: '/products/promotions'
      path: '/products/promotions'
      fullPath: '/products/promotions'
      preLoaderRoute: typeof ProductsPromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/pricing': {
      id: '/products/pricing'
      path: '/products/pricing'
      fullPath: '/products/pricing'
      preLoaderRoute: typeof ProductsPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/market': {
      id: '/products/market'
      path: '/products/market'
      fullPath: '/products/market'
      preLoaderRoute: typeof ProductsMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/field-intel': {
      id: '/products/field-intel'
      path: '/products/field-intel'
      fullPath: '/products/field-intel'
      preLoaderRoute: typeof ProductsFieldIntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/competitors': {
      id: '/products/competitors'
      path: '/products/competitors'
      fullPath: '/products/competitors'
      preLoaderRoute: typeof ProductsCompetitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/margin-dashboard/upload': {
      id: '/margin-dashboard/upload'
      path: '/upload'
      fullPath: '/margin-dashboard/upload'
      preLoaderRoute: typeof MarginDashboardUploadRouteImport
      parentRoute: typeof MarginDashboardRoute
    }
    '/margin-dashboard/settings': {
      id: '/margin-dashboard/settings'
      path: '/settings'
      fullPath: '/margin-dashboard/settings'
      preLoaderRoute: typeof MarginDashboardSettingsRouteImport
      parentRoute: typeof MarginDashboardRoute
    }
    '/margin-dashboard/items': {
      id: '/margin-dashboard/items'
      path: '/items'
      fullPath: '/margin-dashboard/items'
      preLoaderRoute: typeof MarginDashboardItemsRouteImport
      parentRoute: typeof MarginDashboardRoute
    }
    '/margin-dashboard/demo': {
      id: '/margin-dashboard/demo'
      path: '/demo'
      fullPath: '/margin-dashboard/demo'
      preLoaderRoute: typeof MarginDashboardDemoRouteImport
      parentRoute: typeof MarginDashboardRoute
    }
    '/margin-dashboard/channels': {
      id: '/margin-dashboard/channels'
      path: '/channels'
      fullPath: '/margin-dashboard/channels'
      preLoaderRoute: typeof MarginDashboardChannelsRouteImport
      parentRoute: typeof MarginDashboardRoute
    }
    '/embedded/zid': {
      id: '/embedded/zid'
      path: '/embedded/zid'
      fullPath: '/embedded/zid'
      preLoaderRoute: typeof EmbeddedZidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/widget': {
      id: '/embed/widget'
      path: '/embed/widget'
      fullPath: '/embed/widget'
      preLoaderRoute: typeof EmbedWidgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/guides': {
      id: '/docs/guides'
      path: '/guides'
      fullPath: '/docs/guides'
      preLoaderRoute: typeof DocsGuidesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/changelog': {
      id: '/docs/changelog'
      path: '/changelog'
      fullPath: '/docs/changelog'
      preLoaderRoute: typeof DocsChangelogRouteImport
      parentRoute: typeof DocsRoute
    }
    '/dashboard/revenue-hub': {
      id: '/dashboard/revenue-hub'
      path: '/revenue-hub'
      fullPath: '/dashboard/revenue-hub'
      preLoaderRoute: typeof DashboardRevenueHubRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pricing': {
      id: '/dashboard/pricing'
      path: '/pricing'
      fullPath: '/dashboard/pricing'
      preLoaderRoute: typeof DashboardPricingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/restore': {
      id: '/api/restore'
      path: '/api/restore'
      fullPath: '/api/restore'
      preLoaderRoute: typeof ApiRestoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/register-code': {
      id: '/api/register-code'
      path: '/api/register-code'
      fullPath: '/api/register-code'
      preLoaderRoute: typeof ApiRegisterCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/merchants': {
      id: '/admin/merchants'
      path: '/merchants'
      fullPath: '/admin/merchants'
      preLoaderRoute: typeof AdminMerchantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/live-access': {
      id: '/admin/live-access'
      path: '/live-access'
      fullPath: '/admin/live-access'
      preLoaderRoute: typeof AdminLiveAccessRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/codes': {
      id: '/admin/codes'
      path: '/codes'
      fullPath: '/admin/codes'
      preLoaderRoute: typeof AdminCodesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/channels': {
      id: '/admin/channels'
      path: '/channels'
      fullPath: '/admin/channels'
      preLoaderRoute: typeof AdminChannelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/docs/guides/webhooks': {
      id: '/docs/guides/webhooks'
      path: '/webhooks'
      fullPath: '/docs/guides/webhooks'
      preLoaderRoute: typeof DocsGuidesWebhooksRouteImport
      parentRoute: typeof DocsGuidesRoute
    }
    '/docs/guides/sdk-quickstart': {
      id: '/docs/guides/sdk-quickstart'
      path: '/sdk-quickstart'
      fullPath: '/docs/guides/sdk-quickstart'
      preLoaderRoute: typeof DocsGuidesSdkQuickstartRouteImport
      parentRoute: typeof DocsGuidesRoute
    }
    '/docs/guides/quickstart': {
      id: '/docs/guides/quickstart'
      path: '/quickstart'
      fullPath: '/docs/guides/quickstart'
      preLoaderRoute: typeof DocsGuidesQuickstartRouteImport
      parentRoute: typeof DocsGuidesRoute
    }
    '/docs/guides/authentication': {
      id: '/docs/guides/authentication'
      path: '/authentication'
      fullPath: '/docs/guides/authentication'
      preLoaderRoute: typeof DocsGuidesAuthenticationRouteImport
      parentRoute: typeof DocsGuidesRoute
    }
    '/dashboard/scenarios/$slug': {
      id: '/dashboard/scenarios/$slug'
      path: '/scenarios/$slug'
      fullPath: '/dashboard/scenarios/$slug'
      preLoaderRoute: typeof DashboardScenariosSlugRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/webhooks/$platform': {
      id: '/api/webhooks/$platform'
      path: '/api/webhooks/$platform'
      fullPath: '/api/webhooks/$platform'
      preLoaderRoute: typeof ApiWebhooksPlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/repricing/catalog': {
      id: '/api/repricing/catalog'
      path: '/api/repricing/catalog'
      fullPath: '/api/repricing/catalog'
      preLoaderRoute: typeof ApiRepricingCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/repricing/apply': {
      id: '/api/repricing/apply'
      path: '/api/repricing/apply'
      fullPath: '/api/repricing/apply'
      preLoaderRoute: typeof ApiRepricingApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dispute/voucher': {
      id: '/api/dispute/voucher'
      path: '/api/dispute/voucher'
      fullPath: '/api/dispute/voucher'
      preLoaderRoute: typeof ApiDisputeVoucherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/copilot/store': {
      id: '/api/copilot/store'
      path: '/api/copilot/store'
      fullPath: '/api/copilot/store'
      preLoaderRoute: typeof ApiCopilotStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/copilot/images': {
      id: '/api/copilot/images'
      path: '/api/copilot/images'
      fullPath: '/api/copilot/images'
      preLoaderRoute: typeof ApiCopilotImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/copilot/compile': {
      id: '/api/copilot/compile'
      path: '/api/copilot/compile'
      fullPath: '/api/copilot/compile'
      preLoaderRoute: typeof ApiCopilotCompileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/channels/status': {
      id: '/api/channels/status'
      path: '/api/channels/status'
      fullPath: '/api/channels/status'
      preLoaderRoute: typeof ApiChannelsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/channels/disconnect': {
      id: '/api/channels/disconnect'
      path: '/api/channels/disconnect'
      fullPath: '/api/channels/disconnect'
      preLoaderRoute: typeof ApiChannelsDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/channels/connect': {
      id: '/api/channels/connect'
      path: '/api/channels/connect'
      fullPath: '/api/channels/connect'
      preLoaderRoute: typeof ApiChannelsConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/zid': {
      id: '/api/auth/zid'
      path: '/api/auth/zid'
      fullPath: '/api/auth/zid'
      preLoaderRoute: typeof ApiAuthZidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/salla': {
      id: '/api/auth/salla'
      path: '/api/auth/salla'
      fullPath: '/api/auth/salla'
      preLoaderRoute: typeof ApiAuthSallaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/resolve-merchant': {
      id: '/api/auth/resolve-merchant'
      path: '/api/auth/resolve-merchant'
      fullPath: '/api/auth/resolve-merchant'
      preLoaderRoute: typeof ApiAuthResolveMerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/keeta': {
      id: '/api/auth/keeta'
      path: '/api/auth/keeta'
      fullPath: '/api/auth/keeta'
      preLoaderRoute: typeof ApiAuthKeetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/email-bridge': {
      id: '/api/auth/email-bridge'
      path: '/api/auth/email-bridge'
      fullPath: '/api/auth/email-bridge'
      preLoaderRoute: typeof ApiAuthEmailBridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/zid/app-market': {
      id: '/api/webhooks/zid/app-market'
      path: '/api/webhooks/zid/app-market'
      fullPath: '/api/webhooks/zid/app-market'
      preLoaderRoute: typeof ApiWebhooksZidAppMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/$': {
      id: '/api/public/v1/$'
      path: '/api/public/v1/$'
      fullPath: '/api/public/v1/$'
      preLoaderRoute: typeof ApiPublicV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/weekly-margin-digest': {
      id: '/api/public/hooks/weekly-margin-digest'
      path: '/api/public/hooks/weekly-margin-digest'
      fullPath: '/api/public/hooks/weekly-margin-digest'
      preLoaderRoute: typeof ApiPublicHooksWeeklyMarginDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/webhook-retry': {
      id: '/api/public/hooks/webhook-retry'
      path: '/api/public/hooks/webhook-retry'
      fullPath: '/api/public/hooks/webhook-retry'
      preLoaderRoute: typeof ApiPublicHooksWebhookRetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/webhook-intelligence-retry': {
      id: '/api/public/hooks/webhook-intelligence-retry'
      path: '/api/public/hooks/webhook-intelligence-retry'
      fullPath: '/api/public/hooks/webhook-intelligence-retry'
      preLoaderRoute: typeof ApiPublicHooksWebhookIntelligenceRetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scrape-all': {
      id: '/api/public/hooks/scrape-all'
      path: '/api/public/hooks/scrape-all'
      fullPath: '/api/public/hooks/scrape-all'
      preLoaderRoute: typeof ApiPublicHooksScrapeAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/map-monitor': {
      id: '/api/public/hooks/map-monitor'
      path: '/api/public/hooks/map-monitor'
      fullPath: '/api/public/hooks/map-monitor'
      preLoaderRoute: typeof ApiPublicHooksMapMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/group-expire': {
      id: '/api/public/hooks/group-expire'
      path: '/api/public/hooks/group-expire'
      fullPath: '/api/public/hooks/group-expire'
      preLoaderRoute: typeof ApiPublicHooksGroupExpireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/flash-start': {
      id: '/api/public/hooks/flash-start'
      path: '/api/public/hooks/flash-start'
      fullPath: '/api/public/hooks/flash-start'
      preLoaderRoute: typeof ApiPublicHooksFlashStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/flash-end': {
      id: '/api/public/hooks/flash-end'
      path: '/api/public/hooks/flash-end'
      fullPath: '/api/public/hooks/flash-end'
      preLoaderRoute: typeof ApiPublicHooksFlashEndRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/dispatch-queue': {
      id: '/api/public/hooks/dispatch-queue'
      path: '/api/public/hooks/dispatch-queue'
      fullPath: '/api/public/hooks/dispatch-queue'
      preLoaderRoute: typeof ApiPublicHooksDispatchQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/dispatch-confirmation': {
      id: '/api/public/hooks/dispatch-confirmation'
      path: '/api/public/hooks/dispatch-confirmation'
      fullPath: '/api/public/hooks/dispatch-confirmation'
      preLoaderRoute: typeof ApiPublicHooksDispatchConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/copilot-schedules': {
      id: '/api/public/hooks/copilot-schedules'
      path: '/api/public/hooks/copilot-schedules'
      fullPath: '/api/public/hooks/copilot-schedules'
      preLoaderRoute: typeof ApiPublicHooksCopilotSchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/zid/callback': {
      id: '/api/auth/zid/callback'
      path: '/callback'
      fullPath: '/api/auth/zid/callback'
      preLoaderRoute: typeof ApiAuthZidCallbackRouteImport
      parentRoute: typeof ApiAuthZidRoute
    }
    '/api/auth/salla/callback': {
      id: '/api/auth/salla/callback'
      path: '/callback'
      fullPath: '/api/auth/salla/callback'
      preLoaderRoute: typeof ApiAuthSallaCallbackRouteImport
      parentRoute: typeof ApiAuthSallaRoute
    }
    '/api/auth/keeta/callback': {
      id: '/api/auth/keeta/callback'
      path: '/callback'
      fullPath: '/api/auth/keeta/callback'
      preLoaderRoute: typeof ApiAuthKeetaCallbackRouteImport
      parentRoute: typeof ApiAuthKeetaRoute
    }
    '/api/public/v1/webhooks/test-signature': {
      id: '/api/public/v1/webhooks/test-signature'
      path: '/api/public/v1/webhooks/test-signature'
      fullPath: '/api/public/v1/webhooks/test-signature'
      preLoaderRoute: typeof ApiPublicV1WebhooksTestSignatureRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminChannelsRoute: typeof AdminChannelsRoute
  AdminCodesRoute: typeof AdminCodesRoute
  AdminLiveAccessRoute: typeof AdminLiveAccessRoute
  AdminMerchantsRoute: typeof AdminMerchantsRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminChannelsRoute: AdminChannelsRoute,
  AdminCodesRoute: AdminCodesRoute,
  AdminLiveAccessRoute: AdminLiveAccessRoute,
  AdminMerchantsRoute: AdminMerchantsRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardPricingRoute: typeof DashboardPricingRoute
  DashboardRevenueHubRoute: typeof DashboardRevenueHubRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardScenariosSlugRoute: typeof DashboardScenariosSlugRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardPricingRoute: DashboardPricingRoute,
  DashboardRevenueHubRoute: DashboardRevenueHubRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardScenariosSlugRoute: DashboardScenariosSlugRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DocsGuidesRouteChildren {
  DocsGuidesAuthenticationRoute: typeof DocsGuidesAuthenticationRoute
  DocsGuidesQuickstartRoute: typeof DocsGuidesQuickstartRoute
  DocsGuidesSdkQuickstartRoute: typeof DocsGuidesSdkQuickstartRoute
  DocsGuidesWebhooksRoute: typeof DocsGuidesWebhooksRoute
}

const DocsGuidesRouteChildren: DocsGuidesRouteChildren = {
  DocsGuidesAuthenticationRoute: DocsGuidesAuthenticationRoute,
  DocsGuidesQuickstartRoute: DocsGuidesQuickstartRoute,
  DocsGuidesSdkQuickstartRoute: DocsGuidesSdkQuickstartRoute,
  DocsGuidesWebhooksRoute: DocsGuidesWebhooksRoute,
}

const DocsGuidesRouteWithChildren = DocsGuidesRoute._addFileChildren(
  DocsGuidesRouteChildren,
)

interface DocsRouteChildren {
  DocsChangelogRoute: typeof DocsChangelogRoute
  DocsGuidesRoute: typeof DocsGuidesRouteWithChildren
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsChangelogRoute: DocsChangelogRoute,
  DocsGuidesRoute: DocsGuidesRouteWithChildren,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface MarginDashboardRouteChildren {
  MarginDashboardChannelsRoute: typeof MarginDashboardChannelsRoute
  MarginDashboardDemoRoute: typeof MarginDashboardDemoRoute
  MarginDashboardItemsRoute: typeof MarginDashboardItemsRoute
  MarginDashboardSettingsRoute: typeof MarginDashboardSettingsRoute
  MarginDashboardUploadRoute: typeof MarginDashboardUploadRoute
  MarginDashboardIndexRoute: typeof MarginDashboardIndexRoute
}

const MarginDashboardRouteChildren: MarginDashboardRouteChildren = {
  MarginDashboardChannelsRoute: MarginDashboardChannelsRoute,
  MarginDashboardDemoRoute: MarginDashboardDemoRoute,
  MarginDashboardItemsRoute: MarginDashboardItemsRoute,
  MarginDashboardSettingsRoute: MarginDashboardSettingsRoute,
  MarginDashboardUploadRoute: MarginDashboardUploadRoute,
  MarginDashboardIndexRoute: MarginDashboardIndexRoute,
}

const MarginDashboardRouteWithChildren = MarginDashboardRoute._addFileChildren(
  MarginDashboardRouteChildren,
)

interface ApiAuthKeetaRouteChildren {
  ApiAuthKeetaCallbackRoute: typeof ApiAuthKeetaCallbackRoute
}

const ApiAuthKeetaRouteChildren: ApiAuthKeetaRouteChildren = {
  ApiAuthKeetaCallbackRoute: ApiAuthKeetaCallbackRoute,
}

const ApiAuthKeetaRouteWithChildren = ApiAuthKeetaRoute._addFileChildren(
  ApiAuthKeetaRouteChildren,
)

interface ApiAuthSallaRouteChildren {
  ApiAuthSallaCallbackRoute: typeof ApiAuthSallaCallbackRoute
}

const ApiAuthSallaRouteChildren: ApiAuthSallaRouteChildren = {
  ApiAuthSallaCallbackRoute: ApiAuthSallaCallbackRoute,
}

const ApiAuthSallaRouteWithChildren = ApiAuthSallaRoute._addFileChildren(
  ApiAuthSallaRouteChildren,
)

interface ApiAuthZidRouteChildren {
  ApiAuthZidCallbackRoute: typeof ApiAuthZidCallbackRoute
}

const ApiAuthZidRouteChildren: ApiAuthZidRouteChildren = {
  ApiAuthZidCallbackRoute: ApiAuthZidCallbackRoute,
}

const ApiAuthZidRouteWithChildren = ApiAuthZidRoute._addFileChildren(
  ApiAuthZidRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRoute: AccessRoute,
  AdminRoute: AdminRouteWithChildren,
  ApiReferenceRoute: ApiReferenceRoute,
  ChangelogRoute: ChangelogRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LegalRoute: LegalRoute,
  LoginRoute: LoginRoute,
  MarginRoute: MarginRoute,
  MarginDashboardRoute: MarginDashboardRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  RoiCalculatorRoute: RoiCalculatorRoute,
  SignupRoute: SignupRoute,
  ApiRegisterCodeRoute: ApiRegisterCodeRoute,
  ApiRestoreRoute: ApiRestoreRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  EmbedWidgetRoute: EmbedWidgetRoute,
  EmbeddedZidRoute: EmbeddedZidRoute,
  ProductsCompetitorsRoute: ProductsCompetitorsRoute,
  ProductsFieldIntelRoute: ProductsFieldIntelRoute,
  ProductsMarketRoute: ProductsMarketRoute,
  ProductsPricingRoute: ProductsPricingRoute,
  ProductsPromotionsRoute: ProductsPromotionsRoute,
  StoreSlugRoute: StoreSlugRoute,
  ApiAuthEmailBridgeRoute: ApiAuthEmailBridgeRoute,
  ApiAuthKeetaRoute: ApiAuthKeetaRouteWithChildren,
  ApiAuthResolveMerchantRoute: ApiAuthResolveMerchantRoute,
  ApiAuthSallaRoute: ApiAuthSallaRouteWithChildren,
  ApiAuthZidRoute: ApiAuthZidRouteWithChildren,
  ApiChannelsConnectRoute: ApiChannelsConnectRoute,
  ApiChannelsDisconnectRoute: ApiChannelsDisconnectRoute,
  ApiChannelsStatusRoute: ApiChannelsStatusRoute,
  ApiCopilotCompileRoute: ApiCopilotCompileRoute,
  ApiCopilotImagesRoute: ApiCopilotImagesRoute,
  ApiCopilotStoreRoute: ApiCopilotStoreRoute,
  ApiDisputeVoucherRoute: ApiDisputeVoucherRoute,
  ApiRepricingApplyRoute: ApiRepricingApplyRoute,
  ApiRepricingCatalogRoute: ApiRepricingCatalogRoute,
  ApiWebhooksPlatformRoute: ApiWebhooksPlatformRoute,
  ApiPublicHooksCopilotSchedulesRoute: ApiPublicHooksCopilotSchedulesRoute,
  ApiPublicHooksDispatchConfirmationRoute:
    ApiPublicHooksDispatchConfirmationRoute,
  ApiPublicHooksDispatchQueueRoute: ApiPublicHooksDispatchQueueRoute,
  ApiPublicHooksFlashEndRoute: ApiPublicHooksFlashEndRoute,
  ApiPublicHooksFlashStartRoute: ApiPublicHooksFlashStartRoute,
  ApiPublicHooksGroupExpireRoute: ApiPublicHooksGroupExpireRoute,
  ApiPublicHooksMapMonitorRoute: ApiPublicHooksMapMonitorRoute,
  ApiPublicHooksScrapeAllRoute: ApiPublicHooksScrapeAllRoute,
  ApiPublicHooksWebhookIntelligenceRetryRoute:
    ApiPublicHooksWebhookIntelligenceRetryRoute,
  ApiPublicHooksWebhookRetryRoute: ApiPublicHooksWebhookRetryRoute,
  ApiPublicHooksWeeklyMarginDigestRoute: ApiPublicHooksWeeklyMarginDigestRoute,
  ApiPublicV1SplatRoute: ApiPublicV1SplatRoute,
  ApiWebhooksZidAppMarketRoute: ApiWebhooksZidAppMarketRoute,
  ApiPublicV1WebhooksTestSignatureRoute: ApiPublicV1WebhooksTestSignatureRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
