/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RoiCalculatorRouteImport } from './routes/roi-calculator'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as ApiReferenceRouteImport } from './routes/api-reference'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ProductsPromotionsRouteImport } from './routes/products.promotions'
import { Route as ProductsPricingRouteImport } from './routes/products.pricing'
import { Route as ProductsMarketRouteImport } from './routes/products.market'
import { Route as ProductsFieldIntelRouteImport } from './routes/products.field-intel'
import { Route as ProductsCompetitorsRouteImport } from './routes/products.competitors'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardPromotionsRouteImport } from './routes/dashboard.promotions'
import { Route as DashboardPricingRouteImport } from './routes/dashboard.pricing'
import { Route as DashboardMarketRouteImport } from './routes/dashboard.market'
import { Route as DashboardFieldIntelRouteImport } from './routes/dashboard.field-intel'
import { Route as DashboardCompetitorsRouteImport } from './routes/dashboard.competitors'
import { Route as DashboardBenchmarksRouteImport } from './routes/dashboard.benchmarks'
import { Route as ApiPublicHooksScrapeAllRouteImport } from './routes/api/public/hooks/scrape-all'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RoiCalculatorRoute = RoiCalculatorRouteImport.update({
  id: '/roi-calculator',
  path: '/roi-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferenceRoute = ApiReferenceRouteImport.update({
  id: '/api-reference',
  path: '/api-reference',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ProductsPromotionsRoute = ProductsPromotionsRouteImport.update({
  id: '/products/promotions',
  path: '/products/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsPricingRoute = ProductsPricingRouteImport.update({
  id: '/products/pricing',
  path: '/products/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsMarketRoute = ProductsMarketRouteImport.update({
  id: '/products/market',
  path: '/products/market',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsFieldIntelRoute = ProductsFieldIntelRouteImport.update({
  id: '/products/field-intel',
  path: '/products/field-intel',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCompetitorsRoute = ProductsCompetitorsRouteImport.update({
  id: '/products/competitors',
  path: '/products/competitors',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPromotionsRoute = DashboardPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPricingRoute = DashboardPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMarketRoute = DashboardMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFieldIntelRoute = DashboardFieldIntelRouteImport.update({
  id: '/field-intel',
  path: '/field-intel',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCompetitorsRoute = DashboardCompetitorsRouteImport.update({
  id: '/competitors',
  path: '/competitors',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBenchmarksRoute = DashboardBenchmarksRouteImport.update({
  id: '/benchmarks',
  path: '/benchmarks',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiPublicHooksScrapeAllRoute = ApiPublicHooksScrapeAllRouteImport.update({
  id: '/api/public/hooks/scrape-all',
  path: '/api/public/hooks/scrape-all',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-reference': typeof ApiReferenceRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/roi-calculator': typeof RoiCalculatorRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/dashboard/benchmarks': typeof DashboardBenchmarksRoute
  '/dashboard/competitors': typeof DashboardCompetitorsRoute
  '/dashboard/field-intel': typeof DashboardFieldIntelRoute
  '/dashboard/market': typeof DashboardMarketRoute
  '/dashboard/pricing': typeof DashboardPricingRoute
  '/dashboard/promotions': typeof DashboardPromotionsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/products/competitors': typeof ProductsCompetitorsRoute
  '/products/field-intel': typeof ProductsFieldIntelRoute
  '/products/market': typeof ProductsMarketRoute
  '/products/pricing': typeof ProductsPricingRoute
  '/products/promotions': typeof ProductsPromotionsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/hooks/scrape-all': typeof ApiPublicHooksScrapeAllRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-reference': typeof ApiReferenceRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/roi-calculator': typeof RoiCalculatorRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/dashboard/benchmarks': typeof DashboardBenchmarksRoute
  '/dashboard/competitors': typeof DashboardCompetitorsRoute
  '/dashboard/field-intel': typeof DashboardFieldIntelRoute
  '/dashboard/market': typeof DashboardMarketRoute
  '/dashboard/pricing': typeof DashboardPricingRoute
  '/dashboard/promotions': typeof DashboardPromotionsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/products/competitors': typeof ProductsCompetitorsRoute
  '/products/field-intel': typeof ProductsFieldIntelRoute
  '/products/market': typeof ProductsMarketRoute
  '/products/pricing': typeof ProductsPricingRoute
  '/products/promotions': typeof ProductsPromotionsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/public/hooks/scrape-all': typeof ApiPublicHooksScrapeAllRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-reference': typeof ApiReferenceRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/roi-calculator': typeof RoiCalculatorRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/dashboard/benchmarks': typeof DashboardBenchmarksRoute
  '/dashboard/competitors': typeof DashboardCompetitorsRoute
  '/dashboard/field-intel': typeof DashboardFieldIntelRoute
  '/dashboard/market': typeof DashboardMarketRoute
  '/dashboard/pricing': typeof DashboardPricingRoute
  '/dashboard/promotions': typeof DashboardPromotionsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/products/competitors': typeof ProductsCompetitorsRoute
  '/products/field-intel': typeof ProductsFieldIntelRoute
  '/products/market': typeof ProductsMarketRoute
  '/products/pricing': typeof ProductsPricingRoute
  '/products/promotions': typeof ProductsPromotionsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/hooks/scrape-all': typeof ApiPublicHooksScrapeAllRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/api-reference'
    | '/changelog'
    | '/contact'
    | '/dashboard'
    | '/docs'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/roi-calculator'
    | '/signup'
    | '/terms'
    | '/dashboard/benchmarks'
    | '/dashboard/competitors'
    | '/dashboard/field-intel'
    | '/dashboard/market'
    | '/dashboard/pricing'
    | '/dashboard/promotions'
    | '/dashboard/settings'
    | '/products/competitors'
    | '/products/field-intel'
    | '/products/market'
    | '/products/pricing'
    | '/products/promotions'
    | '/dashboard/'
    | '/api/public/hooks/scrape-all'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/api-reference'
    | '/changelog'
    | '/contact'
    | '/docs'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/roi-calculator'
    | '/signup'
    | '/terms'
    | '/dashboard/benchmarks'
    | '/dashboard/competitors'
    | '/dashboard/field-intel'
    | '/dashboard/market'
    | '/dashboard/pricing'
    | '/dashboard/promotions'
    | '/dashboard/settings'
    | '/products/competitors'
    | '/products/field-intel'
    | '/products/market'
    | '/products/pricing'
    | '/products/promotions'
    | '/dashboard'
    | '/api/public/hooks/scrape-all'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/api-reference'
    | '/changelog'
    | '/contact'
    | '/dashboard'
    | '/docs'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/roi-calculator'
    | '/signup'
    | '/terms'
    | '/dashboard/benchmarks'
    | '/dashboard/competitors'
    | '/dashboard/field-intel'
    | '/dashboard/market'
    | '/dashboard/pricing'
    | '/dashboard/promotions'
    | '/dashboard/settings'
    | '/products/competitors'
    | '/products/field-intel'
    | '/products/market'
    | '/products/pricing'
    | '/products/promotions'
    | '/dashboard/'
    | '/api/public/hooks/scrape-all'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApiReferenceRoute: typeof ApiReferenceRoute
  ChangelogRoute: typeof ChangelogRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DocsRoute: typeof DocsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RoiCalculatorRoute: typeof RoiCalculatorRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  ProductsCompetitorsRoute: typeof ProductsCompetitorsRoute
  ProductsFieldIntelRoute: typeof ProductsFieldIntelRoute
  ProductsMarketRoute: typeof ProductsMarketRoute
  ProductsPricingRoute: typeof ProductsPricingRoute
  ProductsPromotionsRoute: typeof ProductsPromotionsRoute
  ApiPublicHooksScrapeAllRoute: typeof ApiPublicHooksScrapeAllRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roi-calculator': {
      id: '/roi-calculator'
      path: '/roi-calculator'
      fullPath: '/roi-calculator'
      preLoaderRoute: typeof RoiCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-reference': {
      id: '/api-reference'
      path: '/api-reference'
      fullPath: '/api-reference'
      preLoaderRoute: typeof ApiReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/products/promotions': {
      id: '/products/promotions'
      path: '/products/promotions'
      fullPath: '/products/promotions'
      preLoaderRoute: typeof ProductsPromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/pricing': {
      id: '/products/pricing'
      path: '/products/pricing'
      fullPath: '/products/pricing'
      preLoaderRoute: typeof ProductsPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/market': {
      id: '/products/market'
      path: '/products/market'
      fullPath: '/products/market'
      preLoaderRoute: typeof ProductsMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/field-intel': {
      id: '/products/field-intel'
      path: '/products/field-intel'
      fullPath: '/products/field-intel'
      preLoaderRoute: typeof ProductsFieldIntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/competitors': {
      id: '/products/competitors'
      path: '/products/competitors'
      fullPath: '/products/competitors'
      preLoaderRoute: typeof ProductsCompetitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/promotions': {
      id: '/dashboard/promotions'
      path: '/promotions'
      fullPath: '/dashboard/promotions'
      preLoaderRoute: typeof DashboardPromotionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pricing': {
      id: '/dashboard/pricing'
      path: '/pricing'
      fullPath: '/dashboard/pricing'
      preLoaderRoute: typeof DashboardPricingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/market': {
      id: '/dashboard/market'
      path: '/market'
      fullPath: '/dashboard/market'
      preLoaderRoute: typeof DashboardMarketRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/field-intel': {
      id: '/dashboard/field-intel'
      path: '/field-intel'
      fullPath: '/dashboard/field-intel'
      preLoaderRoute: typeof DashboardFieldIntelRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/competitors': {
      id: '/dashboard/competitors'
      path: '/competitors'
      fullPath: '/dashboard/competitors'
      preLoaderRoute: typeof DashboardCompetitorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/benchmarks': {
      id: '/dashboard/benchmarks'
      path: '/benchmarks'
      fullPath: '/dashboard/benchmarks'
      preLoaderRoute: typeof DashboardBenchmarksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/hooks/scrape-all': {
      id: '/api/public/hooks/scrape-all'
      path: '/api/public/hooks/scrape-all'
      fullPath: '/api/public/hooks/scrape-all'
      preLoaderRoute: typeof ApiPublicHooksScrapeAllRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardBenchmarksRoute: typeof DashboardBenchmarksRoute
  DashboardCompetitorsRoute: typeof DashboardCompetitorsRoute
  DashboardFieldIntelRoute: typeof DashboardFieldIntelRoute
  DashboardMarketRoute: typeof DashboardMarketRoute
  DashboardPricingRoute: typeof DashboardPricingRoute
  DashboardPromotionsRoute: typeof DashboardPromotionsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBenchmarksRoute: DashboardBenchmarksRoute,
  DashboardCompetitorsRoute: DashboardCompetitorsRoute,
  DashboardFieldIntelRoute: DashboardFieldIntelRoute,
  DashboardMarketRoute: DashboardMarketRoute,
  DashboardPricingRoute: DashboardPricingRoute,
  DashboardPromotionsRoute: DashboardPromotionsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApiReferenceRoute: ApiReferenceRoute,
  ChangelogRoute: ChangelogRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DocsRoute: DocsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RoiCalculatorRoute: RoiCalculatorRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  ProductsCompetitorsRoute: ProductsCompetitorsRoute,
  ProductsFieldIntelRoute: ProductsFieldIntelRoute,
  ProductsMarketRoute: ProductsMarketRoute,
  ProductsPricingRoute: ProductsPricingRoute,
  ProductsPromotionsRoute: ProductsPromotionsRoute,
  ApiPublicHooksScrapeAllRoute: ApiPublicHooksScrapeAllRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
