/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardPromotionsRouteImport } from './routes/dashboard.promotions'
import { Route as DashboardPricingRouteImport } from './routes/dashboard.pricing'
import { Route as DashboardMarketRouteImport } from './routes/dashboard.market'
import { Route as DashboardFieldIntelRouteImport } from './routes/dashboard.field-intel'
import { Route as DashboardCompetitorsRouteImport } from './routes/dashboard.competitors'
import { Route as DashboardBenchmarksRouteImport } from './routes/dashboard.benchmarks'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPromotionsRoute = DashboardPromotionsRouteImport.update({
  id: '/dashboard/promotions',
  path: '/dashboard/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPricingRoute = DashboardPricingRouteImport.update({
  id: '/dashboard/pricing',
  path: '/dashboard/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMarketRoute = DashboardMarketRouteImport.update({
  id: '/dashboard/market',
  path: '/dashboard/market',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFieldIntelRoute = DashboardFieldIntelRouteImport.update({
  id: '/dashboard/field-intel',
  path: '/dashboard/field-intel',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCompetitorsRoute = DashboardCompetitorsRouteImport.update({
  id: '/dashboard/competitors',
  path: '/dashboard/competitors',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBenchmarksRoute = DashboardBenchmarksRouteImport.update({
  id: '/dashboard/benchmarks',
  path: '/dashboard/benchmarks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/benchmarks': typeof DashboardBenchmarksRoute
  '/dashboard/competitors': typeof DashboardCompetitorsRoute
  '/dashboard/field-intel': typeof DashboardFieldIntelRoute
  '/dashboard/market': typeof DashboardMarketRoute
  '/dashboard/pricing': typeof DashboardPricingRoute
  '/dashboard/promotions': typeof DashboardPromotionsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/benchmarks': typeof DashboardBenchmarksRoute
  '/dashboard/competitors': typeof DashboardCompetitorsRoute
  '/dashboard/field-intel': typeof DashboardFieldIntelRoute
  '/dashboard/market': typeof DashboardMarketRoute
  '/dashboard/pricing': typeof DashboardPricingRoute
  '/dashboard/promotions': typeof DashboardPromotionsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/benchmarks': typeof DashboardBenchmarksRoute
  '/dashboard/competitors': typeof DashboardCompetitorsRoute
  '/dashboard/field-intel': typeof DashboardFieldIntelRoute
  '/dashboard/market': typeof DashboardMarketRoute
  '/dashboard/pricing': typeof DashboardPricingRoute
  '/dashboard/promotions': typeof DashboardPromotionsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard/benchmarks'
    | '/dashboard/competitors'
    | '/dashboard/field-intel'
    | '/dashboard/market'
    | '/dashboard/pricing'
    | '/dashboard/promotions'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard/benchmarks'
    | '/dashboard/competitors'
    | '/dashboard/field-intel'
    | '/dashboard/market'
    | '/dashboard/pricing'
    | '/dashboard/promotions'
    | '/dashboard/settings'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard/benchmarks'
    | '/dashboard/competitors'
    | '/dashboard/field-intel'
    | '/dashboard/market'
    | '/dashboard/pricing'
    | '/dashboard/promotions'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  DashboardBenchmarksRoute: typeof DashboardBenchmarksRoute
  DashboardCompetitorsRoute: typeof DashboardCompetitorsRoute
  DashboardFieldIntelRoute: typeof DashboardFieldIntelRoute
  DashboardMarketRoute: typeof DashboardMarketRoute
  DashboardPricingRoute: typeof DashboardPricingRoute
  DashboardPromotionsRoute: typeof DashboardPromotionsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/promotions': {
      id: '/dashboard/promotions'
      path: '/dashboard/promotions'
      fullPath: '/dashboard/promotions'
      preLoaderRoute: typeof DashboardPromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/pricing': {
      id: '/dashboard/pricing'
      path: '/dashboard/pricing'
      fullPath: '/dashboard/pricing'
      preLoaderRoute: typeof DashboardPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/market': {
      id: '/dashboard/market'
      path: '/dashboard/market'
      fullPath: '/dashboard/market'
      preLoaderRoute: typeof DashboardMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/field-intel': {
      id: '/dashboard/field-intel'
      path: '/dashboard/field-intel'
      fullPath: '/dashboard/field-intel'
      preLoaderRoute: typeof DashboardFieldIntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/competitors': {
      id: '/dashboard/competitors'
      path: '/dashboard/competitors'
      fullPath: '/dashboard/competitors'
      preLoaderRoute: typeof DashboardCompetitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/benchmarks': {
      id: '/dashboard/benchmarks'
      path: '/dashboard/benchmarks'
      fullPath: '/dashboard/benchmarks'
      preLoaderRoute: typeof DashboardBenchmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  DashboardBenchmarksRoute: DashboardBenchmarksRoute,
  DashboardCompetitorsRoute: DashboardCompetitorsRoute,
  DashboardFieldIntelRoute: DashboardFieldIntelRoute,
  DashboardMarketRoute: DashboardMarketRoute,
  DashboardPricingRoute: DashboardPricingRoute,
  DashboardPromotionsRoute: DashboardPromotionsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
